### ISSUE TITLE
aria2 and sen2cor dependencies

### ISSUE THREAD

**Issue by RAJohansen** [ranghetti/sen2r#109]
When starting a new R session, both the aria2 and sen2cor dependencies are missing and required to be re-downloaded. 

Currently, the Sen2cor folder is located in the sen2r folder within my R library.

**Comment by ranghetti** [comment]
I fixed this bug two days ago in the development version (#103), but I had not moved them in the master version.
If you reinstall the package now, you should solve it.
Let me know,

**Comment by RAJohansen** [comment]
Reinstalling the package worked.
