### ISSUE TITLE
Alcune immagini non vengono individuate da sen2_list()

### ISSUE THREAD

**Issue by saveriofrancini** [ranghetti/sen2r#112]
Intanto grazie per questo utilissimo pacchetto.
Vorrei però riportare un bug.
Le seguenti immagini, che sulla piattaforma copernicus sono disponibili, 
non vengono infatti individuate da sen2_list()
  "timewindow": ["2017-07-07", "2017-07-09"],
  "s2tiles_selected": ["32TPN", "32TPP", "32TQP"]

**Comment by saveriofrancini** [comment]
Grazie

Un'altra domanda.
Nella cartella "<cartella di output>"  ho già scaricato più di mille
immagini.
Eseguendo le funzioni l1c_list() e s2_download() come indicato
vengono scaricati soltanto i file mancanti o vengono riscaricati tutti?

Grazie in anticipo



Il giorno gio 20 set 2018 alle ore 17:25 Luigi Ranghetti <
notifications@github.com> ha scritto:

**Comment by ranghetti** [comment]
`s2_download()` controlla se esistono già dei files e non li riscarica: nel caso dei prodotti con la nomenclatura compatta, se esiste una cartella col nome corrispondente il download viene ignorato; nel caso di quelli vecchi col nome lungo, viene effettuato un controllo sui granuli in esso contenuti. I prodotti esistenti devono essere stati scaricati con `s2_download()` per garantire che tutto funzioni correttamente; se fossero stati scaricati a mano, devono essere decompressi (il controllo avviene sulle cartelle, non sugli zip) senza sottocartelle intermedie (per esempio: S2B_MSIL1C_20170708T101029_N0205_R022_T32TQP_20170708T101125.zip deve essere stato decompresso direttamente in S2B_MSIL1C_20170708T101029_N0205_R022_T32TQP_20170708T101125.SAFE, non in una cartella S2B_MSIL1C_20170708T101029_N0205_R022_T32TQP_20170708T101125 contenente a sua volta S2B_MSIL1C_20170708T101029_N0205_R022_T32TQP_20170708T101125.SAFE).

**Comment by saveriofrancini** [comment]
Ottimo lavoro, ora funziona.

 Se posso vorrei dare due suggerimenti:

- Sarebbe bello poter stabilire la massima copertura nuvolosa che può avere un'immagine per essere scaricata, anche dalla funzione `sen2r()` e non solo da `sen2_list()`

- Lo stesso se i tiles da scaricare fossero individuati automaticamente grazie all'estenzione dell'aoi inserita tramite il parametro `extent`

**Comment by ranghetti** [comment]
Grazie dei suggerimenti; il primo sarà implementato a breve (#122).
Non ho capito bene il secondo: attualmente sia `s2_list()` che la GUI rilevano i tiles coperti dall'aoi. Quale modifica propone rispetto a questo?

**Comment by saveriofrancini** [comment]
Le volte che ho utilizzato `sen2r()` specificando l'aoi e non i tiles ho spesso ricevuto un errore che riferiva che non vi erano prodotti disponibili con le caratteristiche specificate. Ma magari ho sbagliato qualcosa io.

In tutti i casi sto incontrando un nuovo errore che non riesco a risolvere:

- `Error in lapply(X = X, FUN = FUN, ...) : object 'req_masks' not found`

Questo si presenta sistematicamente quando dovrebbero essere applicate le maschere per rimuovere le nuvole, mi sa aiutare?

**Comment by saveriofrancini** [comment]
La mia impressione è che il problema si presenti se non viene specificato il percorso per i tiles e quindi quando questi vengono generati come raster virtuali. 
Dovendo inserire il percorso per i tiles i tempi di calcolo necessari aumentano moltissimo.

**Comment by ranghetti** [comment]
In entrambi i casi non riesco a riprodurre gli errori: le chiederei di aprire due issue separate riportando, in ognuna, un esempio funzionante (es. allegando il json dei parametri). Questo mi aiuta a capire in che "combinazione" di parametri l'errore si verifica.
