### ISSUE TITLE
Bad ID and Password on https://scihub.copernicus.eu/dhus/#/home

### ISSUE THREAD

**Issue by pobsteta** [ranghetti/sen2r#115]
I want to use my ID and Password with sen2r() function. When i log with the URL https://scihub.copernicus.eu/dhus/#/home it works, but when i save with sen2r() in the web interface, i have in R that ID and Password are not right ?

**Comment by ranghetti** [comment]
This is strange.

Can you paste the exact error which you receive in R?

Also, make these tests:
1. run [`read_scihub_login()`](https://ranghetti.github.io/sen2r/reference/scihub_login.html) and ensure that the output corresponds to your credentials;
2. if they do not correspond, try adding them with [`write_scihub_login("username", "password")`](https://ranghetti.github.io/sen2r/reference/scihub_login.html).

**Comment by pobsteta** [comment]
read_scihub_login() is right. I sent the picture error and my sen2.josn file
![sen2r01](https://user-images.githubusercontent.com/932599/46285499-f7922700-c57b-11e8-9e39-861c148a1794.png)
[sen2.zip](https://github.com/ranghetti/sen2r/files/2433705/sen2.zip)

**Comment by pobsteta** [comment]
i have always the same result with the 2 methods you suggere ?

**Comment by pobsteta** [comment]
yes it works, thanks !
