### ISSUE TITLE
Change the installations of gdal sen2r uses 

### ISSUE THREAD

**Issue by AndrewMAPSS** [ranghetti/sen2r#121]
Hi,

Thank you for a fantastic package. I presented it today at a course and a few participants had problems with getting sen2r to run. We got the attached error ('Probably broken install of gdal at 'C:/PRGRA~2/TerrSet/GDAL/bin' Error in strsplit(sapply(drivers, function(x) { : non-character argument}'). All of them had previous or older versions of gdal installed that they could unfortunately not delete as they were needed for other programs. They installed a newer version using the check_sen2r() function. Is it possible to change which install of gdal sen2r uses?

![sen2r error](https://user-images.githubusercontent.com/44402448/47361407-1e9ecd00-d6d2-11e8-9683-d891d96ab718.JPG)

**Comment by AndrewMAPSS** [comment]
Thanks a million @ranghetti , worked perfectly.

**Comment by ranghetti** [comment]
Happy to know it.
Remember that you have to repeat this workaround in case you update/reinstall the package. To simplify it you could save a copy of the modified json file.
