### ISSUE TITLE
Setting thumbnails = false does not work

### ISSUE THREAD

**Issue by saveriofrancini** [ranghetti/sen2r#124]
I'm setting thumbnails parameter false in my json file but thumbnails images are still created.
Thank's for you job

**Comment by ranghetti** [comment]
Now should be fixed.
Can you reinstall the devel branch
```r
devtools::install_github("ranghetti/sen2r", ref = "devel")
```
and check it?

**Comment by saveriofrancini** [comment]
Solved, well done!
