### ISSUE TITLE
Cloud masking error

### ISSUE THREAD

**Issue by saveriofrancini** [ranghetti/sen2r#126]
This is myjsonfile.json:
{
  "preprocess": [true],
  "s2_levels": ["l1c", "l2a"],
  "sel_sensor": ["s2a", "s2b"],
  "online": [false],
  "downloader": ["aria2"],
  "overwrite_safe": [false],
  "rm_safe": ["no"],
  "step_atmcorr": ["auto"],
  "timewindow": ["2017-05-26", "2017-06-12"],
  "timeperiod": ["full"],
  "extent": ["C:/sen2r_clfr_geolab/travaglini/1600_travaglini"],
  "s2tiles_selected": ["32TMQ"],
  "s2orbits_selected": [null],
  "list_prods": ["BOA"],
  "list_indices": ["CSI"],
  "index_source": ["BOA"],
  "mask_type": ["cloud_shadow_cirrus"],
  "max_mask": [100],
  "mask_smooth": [0],
  "mask_buffer": [0],
  "clip_on_extent": [true],
  "extent_as_mask": [false],
  "extent_name": ["area-studio"],
  "reference_path": [null],
  "res": [null],
  "res_s2": ["10m"],
  "unit": ["Meter"],
  "proj": [null],
  "resampling": ["near"],
  "resampling_scl": ["near"],
  "outformat": ["GTiff"],
  "index_datatype": ["Float64"],
  "compression": ["DEFLATE"],
  "overwrite": [false],
  "path_l1c": ["C:/sen2r_clfr_geolab/1C"],
  "path_l2a": ["C:/sen2r_clfr_geolab/2A"],
  "path_tiles": ["C:/sen2r_clfr_geolab/travaglini/tiles"],
  "path_merged": [null],
  "path_out": ["C:/sen2r_clfr_geolab/travaglini/output"],
  "path_indices": ["C:/sen2r_clfr_geolab/travaglini/indices"],
  "path_subdirs": [true],
  "thumbnails": [false],
  "pkg_version": ["0.3.3"]
}

And here what's going on when I run `> sen2r("myjsonfile.json")`

```
[2018-10-24 18:17:32] Starting sen2r execution.
[2018-10-24 18:19:12] Computing output names...
[2018-10-24 18:19:24] Updating output names...
[2018-10-24 18:19:25] Starting to merge tiles by orbit.
 Using projection "+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs".
[2018-10-24 18:19:29] Starting to edit geometry (clip, reproject, rescale).
[2018-10-24 18:19:55] Starting to apply cloud masks.
Error in lapply(X = X, FUN = FUN, ...) : object 'req_masks' not found
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": La sintassi del nome del file, della directory o del volume non è corretta
Error in lapply(X = X, FUN = FUN, ...) : object 'req_masks' not found
Error in lapply(X = X, FUN = FUN, ...) : object 'req_masks' not found
Error in lapply(X = X, FUN = FUN, ...) : object 'req_masks' not found
[2018-10-24 18:19:55] Execution of sen2r session terminated.
Warning message:
 Some files were not created:
"C:/sen2r_clfr_geolab/travaglini/output/BOA/S2A2A_20170527_065_area-studio_BOA_10.tif"
"C:/sen2r_clfr_geolab/travaglini/output/BOA/S2A2A_20170530_108_area-studio_BOA_10.tif"
"C:/sen2r_clfr_geolab/travaglini/output/BOA/S2A2A_20170606_065_area-studio_BOA_10.tif"
"C:/sen2r_clfr_geolab/travaglini/output/BOA/S2A2A_20170609_108_area-studio_BOA_10.tif"
"C:/sen2r_clfr_geolab/travaglini/indices/CSI/S2A2A_20170527_065_area-studio_CSI_10.tif"
"C:/sen2r_clfr_geolab/travaglini/indices/CSI/S2A2A_20170530_108_area-studio_CSI_10.tif"
"C:/sen2r_clfr_geolab/travaglini/indices/CSI/S2A2A_20170606_065_area-studio_CSI_10.tif"
"C:/sen2r_clfr_geolab/travaglini/indices/CSI/S2A2A_20170609_108_area-studio_CSI_10.tif""
These files will be skipped during next executions from the current parameter file ("oflinemode.json").
To try again to build them, remove the file "oflinemode_ignorelist.txt". 
```

**Comment by ranghetti** [comment]
Ok, the problem is due to a change made in commit 026cd1ef43303a6c42346f523382f850e65fcdb6, in which mask "cloud_shadow_cirrus" was renamed to "clear_sky". I have not maintained a compatibiltiy with the old name since the package is in development; sorry for that. Changing 
```json
"mask_type": ["cloud_shadow_cirrus"],
```
to
```json
"mask_type": ["clear_sky"],
```
in the JSON should solve.

Let me know,

**Comment by saveriofrancini** [comment]
Solved.

Thank you so much
