### ISSUE TITLE
Document installation dependencies

### ISSUE THREAD

**Issue by noerw** [ranghetti/sen2r#132]
The documentation only mentions runtime dependencies. However some non-trivial dependencies are required for installation of the package.

For me the following packages were required on Fedora 27 linux (this list is probably not exhaustive as I might had some preinstalled already):
- for jqr: `jq-devel`
- for protolite: `protobuf-devel`
- for geojsonio: `v8-314-devel`
- for sf: `gdal-devel proj-devel proj-epsg proj-nad geos-devel udunits2-devel`

Mentioning these in the readme and/or documentation would make installation far more straightforward.

**Comment by ranghetti** [comment]
Thank you for your useful suggestion. I will update the documentation after having performed clean installations on different OS.
For now, I add here the packages which were required to install it on an almost clean Ubuntu 18.4: `libssl-dev`, `libcairo2-dev`, `libgdal-dev`, `libjq-dev`, `libprotobuf-dev`, `protobuf-compiler`, `libudunits2-dev`, `libv8-dev`.
