### ISSUE TITLE
`s2_mask()` does not run in parallel

### ISSUE THREAD

**Issue by saveriofrancini** [ranghetti/sen2r#134]
Running:
```
sen2r(
  gui = FALSE, preprocess = TRUE, online = F,
  s2tiles_selected = "32TLQ", 
  mask_type = "clear_sky", max_mask = 80, mask_smooth = 0, mask_buffer = 0,
  clip_on_extent = F, extent_as_mask = F, 
  res_s2 = "10m", unit = "Meter", 
  outformat = "GTiff",
  compression = "DEFLATE", overwrite = FALSE,
  path_l2a = file.path(getwd(), "2A"),
  list_indices = "NDVI",
  path_indices = file.path(getwd(), "indices"), 
  path_subdirs = T, 
  thumbnails = F,
  tmpdir = file.path(getwd(), "tmp"), 
  parallel = TRUE, use_python = T, rmtmp = F
)
```
`s2_calcindices()` run in parallel while `s2_mask()` no

**Comment by ranghetti** [comment]
The parallelisation of `s2_mask()` function was a bit laborious (acutally no gains in term of speed were reached by parallelising that function), so for now it was forced to run in singlecore. However we are working 
1) to speed it up ([new_maskapply](https://github.com/ranghetti/sen2r/tree/feature/new_maskapply));
2) to implement a new modality which should parallelise processing chains of different dates instead that specific internal functions (#86).

**Comment by ranghetti** [comment]
Both were implemented (for now, in devel).
