### ISSUE TITLE
sen2r script error

### ISSUE THREAD

**Issue by claudiuu93** [ranghetti/sen2r#137]
When I run this command:
```r
remotes::install_github("ranghetti/sen2r") 
```
I get this error:
```
√  checking for file 'C:\Users\ALINA\AppData\Local\Temp\Rtmpcdgdmc\remotes31fc2c0d6a5c\ranghetti-sen2r-2411ede/DESCRIPTION' ...
-  preparing 'sen2r': (2.8s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (1.1s)
-  checking for empty or unneeded directories
-  building 'sen2r_0.3.3.tar.gz'
   
Error in i.p(...) : no packages were specified
```
Does anybody know how to resolve this?

**Comment by ranghetti** [comment]
It seems to be a problem with connectivity or repo availability.
Can you check your internet connection and try with another repository, e.g.
```r
remotes::install_github("ranghetti/sen2r", repos="https://stat.ethz.ch/CRAN")
```
?

**Comment by claudiuu93** [comment]
These packages have more recent versions available.
Which would you like to update?

I tried the command remotes::install_github("ranghetti/sen2r", repos="https://stat.ethz.ch/CRAN") and then I got the message
1:   raster (2.6-7 -> 2.8-4) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 
I wrote 8, for example and then I get the same error
√  checking for file 'C:\Users\ALINA\AppData\Local\Temp\RtmpGsdrf6\remotes1f901c461d43\ranghetti-sen2r-2411ede/DESCRIPTION' ...
-  preparing 'sen2r': (1.3s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (582ms)
-  checking for empty or unneeded directories
-  building 'sen2r_0.3.3.tar.gz'
   
Error in i.p(...) : no packages were specified
>

**Comment by claudiuu93** [comment]
I installed the new raster version, but I get the same error:
Downloading GitHub repo ranghetti/sen2r@master
√  checking for file 'C:\Users\ALINA\AppData\Local\Temp\Rtmpi8564h\remotese841f30110b\ranghetti-sen2r-2411ede/DESCRIPTION' ...
-  preparing 'sen2r': (3.6s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (598ms)
-  checking for empty or unneeded directories
-  building 'sen2r_0.3.3.tar.gz'
   
Error in i.p(...) : no packages were specified
>

**Comment by claudiuu93** [comment]
The Rtools is in the path. How can I verify if the Rtool is corectly installed? Is there any function in R to install Rtool?

**Comment by lbusett** [comment]
I'd suggest first updating all your packages (if you did not already do that) as proposed by Luigi. 

`update.packages(ask = FALSE)`

It is better if you do that from a "fresh" R/RStudio instance. 

Also, it could be useful if you could share your sessionInfo()

**Comment by ranghetti** [comment]
Hi @claudiuu93, have you solved the issue?
