### ISSUE TITLE
 mask_smooth and mask_buffer

### ISSUE THREAD

**Issue by saveriofrancini** [ranghetti/sen2r#143]
Setting  mask_smooth or mask_buffer non-zero returns: "same files were not created", and no output files are created. 

Best, Saverio

**Comment by ranghetti** [comment]
Please post:
- the content of the parameter file,
- the existing files in the used path (if not empty),
- the output of the command.

**Comment by ranghetti** [comment]
Should be fixed in v.1.0.0
