### ISSUE TITLE
Dependencies wget and aria2 not installed after check_sen2r_deps()

### ISSUE THREAD

**Issue by FrancescoReyes** [ranghetti/sen2r#147]
On Windows 10, 64bit computer, R-3.5.0:
After installation of sen2r, I performed the dependency check with check_sen2r_deps(). wget ed aria2 were not installed. 

Basically, connection to https://eternallybored.org never gets through.

so attempts to install wget from shiny page, return the following error message:
> cannot open URL ' https://eternallybored.org/misc/wget/releases/wget-1.19.4-win64.zip' download.file

same for attempts to install aria2 using shiny page. In this case the shiny page just closes and R console returns the error message:
> Listening on http://127.0.0.1:3864
> trying URL 'https://eternallybored.org/misc/wget/releases/wget-1.19.4-win64.zip'
> Warning in download.file(wget_url, wget_zip) : InternetOpenUrl failed: 'A connection with the server 
> could not be established'
> Warning: Error in download.file: cannot open URL
> 'https://eternallybored.org/misc/wget/releases/wget-1.19.4-win64.zip'
>   79: download.file
>   78: install_wget
>   75: load_binpaths
>   74: import_s2download
>   73: observeEventHandler
>    2: runApp
>    1: check_sen2r_deps

**Comment by lbusett** [comment]
Is it possible that you are behind a firewall blocking the connections? 

What do you get if, from R, you do: 

```
wzip_save_path = "___some_path___/wget.zip"
download.file("https://eternallybored.org/misc/wget/releases/wget-1.19.4-win64.zip", "wzip_save_path")
```
(with ___some_path___ corresponding to a valid path on your machine)?

**Comment by ranghetti** [comment]
What about trying to install sen2cor?

**Comment by FrancescoReyes** [comment]
This happens:
> wzip_save_path = "E:\\Precision_Agriculture\\wget.zip"
> download.file("https://eternallybored.org/misc/wget/releases/wget-1.19.4-win64.zip", "wzip_save_path")
trying URL 'https://eternallybored.org/misc/wget/releases/wget-1.19.4-win64.zip'
Error in download.file("https://eternallybored.org/misc/wget/releases/wget-1.19.4-win64.zip", : cannot open URL 'https://eternallybored.org/misc/wget/releases/wget-1.19.4-win64.zip'
In addition: Warning message:
In download.file("https://eternallybored.org/misc/wget/releases/wget-1.19.4-win64.zip", : InternetOpenUrl failed: 'Impossibile stabilire una connessione con il server'

Think about using [Signal](https://signal.org/), [ProtonMail](https://protonmail.com/) and [DuckDuckGo](https://duckduckgo.com/?t=ffsb)
for your messaging, email and web-browsing privacy

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by FrancescoReyes** [comment]
The installation of sen2cor was already successful.

In ogni caso possiamo anche parlare in italiano, visto che non stiamo scrivendo su github, o sbaglio?

Francesco

Think about using [Signal](https://signal.org/), [ProtonMail](https://protonmail.com/) and [DuckDuckGo](https://duckduckgo.com/?t=ffsb)
for your messaging, email and web-browsing privacy

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by lbusett** [comment]
Ciao Francesco. Siamo sempre su github, per cui meglio l'inglese se possibile ;-) 

I still think you have a firewall / antivirus problem. What happens if you open the "https://eternallybored.org/misc/wget/releases/wget-1.19.4-win64.zip"  link from a browser? 

Lorenzo

**Comment by FrancescoReyes** [comment]
The link works from my personal laptop but doesn't from my office computer.
It seems it's not my antivirus preventing the website from opening. Maybe a firewall in the local network?...

So I downloaded the package on one PC and sent it to the other one by email.
Then I tried to install it via:
>Tools>Install Packages...>Install from: Package Archive FIle (.zip; tar.gz)
but getting the error

>

install.packages("C:/Users/Ut1/Downloads/wget-1.19.4-win64.zip", repos = NULL, type = "win.binary")

Installing package into ‘C:/Users/Ut1/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)

Warning in install.packages :
  cannot open compressed file 'wget-1.19.4-win64/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection

Cheers,
Francesco

Think about using [Signal](https://signal.org/), [ProtonMail](https://protonmail.com/) and [DuckDuckGo](https://duckduckgo.com/?t=ffsb)
for your messaging, email and web-browsing privacy

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ranghetti** [comment]
`install.packages()` cannot work in this case, because Wget is not an R package, but a binary.
To manually install it, try in this way:
1. download and extract [Wget](https://eternallybored.org/misc/wget/releases/wget-1.19.4-win64.zip);
2. open File Explorer (*Esplora risorse*) and go in the directory where sen2r is installed; to know its path, type in R:
    ```r
    system.file(package="sen2r")
   ```
3. copy  `wget.exe` (extracted from the Zip) in this directory;
4. in R, type these commands:
    ```r
    binpaths <- sen2r:::load_binpaths()
    wget_path <- sen2r::normalize_path(file.path(system.file(package="sen2r"),"wget.exe"))
    file.exists(wget_path)
    ````
5. if this last command returns TRUE (it should), do:
    ```r
    binpaths <- sen2r:::load_binpaths()
    binpaths$wget <- wget_path
    writeLines(jsonlite::toJSON(binpaths, pretty=TRUE), attr(binpaths, "path"))
    ````
Then restart R and reload the package.

Let us know if it will solve,

**Comment by FrancescoReyes** [comment]
Installation was successful,
all dependencies checked by check_sen2r_deps() are satisfied, including wget and aria2.

Thank you!
Francesco

Think about using [Signal](https://signal.org/), [ProtonMail](https://protonmail.com/) and [DuckDuckGo](https://duckduckgo.com/?t=ffsb)
for your messaging, email and web-browsing privacy

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
