### ISSUE TITLE
error when launching sen2cor()

### ISSUE THREAD

**Issue by jimoreira** [ranghetti/sen2r#154]
the error is as follows
```
[2019-02-22 23:11:36] Starting sen2r execution.
Error in if (!grepl(pythonhome_new, path_exi, fixed = TRUE)) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="NA": El sistema no puede encontrar el archivo especificado
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="NA": El sistema no puede encontrar el archivo especificado
```
i have repeted the procedure for the installation several times and no luck.
thanks for your help!

**Comment by ranghetti** [comment]
It seems to be related to your Python installation.
1. Which is your operating system? If you are on Windows, have you installed GDAL using the [OSGeo4W installer](http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe)? If not, do it before continuing.
2. Please post the output of
    ```r
    Sys.getenv("PATH")
    Sys.getenv("PYTHONHOME")
    Sys.getenv("PYTHONPATH")
    sen2r:::load_binpaths()
    ```

**Comment by jimoreira** [comment]
hi, thanks for your quick reply.
1. I do, and also I have a previous installation, both in the system path.
2. ` Sys.getenv("PATH")
[1] "C:\\Program Files\\R\\R-3.5.1\\bin\\i386;C:\\Program Files\\Python37\\Scripts\\;C:\\Program Files\\Python37\\;C:\\Python27\\Scripts;C:\\Python27;C:\\Program Files\\Microsoft MPI\\Bin\\;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\PuTTY\\;C:\\Program Files (x86)\\GDAL;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;\"C:\\Program Files\\GNUWin32\\bin;C:\\G77\\bin\";C:\\Strawberry\\c\\bin;C:\\Strawberry\\perl\\site\\bin;C:\\Strawberry\\perl\\bin;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Users\\javie\\Anaconda3\\python;C:\\Users\\javie\\build\\6SV\\1.1\\6SV1.1;C:\\cygwin64\\bin;C:\\OSGeo4W64\\bin;C:\\Users\\javie\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\snap\\bin;C:\\Users\\javie\\AppData\\Local\\atom\\bin;C:\\Program Files\\Git\\bin;C:\\Program Files\\R\\R-3.4.3\\bin;C:\\Program Files\\Docker Toolbox;C:\\Users\\javie\\Anaconda3\\Library\\bin;C:\\Users\\javie\\Anaconda3\\Lib;C:\\Users\\javie\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\javie\\AppData\\Local\\Microsoft\\WindowsApps;\"C:\\Program Files\\GNUWin32\\bin;C:\\G77\\bin\";C:\\Users\\javie\\Anaconda3\\python;C:\\Users\\javie\\AppData\\Local\\Google\\Cloud SDK\\google-cloud-sdk\\bin;C:\\Users\\javie\\build\\6SV\\1.1\\6SV1.1;"`
`Sys.getenv("PYTHONHOME")
[1] "NA"`
`Sys.getenv("PYTHONPATH")
[1] "NA"`
` sen2r:::load_binpaths()
$`gdalbuildvrt`
[1] "C:\\PROGRA~2\\GDAL\\GDALBU~1.EXE"

$gdal_translate
[1] "C:\\PROGRA~2\\GDAL\\GDAL_T~1.EXE"

$gdalwarp
[1] "C:\\PROGRA~2\\GDAL\\gdalwarp.exe"

$python
[1] "C:\\PROGRA~2\\GDAL\\python.exe"

$gdal_calc
[1] "C:\\PROGRA~2\\GDAL\\python.exe C:\\PROGRA~2\\GDAL\\GDAL_C~1.PY"

$gdal_polygonize
[1] "C:\\PROGRA~2\\GDAL\\python.exe C:\\PROGRA~2\\GDAL\\GDAL_P~1.PY"

$gdal_fillnodata
[1] "C:\\PROGRA~2\\GDAL\\python.exe C:\\PROGRA~2\\GDAL\\GDAL_F~1.PY"

$gdaldem
[1] "C:\\PROGRA~2\\GDAL\\gdaldem.exe"

$gdalinfo
[1] "C:\\PROGRA~2\\GDAL\\gdalinfo.exe"

$ogrinfo
[1] "C:\\PROGRA~2\\GDAL\\ogrinfo.exe"

$wget
[1] "C:\\Users\\javie\\Documents\\R\\win-library\\3.5\\sen2r\\wget.exe"

$aria2c
[1] "C:\\Users\\javie\\Documents\\R\\win-library\\3.5\\sen2r\\aria2c.exe"

$sen2cor
[1] "C:\\Users\\javie\\DOCUME~1\\R\\WIN-LI~1\\3.5\\sen2r\\sen2cor\\SEN2CO~1.05-\\L2A_PR~1.BAT"

attr(,"path")
[1] "C:/Users/javie/Documents/R/win-library/3.5/sen2r/extdata/paths.json"`

I can see now that those "Na" are the problem, but I don't know yet, how to solve it. 
I have installed both python 2.7 and 3.7 and that usually gave me troubles when installing new soft, sen2r run with both? 
thanks again

**Comment by ranghetti** [comment]
I forgot one step: after installing GDAL through OSGeo4W, you must reload your GDAL installation in order to use it instead of the one existing at `C:\PROGRA~2\GDAL` with the OSGeo4W.

To do it:
```r
sen2r:::check_gdal(force=TRUE)
sen2r:::init_python()
```

This should normally fix; you can check it repeating the steps in my previous post:
```r
Sys.getenv("PATH")
Sys.getenv("PYTHONHOME")
Sys.getenv("PYTHONPATH")
sen2r:::load_binpaths()
```

In case the output of these commands would be similar to the old one (PYTHONHOME and PYTHONPATH at NA, and `C:\\PROGRA~2\\GDAL` instead than `C:\\OSGeo4W64\\bin` in the paths), use this command (particular for your case):
```r
sen2r:::check_gdal(gdal_path="C:/OSGeo4W64", force=TRUE)
sen2r:::init_python()
```
and then re-check.

Let me know,

**Comment by jimoreira** [comment]
strange, 
when `sen2r:::check_gdal(gdal_path="C:/OSGeo4W64", force=TRUE)`
it tells me that isn´t a valid option, so it takes the other one installed anyway. So, i delete the other one from the path list, and try again, and gave me following error. 
`Searching for a valid GDAL installation...
Probably broken install of gdal at 'C:/OSGEO4~1/bin/'
<simpleError in as.Date.default(unlist(versions)): do not know how to convert 'unlist(versions)' to class “Date”>
Probably broken install of gdal at 'C:/OSGEO4~1/bin/'
<simpleError in as.Date.default(unlist(versions)): do not know how to convert 'unlist(versions)' to class “Date”>
 GDAL was not found in the system PATH, search in the full system (this could take some time, please wait)...
Probably broken install of gdal at 'C:/OSGEO4~1/bin/'
Probably broken install of gdal at 'C:/PROGRA~1/QGIS2~1.14/bin/'
Probably broken install of gdal at 'C:/PROGRA~1/QGIS3~1.4/bin/'
Probably broken install of gdal at 'C:/Users/javie/DOCUME~1/R/WIN-LI~1/3.5/sen2r/sen2cor/SEN2CO~1.05-/bin/'
Probably broken install of gdal at 'C:/OSGEO4~1/bin/'
<simpleError in as.Date.default(unlist(versions)): do not know how to convert 'unlist(versions)' to class “Date”>
Error:  GDAL was not found, please install it.
In addition: There were 40 warnings (use warnings() to see them)`

**Comment by ranghetti** [comment]
Can you post the following two R outputs?
```r
list.files("C:\\OSGeo4W64\\bin", "^gdal.+\\.exe$")
shell("C:\\OSGeo4W64\\bin\\gdalinfo.exe --version")
```

**Comment by jimoreira** [comment]
`list.files("C:\\OSGeo4W64\\bin", "^gdal.+\\.exe$")
 [1] "gdal_contour.exe"     "gdal_grid.exe"        "gdal_rasterize.exe"  
 [4] "gdal_translate.exe"   "gdaladdo.exe"         "gdalbuildvrt.exe"    
 [7] "gdaldem.exe"          "gdalenhance.exe"      "gdalinfo.exe"        
[10] "gdallocationinfo.exe" "gdalmanage.exe"       "gdalserver.exe"      
[13] "gdalsrsinfo.exe"      "gdaltindex.exe"       "gdaltransform.exe"   
[16] "gdalwarp.exe"  `

`shell("C:\\OSGeo4W64\\bin\\gdalinfo.exe --version")
ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_BAG.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_BAG.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_FITS.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_FITS.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_GMT.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_GMT.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_HDF4.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_HDF4.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_HDF4Image.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_HDF4Image.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_HDF5.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_HDF5.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_HDF5Image.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_HDF5Image.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_KEA.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_KEA.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_netCDF.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\gdal_netCDF.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\ogr_MSSQLSpatial.dll
193: %1 no es una aplicación Win32 válida.

ERROR 1: Can't load requested DLL: C:\Program Files (x86)\GDAL\gdalplugins\ogr_MSSQLSpatial.dll
193: %1 no es una aplicación Win32 válida.

GDAL 2.4.0, released 2018/12/14`

**Comment by ranghetti** [comment]
For some reasons, `C:\OSGeo4W64\bin\gdalinfo.exe` (one of the GDAL binaries installed in `C:\OSGeo4W64`) is using libraries installed in `C:\Program Files (x86)\GDAL`, which now are missing.

I think you should clean up your system (I do not know if a faster method is available):
1. remove all your GDAL installations;
2. use `regedit.exe` to clean all the paths related to GDAL from your PATH system variable (see e.g. [this link](https://www.opentechguides.com/how-to/article/windows-10/113/windows-10-set-path.html));
3. reinstall GDAL using the OSGeo4W installer;
4. repeat 
    ```r
    sen2r:::check_gdal(gdal_path="C:/OSGeo4W64", force=TRUE)
    sen2r:::init_python()
    ```

**Comment by jimoreira** [comment]
ok, done, 
`sen2r:::check_gdal(gdal_path="C:/OSGeo4W64", force=TRUE)
 Searching for a valid GDAL installation...
 GDAL version in use: 2.4.0`

gdal seems to be ok, but, the following error when init_python
`sen2r:::init_python()
Error in initialize_python(required_module, use_environment) : 
  Your current architecture is 32bit however this version of Python is compiled for 64bit.`

**Comment by ranghetti** [comment]
Oops..! I am sorry, I assumed your OS to be a 64-bit system, so I gave you the link to install a 64-bit OSGeo4W. You should reinstall it from [here](http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86.exe) (no need to re-clean PATH), or using the `check_sen2r_deps()` function in sen2r (which checks for system architecture).

**Comment by jimoreira** [comment]
I do, and python its also 64bit, so, I'm guessing the problem is that R isn't 64 bit.

**Comment by ranghetti** [comment]
I have not understood, do you have 1) a 32-bit Windows OS or 2) a 64-bit Windows OS with a 32-bit R? In the first case, installing the 32-bit OSGeo4W version would install also a 32-bit Python binary (isn't it? I have not tested it on a 32-bit Windows OS, so I'm only supposing it); the second case would be stranger, while the R installer for Windows is unique for both architectures.

**Comment by jimoreira** [comment]
Windows is 64-bit so, in any case, I'm in the second situation.
how can i check the R or Rstudio version?

**Comment by ranghetti** [comment]
https://www.digitalcitizen.life/3-ways-learn-whether-windows-program-64-bit-or-32-bit and search for "rsession" (it's ok Rstudio to be at 32-bit, for what I know)

**Comment by jimoreira** [comment]
chequing in Rstudio, 
R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: i386-w64-mingw32/i386 (32-bit)

Rstudio, choose to use 32-bit R but i have installed both of them..i guess this is the problem.

**Comment by jimoreira** [comment]
that's it. Go to Rstudio/Tools/Global Options/R version (choose a 64-bit) 
With that, sen2r working.
Man, I can't thank you enough! you definitely are taking care of your clients!! 
thanks again!
