### ISSUE TITLE
GDAL Issue

### ISSUE THREAD

**Issue by onuryuzugullu** [ranghetti/sen2r#156]
I'm having the following error now. How may I solve it?

[2019-03-01 11:00:52] Starting sen2r execution.
Probably broken install of gdal at 'C:/PROGRA~1/QGIS3~1.4/bin/'
Error in as.Date.default(unlist(versions)) : 
  do not know how to convert 'unlist(versions)' to class “Date”

**Comment by ranghetti** [comment]
Try installing the OSGeo4W version of GDAL:
- download the installer ([32-bit](http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86.exe) or [64-bit](http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe));
- select GDAL and install it;
- restart R and type:
    ```r
    sen2r:::check_gdal(force=TRUE)
    sen2r:::init_python()
    ```

If this will not solve, please paste the output of
```r
Sys.getenv("PATH")
Sys.getenv("PYTHONHOME")
Sys.getenv("PYTHONPATH")
sen2r:::load_binpaths()
```

**Comment by ranghetti** [comment]
@onuryuzugullu, have you solved?
If not, fell free to re-open this issue.

**Comment by onuryuzugullu** [comment]
Yes I had Uninstall and install GDAL. Seems to be working. Thanks :)
