### ISSUE TITLE
Error in sen2r()

### ISSUE THREAD

**Issue by hagc** [ranghetti/sen2r#157]
When trying to run `sen2r()`, I get the following error:

```
> [2019-03-06 14:04:24] Starting sen2r execution.
Error in system2(command = python, args = paste0("\"", config_script,  : 
  'CreateProcess' failed to run 'C:\OSGEO4~1\bin\python.exe "C:/Users/hcosta/Documents/R/win-library/3.5/reticulate/config/config.py"'
In addition: Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": A sintaxe do nome do ficheiro, do nome do directório ou da etiqueta do volume é incorrecta
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": A sintaxe do nome do ficheiro, do nome do directório ou da etiqueta do volume é incorrecta
```
Some time ago, I was able to run` sen2r()` perfectly, but possibly I messed up things while following #152. I don't have admin rights and my session info is:

```
> R version 3.5.2 (2018-12-20)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=Portuguese_Portugal.1252  LC_CTYPE=Portuguese_Portugal.1252    LC_MONETARY=Portuguese_Portugal.1252
> [4] LC_NUMERIC=C                         LC_TIME=Portuguese_Portugal.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] shiny_1.2.0 sen2r_1.0.0
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.0           lattice_0.20-38      shinyWidgets_0.4.5   prettyunits_1.0.2    class_7.3-14         ps_1.3.0            
>  [7] assertthat_0.2.0     rprojroot_1.3-2      digest_0.6.18        foreach_1.4.4        V8_2.0               mime_0.6            
> [13] R6_2.4.0             backports_1.1.3      leaflet.extras_1.0.0 e1071_1.7-0.1        httr_1.4.0           geojson_0.3.2       
> [19] pillar_1.3.1         rlang_0.3.1          lazyeval_0.2.1       curl_3.3             rstudioapi_0.9.0     data.table_1.12.0   
> [25] callr_3.1.1          raster_2.8-19        geojsonio_0.6.0      R.utils_2.8.0        R.oo_1.22.0          Matrix_1.2-15       
> [31] reticulate_1.11.1    shinyjs_1.0          rgdal_1.3-9          stringr_1.4.0        jqr_1.1.0            foreign_0.8-71      
> [37] htmlwidgets_1.3      munsell_0.5.0        compiler_3.5.2       httpuv_1.4.5.1       pkgconfig_2.0.2      pkgbuild_1.0.2      
> [43] rgeos_0.4-2          htmltools_0.3.6      mapedit_0.4.3        tibble_2.0.1         codetools_0.2-15     XML_3.98-1.18       
> [49] crayon_1.3.4         withr_2.1.2          later_0.8.0          sf_0.7-3             R.methodsS3_1.7.1    grid_3.5.2          
> [55] jsonlite_1.6         xtable_1.8-3         DBI_1.0.0            magrittr_1.5         scales_1.0.0         units_0.6-2         
> [61] stringi_1.3.1        cli_1.0.1            fs_1.2.6             promises_1.0.1       remotes_2.0.2        leaflet_2.0.2       
> [67] doParallel_1.0.14    sp_1.3-1             shinyFiles_0.7.2     iterators_1.0.10     tools_3.5.2          gdalUtils_2.0.1.14  
> [73] crosstalk_1.0.0      processx_3.2.1       parallel_3.5.2       colorspace_1.4-0     maptools_0.9-5       shinydashboard_0.7.1
> [79] classInt_0.3-1      
```

**Comment by ranghetti** [comment]
I have not understood: which operations of issue #152 have you followed? Maybe you have changed environmental variables (referring to `C:\OSGEO4W64`) but without having a OSGeo4W environment installed at that path?

**Comment by hagc** [comment]
I don't remember well to be honest, but remember to check %PYTHONHOME% in the Windows command prompt, and alike. I don't have admin right, so can't change much. It's strange that `sen2r()` was working, but not any more.
Yes, I have OSGeo4W in C:\OSGeo4W64. I know it's difficult to solve problems remotely, but if you have any hint, based on the error messages, I appreciate it.

**Comment by ranghetti** [comment]
First, try reinstalling the package **reticulate**. Then, type these commands and post the output:
```r
sen2r::init_python()
sen2r:::check_gdal(force=TRUE)
sen2r:::load_binpaths()
```
and check if the error launching `sen2r()` still appears.

**Comment by hagc** [comment]
I installed the reticulate package and run the commands, but the errors persist.

`> sen2r::init_python()`

> Error in system2(command = python, args = paste0("\"", config_script,  : 
>   'CreateProcess' failed to run 'C:\OSGEO4~1\bin\python.exe "C:/Users/hcosta/Documents/R/win-library/3.5/reticulate/config/config.py"'
> In addition: Warning messages:
> 1: In normalizePath(path.expand(path), winslash, mustWork) :
>   path[1]="": A sintaxe do nome do ficheiro, do nome do directório ou da etiqueta do volume é incorrecta
> 2: In normalizePath(path.expand(path), winslash, mustWork) :
>   path[1]="": A sintaxe do nome do ficheiro, do nome do directório ou da etiqueta do volume é incorrecta

`> sen2r:::check_gdal(force=TRUE)`
 

> Searching for a valid GDAL installation...
>  GDAL version in use: 2.4.0

`> sen2r:::load_binpaths()`

> $gdalbuildvrt
> [1] "C:\\OSGEO4~1\\bin\\GDALBU~1.EXE"
> 
> $gdal_translate
> [1] "C:\\OSGEO4~1\\bin\\GDAL_T~1.EXE"
> 
> $gdalwarp
> [1] "C:\\OSGEO4~1\\bin\\gdalwarp.exe"
> 
> $python
> [1] "C:\\OSGEO4~1\\bin\\python.exe"
> 
> $gdal_calc
> [1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_C~1.PY"
> 
> $gdal_polygonize
> [1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_P~2.PY"
> 
> $gdal_fillnodata
> [1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_F~1.PY"
> 
> $gdaldem
> [1] "C:\\OSGEO4~1\\bin\\gdaldem.exe"
> 
> $gdalinfo
> [1] "C:\\OSGEO4~1\\bin\\gdalinfo.exe"
> 
> $ogrinfo
> [1] "C:\\OSGEO4~1\\bin\\ogrinfo.exe"
> 
> $wget
> [1] "C:\\Users\\hcosta\\Documents\\R\\win-library\\3.5\\sen2r\\wget.exe"
> 
> attr(,"path")
> [1] "C:/Users/hcosta/Documents/R/win-library/3.5/sen2r/extdata/paths.json"

`> sen2r::sen2r()`

> [2019-03-06 15:54:07] Starting sen2r execution.
> Error in system2(command = python, args = paste0("\"", config_script,  : 
>   'CreateProcess' failed to run 'C:\OSGEO4~1\bin\python.exe "C:/Users/hcosta/Documents/R/win-library/3.5/reticulate/config/config.py"'

**Comment by hagc** [comment]
without the annoying strikethrough text:

$gdalbuildvrt
[1] "C:\\OSGEO4\~1\\bin\\GDALBU~1.EXE"

$gdal_calc
[1] "C:\\OSGEO4\~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_C\~1.PY"

$gdal_polygonize
[1] "C:\\OSGEO4\~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_P\~2.PY"

$gdal_fillnodata
[1] "C:\\OSGEO4\~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_F\~1.PY"

**Comment by ranghetti** [comment]
Paste the output of these commands (they will not solve, but they are useful to understand if the error is related to **reticulate** or **sen2r**):
```r
reticulate::use_python(sen2r:::load_binpaths()$python, required = TRUE)
reticulate::import_builtins()
reticulate::import("os")
```

**Comment by hagc** [comment]
`> reticulate::use_python(sen2r:::load_binpaths()$python, required = TRUE)`
Nothing outputted by this command

`> reticulate::import_builtins()`

> Error in system2(command = python, args = paste0("\"", config_script,  : 
>   'CreateProcess' failed to run 'C:\OSGEO4~1\bin\python.exe "C:/Users/hcosta/Documents/R/win-library/3.5/reticulate/config/config.py"'

`> reticulate::import("os")`

> Error in system2(command = python, args = paste0("\"", config_script,  : 
>   'CreateProcess' failed to run 'C:\OSGEO4~1\bin\python.exe "C:/Users/hcosta/Documents/R/win-library/3.5/reticulate/config/config.py"'

**Comment by ranghetti** [comment]
This suggests it is an error related to the package **reticulate**.
If removing the PYTHONHOME and PYTHONPATH environments will not solve, you can search a similar problem within [reticulate issues](https://github.com/rstudio/reticulate/issues) or opening there a new one.

**Comment by hagc** [comment]
Thank you very much for your help and developing sen2r.
