### ISSUE TITLE
s2_calcindices PVI MSBI output NA or NULL

### ISSUE THREAD

**Issue by FrancescoReyes** [ranghetti/sen2r#160]
Dear Luigi,

I tried to use the s2_calcindices() function to calculate a number of indices c("NDVI", "MSBI","MTVI2","PVI") on a subset of a S2 product (obtained through gdal_warp and a shape as mask).

   indici_da_calcolare <- c("NDVI", "MSBI", "MTVI2","PVI")
   s2_calcindices( infiles = path_clip_campo, 
                    outdir = index_campo_folder, 
                    indices = indici_da_calcolare, 
                    source = "BOA" )

the produced "NDVI" and "MTVI2" indices look good, while the raster output for "MSBI","PVI" contain only NA values. 
I guessed that, for PVI, the problem mught be the lack of a0 and a1 parameters. So I changed the instruction as follows:

    s2_calcindices( infiles = path_clip_campo, 
                    outdir = index_campo_folder, 
                    indices = indici_da_calcolare, 
                    source = "BOA",
                    parameters = list("PVI" = list("a0" = parameter_a0_PVI,
                                                   "a1" = parameter_a1_PVI))
                    )
but getting as output just:
NULL
and no file created.

Do you have suggestions on how to procede?

**Comment by ranghetti** [comment]
Hi, actually I did not yet test sufficiently the use of indices which require parameters (they are all non-checked ones), so I did not provide a sufficient documentation.
By the way, you can try to use them following (for now) these notes:

1. obtain the formula of the index in this way:
    ```r
    idxlist <- list_indices()
    idxlist[idxlist$name %in% indici_da_calcolare, c("name", "s2_formula")]
    ```
2. check the name of the parameters in the formula (e.g., in your case the formula of the PVI index is `((1)/(sqrt(power(par_a,2)+1)))*(band_8-par_a-par_b)`). In case of non-checked indices, ensure also that the formula corresponds to what you actually want to compute!
3. associate the names `par_a`, `par_b` and `par_x` present in the formula with your parameters (in your case, you need to realise which among `parameter_a0_PVI` and `parameter_a1_PVI` is `par_a` and which is `par_b`);
4. for the argument `parameters`, use this syntax:
    ```r
    list("PVI" = list("a" = parameter_aX_PVI, "b" = parameter_aY_PVI))
    ```
    so, for each index you must provide a named list in which names are `a`, `b` or `x` (not `a0`, `a1` or other names).

Also remember to delete the existing raster with NA values (or to use `overwrite = TRUE`) and to use `proc_mode = "raster"` to avoid error #152.

**Comment by ranghetti** [comment]
@FrancescoReyes ,
commit 3e8debdbc9dbd73e0d5d87adebe4c2f82204b4a8 in #162 should have fixed some inconsistencies in parsing formulas; check it and let me know if the issue reported by mail is fixed.

**Comment by FrancescoReyes** [comment]
How to update the package without reinstalling the whole of it?

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by ranghetti** [comment]
This is not possible, you need to reinstall it.
