### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jeaggu** [ranghetti/sen2r#161]
Hi,
I have tried to install the software on different windows machines but I always get the same problem at the end when I try to run the Sen2r() function, any idea how to fix this?

Thanks!
```
> sen2r()
[2019-03-13 23:08:43] Starting sen2r execution.
Error in if (!grepl(pythonhome_new, path_exi, fixed = TRUE)) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": The filename, directory name, or volume label syntax is incorrect
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": The filename, directory name, or volume label syntax is incorrect
```

**Comment by ranghetti** [comment]
Hi,
first of all, have a look to issue #154 to check if you are on the same situation (different architectures among OS and RStudio).
If it would not solve, please post the outputs which I required in that issue.

**Comment by jeaggu** [comment]
Hi and thanks for the fast reply!

I did all the steps you suggest in  #154 
This is the output I get after doing the last step:
--------------------------------------------------
remove all your GDAL installations;
use regedit.exe to clean all the paths related to GDAL from your PATH system variable (see e.g. this link);
reinstall GDAL using the OSGeo4W installer;
repeat
sen2r:::check_gdal(gdal_path="C:/OSGeo4W64", force=TRUE)
sen2r:::init_python()
-------------------------------------------------
The output is: 
sen2r:::check_gdal(gdal_path="C:/OSGeo4W64", force=TRUE)
 Searching for a valid GDAL installation...
 GDAL version in use: 2.4.0
Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\OSGEO4~1\bin\/python.exe": The system cannot find the file specified
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\OSGEO4~1\bin\/gdal_calc.py": The system cannot find the file specified
3: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\OSGEO4~1\bin\/python.exe": The system cannot find the file specified
4: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\OSGEO4~1\bin\/gdal_polygonize.py": The system cannot find the file specified
5: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\OSGEO4~1\bin\/python.exe": The system cannot find the file specified
6: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\OSGEO4~1\bin\/gdal_fillnodata.py": The system cannot find the file specified

sen2r:::init_python()
Error in if (!grepl(pythonhome_new, path_exi, fixed = TRUE)) { : 
  missing value where TRUE/FALSE needed


So, I re-installed Python in case something was wrong with it but after repeating the operation nothing changed.
This is weird because I have been able to run Sen2Cor from command line....

Thanks for any tips

**Comment by ranghetti** [comment]
In that issue I assumed that GDAL were reinstalled in `C:/OSGeo4W64`; where did you reinstall it? If the location is different (as it seems), replace your specific location in 
```r
sen2r:::check_gdal(gdal_path="C:/OSGeo4W64", force=TRUE)
```

**Comment by jeaggu** [comment]
The installation was done in C:/

Now I have re-run all what you suggested in #154

Sys.getenv("PATH")
[1] "D:\\SoftwareInstalledHere\\Anaconda2_27;D:\\SoftwareInstalledHere\\Anaconda2_27\\Scripts;D:\\SoftwareInstalledHere\\Anaconda2_27\\Library\\bin;C:\\Program Files\\R\\R-3.5.2\\bin\\x64;C:\\Python27;D:\\SoftwareInstalledHere\\Anaconda2_27;D:\\SoftwareInstalledHere\\Anaconda2_27\\Library\\mingw-w64\\bin;D:\\SoftwareInstalledHere\\Anaconda2_27\\Library\\usr\\bin;D:\\SoftwareInstalledHere\\Anaconda2_27\\Library\\bin;D:\\SoftwareInstalledHere\\Anaconda2_27\\Scripts;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Git LFS;C:\\Program Files\\TortoiseGit\\bin;D:\\Downloads_Jesus\\phylocom-4.2\\w32\\phylocom;D:\\SoftwareInstalledHere\\snap\\bin"

Sys.getenv("PYTHONHOME")
[1] "NA"

> Sys.getenv("PYTHONPATH")
[1] "NA"


sen2r:::load_binpaths()
$gdalbuildvrt
[1] "C:\\OSGEO4~1\\bin\\GDALBU~1.EXE"

$gdal_translate
[1] "C:\\OSGEO4~1\\bin\\GDAL_T~1.EXE"

$gdalwarp
[1] "C:\\OSGEO4~1\\bin\\gdalwarp.exe"

$python
[1] "C:\\OSGEO4~1\\bin\\python.exe"

$gdal_calc
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\gdal_calc.py"

$gdal_polygonize
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\gdal_polygonize.py"

$gdal_fillnodata
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\gdal_fillnodata.py"

$gdaldem
[1] "C:\\OSGEO4~1\\bin\\gdaldem.exe"

$gdalinfo
[1] "C:\\OSGEO4~1\\bin\\gdalinfo.exe"

$ogrinfo
[1] "C:\\OSGEO4~1\\bin\\ogrinfo.exe"

attr(,"path")
[1] "C:/Users/Jesus_Aquirre/Documents/R/win-library/3.5/sen2r/extdata/paths.json"


So, Python is installed in C:\\Python27

**Comment by ranghetti** [comment]
Probably I was not clear in my previous messages. I write here below the steps which you should perform in the right order, to be sure all the steps were performed (sorry for repetitions).

1. have you checked the architectures of both your OS and of your R installation (see the last 4 posts in issue #154)? Post here both OS and R architectures after checking.
2. have you installed GDAL using the OSGeo4W installer? If so, post the installation path (the complete path, not only C:\); if neither, install it (choosing the right installer: [this](http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe) for 64-bit or [this](http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86.exe) for 32-bit) and post the installation path (it should be C:/OSGeo4W64).
3. launch `sen2r:::check_gdal(gdal_path="C:/OSGeo4W64", force=TRUE)`, replacing `"C:/OSGeo4W64"` with the correct path.
4. launch `sen2r:::load_binpaths()` and check if the error is solved.

**Comment by jeaggu** [comment]
Hi Luigi, I just followed your advice, see results below:

1-  Post here both OS and R architectures after checking  
Windows is 64-bit 
 
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

2- GDAL was installed using the OSGeo4W installer for 64 bits. This is where it is and the files in there:

list.files("C:\\OSGeo4W64\\bin", "^gdal.+\\.exe$")
 [1] "gdal_contour.exe"     "gdal_grid.exe"        "gdal_rasterize.exe"   "gdal_translate.exe"   "gdaladdo.exe"         "gdalbuildvrt.exe"     "gdaldem.exe"         
 [8] "gdalenhance.exe"      "gdalinfo.exe"         "gdallocationinfo.exe" "gdalmanage.exe"       "gdalserver.exe"       "gdalsrsinfo.exe"      "gdaltindex.exe"      
[15] "gdaltransform.exe"    "gdalwarp.exe" 

3-I launched the sen2cor leaving the path as you showed because there is where I have the OSGeo4W installed:

sen2r:::check_gdal(gdal_path="C:/OSGeo4W64", force=TRUE)
 Searching for a valid GDAL installation...
 GDAL version in use: 2.4.0

Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\OSGEO4~1\bin\/python.exe": The system cannot find the file specified
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\OSGEO4~1\bin\/gdal_calc.py": The system cannot find the file specified
3: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\OSGEO4~1\bin\/python.exe": The system cannot find the file specified
4: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\OSGEO4~1\bin\/gdal_polygonize.py": The system cannot find the file specified
5: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\OSGEO4~1\bin\/python.exe": The system cannot find the file specified
6: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\OSGEO4~1\bin\/gdal_fillnodata.py": The system cannot find the file specified

4-Launching sen2r returns this:

sen2r:::load_binpaths()
$gdalbuildvrt
[1] "C:\\OSGEO4~1\\bin\\GDALBU~1.EXE"

$gdal_translate
[1] "C:\\OSGEO4~1\\bin\\GDAL_T~1.EXE"

$gdalwarp
[1] "C:\\OSGEO4~1\\bin\\gdalwarp.exe"

$python
[1] "C:\\OSGEO4~1\\bin\\python.exe"

$gdal_calc
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\gdal_calc.py"

$gdal_polygonize
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\gdal_polygonize.py"

$gdal_fillnodata
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\gdal_fillnodata.py"

$gdaldem
[1] "C:\\OSGEO4~1\\bin\\gdaldem.exe"

$gdalinfo
[1] "C:\\OSGEO4~1\\bin\\gdalinfo.exe"

$ogrinfo
[1] "C:\\OSGEO4~1\\bin\\ogrinfo.exe"

attr(,"path")
[1] "C:/Users/Jesus_Aquirre/Documents/R/win-library/3.5/sen2r/extdata/paths.json"

5. However, when I go to C:\\OSGEO4~1\\bin\\   I cannot find the python.exe files, is this normal?

**Comment by ranghetti** [comment]
It is strange than python binary is missing; post these outputs:
```r
list.files("C:\\OSGeo4W64\\bin", "^python\\.exe$", recursive=TRUE)
list.files("C:\\OSGeo4W64\\bin", "^gdal.+\\.py$")
```

Then, try launching again the OSGeo4W installer, choose "Advanced install", click "Next" several times until the "Select package" form, and reinstall "python-core" and "gdal-python"; then relaunch the two aforementioned commands and post again their outputs.

**Comment by ranghetti** [comment]
I noticed just now on another Windows installation that, using the OSGeo4W installer and choosing to install only GDAL (without QGIS and GRASS), python and python-based GDAL routines were not installed. Maybe this is you case? In this case, using the advanced installer as described above (or installing also QGIS in the simplified installer) should solve.

**Comment by jeaggu** [comment]
Hi Luigi,
Thanks for the support, now I managed to make it work following your suggestions!

Now I will start working on the data.

Thanks for putting together the package!
