### ISSUE TITLE
Adding Continuum Removal indices

### ISSUE THREAD

**Issue by ranghetti** [ranghetti/sen2r#168]
Implement the following two indices:
1. Continuum Removal in the red (**CRred**):
    `CRred = R / C`
    where `R = band_4`
    and `C = band_3 + ((lambda_4-lambda_3)/(lambda_6-lambda_3)) * (band_6 - band_3)`
2. Band Depth in the red (**BDred**): 
    `BDred = 1 - CRred`

`lambda_3`, `lambda_4` and `lambda_6` varies basing on the sensor:
- for Sentinel-2A: `lambda_3 = 559.8 nm`, `lambda_4 = 664.6 nm`, `lambda_6 = 740.5 nm`;
- for Sentinel-2B: `lambda_3 = 559.0 nm`, `lambda_4 = 664.9 nm`, `lambda_6 = 739.1 nm`.

To use approximated wavelength values, indices **CRred_0** and **BDred_0** can be used; in this case, `lambda_3 = 560 nm`, `lambda_4 = 665 nm`, `lambda_6 = 740 nm`.

An experimental index **CRred2** was also added basing on the definition provided in [Clark & Roush (1984)](https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/JB089iB07p06329):
`Crred2 = R2 / C2`, 
where `R2` and `C2` were computed as the area subtented respectively by the B3-B6 spectrum (considering both B4 and B5 absorbances) and the continuum:
`R2 = (lambda_4 - lambda_3) * (band_4 + band_3) + (lambda_5 - lambda_4) * (band_5 + band_4) + (lambda_6 - lambda_5) * (band_6 + band_5)`
`C2 = (lambda_6 - lambda_3) * (band_6 + band_3)`

**Comment by ranghetti** [comment]
**CRred_0**, **BDred_0**, **CRred2_0** names were changed to **CRred-0**, **BDred-0**, **CRred2-0** to avoid conflicts (the same for **CRred_2A**, **CRred_2B** etc.)

**Comment by giuliatagliabue** [comment]
Ciao Luigi, 
I have an issue when reinstalling sen2r after this new implementation. When I check the dependencies I get an error related to Wget: 

"cannot open URL 'https://eternallybored.org/misc/wget/releases/wget-1.19.4-win64.zip' download.file"

I also tried to install it manually but it doesn't seem to work .. 
Thanks, Giulia

**Comment by ranghetti** [comment]
Bad luck, the online version of Wget was changed yesterday!
I have changed the functions `install_wget()` and `install_aria2()` to automatically download the latest available version (#171). Reinstalling the package should solve.

**Comment by giuliatagliabue** [comment]
Classic .. ahah
Thanks Luigi! I tried to reinstall but it seems like it is trying to reinstall the same wget version as before and it doesn't work .. :( any other idea?

**Comment by ranghetti** [comment]
...I forgot to merge these last edits in the feature CRred, sorry! Now should work

**Comment by giuliatagliabue** [comment]
No problem :) 
Wget is ok now, but still get error for aria2: 

"Error in unzip(zipfile = aria2_zip, list = TRUE) : 
  zip file 'C:\Users\Giulia\DOCUME~1\R\WIN-LI~1\3.5\sen2r\aria2.zip' cannot be opened"

I launched sen2r() anyway, but the GUI crashes when I try to login to SciHub .. I don't know if the issue is related to aria2 .. it shouldn't right?

**Comment by ranghetti** [comment]
No, these two errors should not be related each other.

I will try to verify on a Windows PC the aria2c problem as soon as possible; in the meantime, you can use Wget without problems.

I cannot reproduce the problem with the SciHub login: which error is returned when the GUI crashes? If you do not solve, you can provide your credential to the package using the function 
```r
write_scihub_login("username","password")
```
(replacing `"username"` and `"password"` properly).

**Comment by ranghetti** [comment]
Can you try now? I have restored the old wget since the new version did not work properly.

**Comment by giuliatagliabue** [comment]
Ciao Luigi, it works now (everything apart from the installation of aria2), but I have another issue. 
When I try to launch any processing, the GUI closes and I get this message: 

```
[2019-04-10 15:09:37] No output products matching the settings were found; 
please specify less restrictive settings.
```
I tried with broad time windows and the max cloud limit is 100% .. could it be something else that I forgot to check? Thanks

**Comment by ranghetti** [comment]
When no products are found, sometimes the reason is related to 1) wrong SciHub credentials, 2) problems to ApiHub. This morning I received the same issue, so I think the problem could be the second. Usually this problem disappear after some hours ; let me know if tomorrow will still be present.

**Comment by giuliatagliabue** [comment]
Ciao Luigi, I tried just now and it still doesn't work, I checked the credentials and they are correct

**Comment by ranghetti** [comment]
Can you post the JSON file with parameters of the chain that produces that message?

**Comment by giuliatagliabue** [comment]
Here it is. Thank you!

[Aranjuez_test.zip](https://github.com/ranghetti/sen2r/files/3068945/Aranjuez_test.zip)

**Comment by ranghetti** [comment]
I verified that the function to search for SAFE archives does not return any product on Windows. The aria2 version which is now downloaded is the same which was downloaded before last edits, so it is difficult to understand the reason of this behaviour.

I already planned to edit the functions to search and download SAFE in order not to use python; probably I will do it as soon as possible so to solve also this bug. In the meantime, to make test on the new indices you can manually download the required SAFE, unzip them and place them in the directory Level_2A, then re-launch the processing in offline mode.

Sorry for this issue...

**Comment by ranghetti** [comment]
I should have fixed it with #174 ; can yu test if the problem is solved for you?

**Comment by giuliatagliabue** [comment]
Ciao Luigi! Just tested, seems to work perfect now! Thanks a lot :)
I will check the CRred index output and let you know how it works.

**Comment by ranghetti** [comment]
Indices were added to master branch.
