### ISSUE TITLE
s2_mask - Error

### ISSUE THREAD

**Issue by FrancescoReyes** [ranghetti/sen2r#172]
Thanks in advance for the attention!

it is maybe not fully clear to me how the argument "maskfiles" should be specified into the s2_mask function.
When specifying as "maskfiles" the whole L2A image (on which basis the translated image was generated), a SCL file path of the same L2A product, or a shape file on which I wish to verify the presence of clouds:

`s2_mask(paste0(translated_folder, "\\", immagine_translated), maskfiles = paste0(L2A_images, "\\", immagine_L2A) , mask_type = "cloud_and_shadow")`

`s2_mask(paste0(translated_folder, "\\", immagine_translated), maskfiles = SCL_file, mask_type = "cloud_and_shadow")`

`s2_mask(paste0(translated_folder, "\\", immagine_translated), maskfiles = shape_azienda, mask_type = "cloud_and_shadow")`

I always get the same error:
> Error in if (format == "VRT") { : missing value where TRUE/FALSE needed

What can be the problem?
maybe in some interaction with the GDAL library?
or not correctly specify arguments?

Maybe a example of usage would be useful! :-)

**Comment by ranghetti** [comment]
Hi Francesco,
`maskfiles` is a vector of filenames of SCL rasters, so your first two examples are correct, while the third one cannot work.

I think this error could be related to your particular Python installation, linke in #152.
`s2_mask()` still makes use of GDAL in some parts of the code.
I plan to remove all GDAL python commands in future, but not as quickly. In the meantime, you can try using the docker version of the package.
