### ISSUE TITLE
Installation problems (Pyhton??)

### ISSUE THREAD

**Issue by rcabas** [ranghetti/sen2r#173]
Hi,
I have several problems with the installation of sen2r... indeed, I suppose the problems is only the python because, all the other things apparently go fine.
I am installing the sen2r in windows server 2016 (64bits)
I install OSGEO4W, with and without QGIS... now I have install the complete version.
I also installed python 2.7.14 and python 3.7.0
I read several issuses and try to solve the problem, but still no working.
I execute the check_sen2r_deps() and all configuration are OK except aria2c, I have not installed. Because allways that I intend to install, whit "check_sen2r_deps()", I have problems and show me this mesage:

```
Listening on http://127.0.0.1:6011
Warning: Error in system: 'C:\Program' not found
  79: system
  78: install_aria2
  75: load_binpaths
  74: import_s2download
  73: observeEventHandler
   2: runApp
   1: check_sen2r_deps
```

and i have to install manually like you posted in the issue  147
As I see, please find below the output of these commands:

```
> sen2r:::init_python()
Error in python_config(python_version, required_module, python_version,  : 
  Error 29 occurred running C:\OSGEO4~1\bin\python.exe 
In addition: Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": The filename, directory name, or volume label syntax is incorrect
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": The filename, directory name, or volume label syntax is incorrect
3: In system2(command = python, args = paste0("\"", config_script,  :
  running command '"C:\OSGEO4~1\bin\python.exe" "C:/Program Files/R/R-3.5.3/library/reticulate/config/config.py"' had status 29

> Sys.getenv("PATH")
[1] "C:\\OSGEO4~1\\apps\\Python27;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\OSGeo4W64\\bin;C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps;"

> Sys.getenv("PYTHONHOME")
[1] "C:\\OSGEO4~1\\apps\\Python27"

> Sys.getenv("PYTHONPATH")
[1] "C:\\OSGEO4~1\\apps\\Python27\\Lib"

> sen2r:::load_binpaths()
$gdalbuildvrt
[1] "C:\\OSGEO4~1\\bin\\GDALBU~1.EXE"

$gdal_translate
[1] "C:\\OSGEO4~1\\bin\\GDAL_T~1.EXE"

$gdalwarp
[1] "C:\\OSGEO4~1\\bin\\gdalwarp.exe"

$python
[1] "C:\\OSGEO4~1\\bin\\python.exe"

$gdal_calc
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_C~1.PY"

$gdal_polygonize
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_P~2.PY"

$gdal_fillnodata
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_F~1.PY"

$gdaldem
[1] "C:\\OSGEO4~1\\bin\\gdaldem.exe"

$gdalinfo
[1] "C:\\OSGEO4~1\\bin\\gdalinfo.exe"

$ogrinfo
[1] "C:\\OSGEO4~1\\bin\\ogrinfo.exe"

$wget
[1] "C:\\Program Files\\R\\R-3.5.3\\library\\sen2r\\wget.exe"

$sen2cor
[1] "C:\\Program Files\\R\\R-35~1.3\\library\\sen2r\\sen2cor\\SEN2CO~1.05-\\L2A_PR~1.BAT"

attr(,"path")
[1] "C:/Program Files/R/R-3.5.3/library/sen2r/extdata/paths.json"

> sen2r:::check_gdal(force=TRUE)
 Searching for a valid GDAL installation...
 GDAL version in use: 2.4.1

> list.files("C:\\OSGeo4W64\\bin", "^gdal.+\\.exe$")
 [1] "gdal_contour.exe"     "gdal_grid.exe"        "gdal_rasterize.exe"  
 [4] "gdal_translate.exe"   "gdaladdo.exe"         "gdalbuildvrt.exe"    
 [7] "gdaldem.exe"          "gdalenhance.exe"      "gdalinfo.exe"        
[10] "gdallocationinfo.exe" "gdalmanage.exe"       "gdalserver.exe"      
[13] "gdalsrsinfo.exe"      "gdaltindex.exe"       "gdaltransform.exe"   
[16] "gdalwarp.exe"

> shell("C:\\OSGeo4W64\\bin\\gdalinfo.exe --version")
GDAL 2.4.1, released 2019/03/15
```

Thanks a lot and I hope to reach a solution!

**Comment by ranghetti** [comment]
Thank you to have already posted some outputs useful tu understand the situation.
Can you post the output of this?
```r
list.files("C:\\OSGeo4W64\\bin", "^gdal.+\\.py$")
```
If it would be empty, download and open the [OSGeo4W installer](https://www.qgis.org/it/site/forusers/download.html), choose "Advanced install", click "Next" until you will reach the sheet with the package selection, and install the package "python-gdal".

**Comment by rcabas** [comment]
Thanks!
The output:
> list.files("C:\\OSGeo4W64\\bin", "^gdal.+\\.py$")
 [1] "gdal_auth.py"       "gdal_calc.py"       "gdal_edit.py"      
 [4] "gdal_fillnodata.py" "gdal_merge.py"      "gdal_pansharpen.py"
 [7] "gdal_polygonize.py" "gdal_proximity.py"  "gdal_retile.py"    
[10] "gdal_sieve.py"      "gdal2tiles.py"      "gdal2xyz.py"       
[13] "gdalchksum.py"      "gdalcompare.py"     "gdalident.py"      
[16] "gdalimport.py"      "gdalmove.py"       
>

**Comment by rcabas** [comment]
I think the problems is concerning to python configuration.
When I execute "sen2r:::init_python()", the output is:
> sen2r:::init_python()
Error in python_config(python_version, required_module, python_version,  : 
  Error 29 occurred running C:\OSGEO4~1\bin\python.exe 
In addition: Warning message:
In system2(command = python, args = paste0("\"", config_script,  :
  running command '"C:\OSGEO4~1\bin\python.exe" "C:/Program Files/R/R-3.5.3/library/reticulate/config/config.py"' had status 29

I have allready install sen2r in Windows 7 and Windows 10 with minimal problemas but I solved it (mainly the automatically installation of aria2, that I had to installed manually.

**Comment by ranghetti** [comment]
Can you try to update all R packages (`update.packages(ask=FALSE)`) and the OSGeo4W environment (re-launching the OSGeo4W installer in Advanced mode)?

**Comment by rcabas** [comment]
ok...
with this: "and the OSGeo4W environment (re-launching the OSGeo4W installer in Advanced mode)" you mean "reinstall" all the packages?

**Comment by rcabas** [comment]
I updates the package as you mentioned, (not OSGEO4W), and relunch R, and when open the library sen2r, the output:
> library(sen2r)
Error: package or namespace load failed for ‘sen2r’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): there is no package called ‘reticulate’

then I forced to install the sen2r again and is ok (I have to install the dependencies again)

**Comment by ranghetti** [comment]
Well!

**Comment by rcabas** [comment]
no... the problem is still alive!! jejeje
I have only to reinstall the sen2r but I have no solve the problem.
Now I am reinstalling the OSGEO4W... totally
But the "sen2r:::init_python()" dont work

**Comment by ranghetti** [comment]
Ok, to update OSGeo4W simply open the installer in the Advanced mode, and click "next" without doing anything else: the effect of that will be the update (reinstallation) of all the installed packages. There is no need to uninstall and reinstall.

**Comment by rcabas** [comment]
no, dont work....
I repeated all the functions executed before... and all have the same output
The  difference between this installation with W7 and W10, is the init_python() function

**Comment by ranghetti** [comment]
Unfortunately I do not know how to solve this proble.
You can try using sen2r in a docker container (http://sen2r.ranghetti.info/articles/docker)

**Comment by rcabas** [comment]
ok, thanks for your time... maybe is something related to windows server 2016... that has bloqued some services that affect python...
I tried to intall sen2r in a docker, but as I understood, this version is only for the GUI... can it work with R programing task?

**Comment by ranghetti** [comment]
Yes, the dockerised version provide you an Rstudio server interface, form which you can launch a GUI as well as using the common R syntax.

**Comment by rcabas** [comment]
ok, thanks... in that case, it can be better to install sen2r in Ubuntu, isnt it? it will be faster

**Comment by ranghetti** [comment]
Yes (http://sen2r.ranghetti.info/articles/installation#on-linux-systems)

**Comment by rcabas** [comment]
Thanks! Luigi... I will come back if have problems with this installation!
Great work!
