### ISSUE TITLE
BOA band names gone

### ISSUE THREAD

**Issue by yesdavid** [ranghetti/sen2r#176]
Dear Luigi,
after running `s2_translate()` the band names of the BOA are gone and are simply labeled 1-11.
`sen2r::s2_translate(infile = unzipped_l2a[p0], 
                      outdir = dir_translated_l2a, 
                      format = "GTiff",
                      prod_type = c("BOA", "TCI", "SCL"),
                      subdirs = TRUE)`
How do I know which band number is which band?
Best,
David

**Comment by ranghetti** [comment]
Dear David,
unfortunately, for what I know, it is not possible to save band names within GeoTIFF files. I plan to add this information in the ENVI metafiles (#166), but for now that is still missing. 
Nevertheless, BOA and TOA files produced by sen2r always have the same number of bands: TOA is composed by 12 bands (Sentinel-2 bands 1 to 12 with a resolution < 20m; bands 1 to 7, 8a and 9 to 11 with a resolution >= 20m); BOA is composed by 11 bands (the same bands without band 10). Knowing that, you can manually associate the proper wavelength (https://sentinel.esa.int/web/sentinel/user-guides/sentinel-2-msi/resolutions/radiometric) to each band.
I will add this information explicitly in the GUI; in the meantime, you can find band information in the sheet "RGB images selection", trying to define a new RGB image.
Hoping this can help,

**Comment by yesdavid** [comment]
Thank you for your quick response! I will check out your suggested sources!
Did I understand it correctly that there is no band 8 then? 

> bands 1 to 7, 8a and 9 to 11

And is the first band after the translation "coastal aerosol", or "blue"? Because for my translated BOA-file I figured the names to be:
1 = "B02", 2 = "B03", 3 = "B04", 4 = "B05", 5 = "B06", 6 = "B07", **7 = "B08"**, 8 = "B8A", 9 = "B09", 10 = "B11", 11 = "B12")

Thanks a lot!

**Comment by ranghetti** [comment]
First band is "coastal aerosol" (band 1, 443 nm). There is no band 8 in case of output resolution >= 20m; otherwise there is no band 8A:

This is the situation for BOA:
- resolution < 20m: bands 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12
- resolution >= 20m: bands 1, 2, 3, 4, 5, 6, 7, 8a, 9, 11, 12

TOA:
- resolution < 20m: bands 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
- resolution >= 20m: bands 1, 2, 3, 4, 5, 6, 7, 8a, 9, 10, 11, 12
