### ISSUE TITLE
Assign a new palette (.cpt) to a cliped raster images

### ISSUE THREAD

**Issue by rcabas** [ranghetti/sen2r#183]
Hi,
I would like to add a new palette color (CPT) to a final image that I have process, as follow:
- I have download a SAFE product
- I have performed VRT file with s2translate()
- I have performed a NDVI Index with s2_calcindices()
- I have cut the last images with a SHP file of the desired area with gdal_wrap()

The final product I have is a GTiff archiveof the raw data in greys scale and I would like to assign different palettes to show the final process.
I have use raster2rgb() with partialy success... I have use: SCL, NDVI, generic_ndsi and Zscore and the process went "fine" (in SCL apears all purple and is an agriculture area).
In the explanation of this functions says:
"palette | Path of the palette file to be used (cpt or txt), or character value of a builtin palette ("SCL", "NDVI", the default "generic_ndsi" or "generic_ndsi_2")."

But I download several CPT palettes and use them in the functions and always show me the following:
"Error in if (!names(palette) %in% c("SCL") & (minval != -1 | maxval !=  : 
  argumento tiene longitud cero"

This is the functin I have used:

"raster2rgb(shpuserNDVI, out_file = jpguserNDVI, palette = palette, minval = -10000, maxval = 10000)"

where "palette" is the entire path of the CPT file, including itself, I have excute the following function to test it:

> file.exists(palette)
[1] TRUE

Can you tell how can I assign a different palette to a final image? The final product I need is a JPG or PNG archive with a cutted (shp) area of an INDEX image...

Thanks!
PD: I am using Windows platform because the gdal_wrap() function doesent work in Linux... but this can be another issue :-)

**Comment by ranghetti** [comment]
Hi,
`raster2rgb()` is an internal function, so it is not thought to be used by package users: so exceptions can occur. I will improve the documentation and manage the exceptions in future.
In your case, I think you can solve by naming the path `palette`. E.g.:
```r
palette <- "/path/of/your/palette.cpt"
names(palette) <- "mypalette"
```
If it does not solve, please post the `raster2rgb()` command you are launching, together with the content of the arguments (1. `palette`, 2. the class of `shpuserNDVI`).

**Comment by ranghetti** [comment]
I'm closing this issue supposing it was solved, reopen it if not.
