### ISSUE TITLE
index addition - NDWI

### ISSUE THREAD

**Issue by CTO22** [ranghetti/sen2r#184]
Would it be possible to add NDWI?  Its described on sentinel-hub.com but not present on the RS index list on the github.io

https://www.sentinel-hub.com/eoproducts/ndwi-normalized-difference-water-index

**Comment by ranghetti** [comment]
I will add it in a future release, together with NDWI2 ((B03-B08)/(B03+B08)); in the meantime, you can use index NDII for it, which has the same formula ((B08-B11)/(B08+B11)).

**Comment by CTO22** [comment]
Thank you so much,
I did not recognize that the formulas were the same for those.

Best regards,
Cory

________________________________

**Comment by ranghetti** [comment]
NDWI index was added to master branch.
