### ISSUE TITLE
SCL classes

### ISSUE THREAD

**Issue by yesdavid** [ranghetti/sen2r#188]
Dear Luigi,  

can you please tell me which classes of the SCL file are being used when masking with `mask_type = "land"`? The classes seem to be different from case to case. My guess would be that classes 4 and 5 are vegetation and bare soil, but I want to be sure.  
I need to know this, because I cannot work with the BOA-file and have to create a mask from your SCL-file on my own.

Best,
David

**Comment by ranghetti** [comment]
Dear David,
I confirm that `mask_type = "land"` corresponds to mask classes 4 and 5. You can find which classes are masked using each value of the argument `mask_type` in the help of the function `s2_mask()`. Alternatively, an help window with a similar documentation can be opened from the GUI, in the sheet "Processing options", right to the selector "Apply mask to:".

> The classes seem to be different from case to case.

Which differences are you observing? It can occur that the classification performed in the SCL would not be correct; so, if you want to perform a check, you can compare your masked output with the SCL layer. If you would observe that pixels not classified as "land" or "bare soil" are not being masked (or vice versa), please report it with a reproducible example.
