### ISSUE TITLE
New SAFE images structure and new version of sen2cor()

### ISSUE THREAD

**Issue by rcabas** [ranghetti/sen2r#189]
Dear Luigi,
I don not know if is temporaly, or definitely, but yesterday and today I downloaded SAFE product and in the "IMG_DATA" apears directly the JP2 files with the best resolutions... it is not the three directories like "10m", "20m" and "60m".
In the other case, I have downloaded the SAFE, and download the L1C level and when I excecuted the sen2cor (v2.5.5), it was not work properly....
I see there is a new version of sen2cor (v 2.8), but i do not know if this version solve this problem or not... in any case, I do not know how to upgrade sen2cor or if it is necessary for sen2r.
Thanks a lot!

**Comment by ranghetti** [comment]
In order to check it, can you post the name of both the SAFE products you dowloaded?

The version of Sen2Cor installed within sen2r is locked. In the past days I tried to update Sen2Cor to version 2.8.0, but errors in executing it occurred. I will make further tests during next days.

**Comment by rcabas** [comment]
The SAFE product in L1C is:
"S2A_MSIL1C_20190626T140101_N0207_R067_T21JTH_20190626T154048.SAFE"
Now I try to forcce to download the same SAFE but in L2A and it is downloaded with three directories structure...
But In some cases L2A it is not available and is faster for me to process L1C locally....

**Comment by rcabas** [comment]
Other question, in the s2_list() function, in the "level" paramter, when we put "auto", this means that first search L2A and in case it is not available, list L1C?

**Comment by ranghetti** [comment]
So the product without directories "10m", "20m" and "60m" is L1C? That is normal, this is the structure used in L2A format.
While I'm checking if Sen2Cor run correctly on that product, can you post the output of the error you are receiving?

> Other question, in the s2_list() function, in the "level" paramter, when we put "auto", this means that first search L2A and in case it is not available, list L1C?

Yes.

**Comment by rcabas** [comment]
Hi Luigi, let me see one think, I am usind virtual machine to execute LINUX, and the problem can be that this VM has not enough space....
Let me check and come back to you.

**Comment by rcabas** [comment]
Yes!, The problem was the space of the hard disc!
Sorry for this inconvenince...
Thanks!
