### ISSUE TITLE
cannot install from github

### ISSUE THREAD

**Issue by jillbolland** [ranghetti/sen2r#190]
I am running R3.5.2  and trying to install the sen2r package.  I have downloaded and installed Remotes and devtools.   I have also set R to use my proxy using Sys.setenv   however I am still not able to install I get an error "Error: Failed to install 'sen2r' from GitHub:
  Failed to connect to api.github.com port 443: Connection refused"    I have also received the error " Unsupported proxy  'https://AONNET/xxxxx@xxxx:9001/', libcurl is built without the HTTPS-proxy support."

I understand that it is probably an with my company's setup but our IT dept is not able to fix my issue.  Is it possible to download the files and install from my pc

**Comment by ranghetti** [comment]
Unfortunately I have no ideas about the reason of this problem. You can try to install the package using Git:
1. clone the sen2r repository on your local machine (see e.g. https://happygitwithr.com, chapters [13](https://happygitwithr.com/rstudio-see-git.html) and [12.3](https://happygitwithr.com/rstudio-git-github.html#clone-the-new-github-repository-to-your-computer-via-rstudio))
2. build the package in RStudio (Ctrl+Shift+B)
