### ISSUE TITLE
Add alternative atm. corr. algorithms and band downscaling

### ISSUE THREAD

**Issue by dpoursanidis** [ranghetti/sen2r#193]
- [ ] Option to use ACOLITE atm cor for water applications  (https://github.com/acolite/acolite).

- [ ] Option for band dowscaling using a unique approach  -(http://nicolas.brodu.net/recherche/superres/). I have use it in  this publication  (https://www.sciencedirect.com/science/article/pii/S0303243418311656).

- [ ] Option for C2RCC atm cor for water applications  (https://github.com/bcdev/s3tbx-c2rcc).

**Comment by ranghetti** [comment]
Closing due to the end of the package development (this improvement will not be implemented, sorry).
