### ISSUE TITLE
Single condition on `if` on array

### ISSUE THREAD

**Issue by lbusett** [ranghetti/sen2r#195]
This line:

https://github.com/ranghetti/sen2r/blob/96114e737e3e088831c8a19c2cdaa2c548095b7a/R/sen2r.R#L1584

gives a warning:

```r
Warning message:
In if (sel_s2_dt$level == "1C") { :
  the condition has length > 1 and only the first element will be used
```

should probably be changed to: 

```r
if (unique(sel_s2_dt$level)=="1C") {path_l1c} else {path_l2a}, sel_s2_dt[,name]),
```

(this because it's not nice to throw a warning if not needed, and also because I think CRAN started checking those conditions)

**Comment by ranghetti** [comment]
Sorry, this was fixed but only in devel:
```r
sapply(sel_s2_dt$level, switch, `1C`=path_l1c, `2A`=path_l2a),
```
