### ISSUE TITLE
Force index computation and RGBs to use TOAs if levels = l1c

### ISSUE THREAD

**Issue by lbusett** [ranghetti/sen2r#198]
Arguments "index_source" and the reflectances used to compute RGBs should be forced to "TOA" and "RGBxxxT" if s2_levels == l1c | step_atmcorr == "no". Otherwise, computation may fail due to lacking input data.

**Comment by ranghetti** [comment]
Now step_atmcorr cannot be set to "no", so that index_source /RGBxxxT can not conflict with step_atmcorr.
