### ISSUE TITLE
On devel, spectral indices are not generated if masking is needed

### ISSUE THREAD

**Issue by lbusett** [ranghetti/sen2r#200]
``` r
sen2r(
            gui = FALSE,
            online = FALSE,
            s2_levels = "l2a",
            step_atmcorr = "l2a",
            # list_prods = "BOA",
            extent = file.path(example_dir, "scalve.kml"),
            extent_name = "Scalve",
            extent_as_mask = TRUE,
            timewindow = as.Date("2017-07-03"),
            list_indices = c("NDVI","MSAVI2"),
            mask_type = "cloud_medium_proba",
            path_out = out_dir,
            path_l1c = file.path(safe_dir, "L1C"),
            path_l2a = file.path(safe_dir, "L2A"),
            path_indices = out_dir,
            parallel = FALSE, 
            thumbnails = FALSE, 
        )
```

[2019-08-27 10:22:07] Starting sen2r execution.
[2019-08-27 10:22:08] Computing output names...
[2019-08-27 10:22:08] Updating output names...
[2019-08-27 10:22:09] Starting to translate SAFE products in custom format.
Using UTM zone 32.
Input file size is 5490, 5490
0...10...20...30...40...50...60...70...80...90...100 - done.
2 output files were correctly created.
Using UTM zone 32.
Input file size is 5490, 5490
0...10...20...30...40...50...60...70...80...90...100 - done.
2 output files were correctly created.
[2019-08-27 10:22:10] Starting to merge tiles by orbit.
Using projection "+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs".
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 5490, 10491
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 10980, 20982
[2019-08-27 10:22:10] Starting to edit geometry (clip, reproject, rescale).
[2019-08-27 10:22:12] Starting to apply cloud masks.
Processing chunk 1 of 8
Processing chunk 2 of 8
Processing chunk 3 of 8
Processing chunk 4 of 8
Processing chunk 5 of 8
Processing chunk 6 of 8
Processing chunk 7 of 8
Processing chunk 8 of 8
[2019-08-27 10:22:28] Execution of sen2r session terminated.
Warning message:
Some files were not created:
"/tmp/RtmpNXOAz3/out_test3/NDVI/S2A2A_20170703_022_Scalve_NDVI_10.tif"
"/tmp/RtmpNXOAz3/out_test3/MSAVI2/S2A2A_20170703_022_Scalve_MSAVI2_10.tif"

**Comment by ranghetti** [comment]
Fixed with 82e93ae22e71e93e83c67985725004b0882c72ca.
