### ISSUE TITLE
How to associate sen2r band names with ESA naming convention?

### ISSUE THREAD

**Issue by philiporlando** [ranghetti/sen2r#212]
Really great package, thanks for making this available! This is helping me automate my Sentinel-2 data compilation pipeline, but I could use some clarification when renaming the `sen2r()` bands to match the naming convention used by the ESA. 

Calling `sen2r()` with the following parameters produces a raster stack with 11 bands. 
```
sen2r(gui = FALSE,
      timewindow = c(as.Date("2019-08-20")-14, as.Date("2019-08-20)+14),
      extent = "./data/study_extent.kml",
      extent_name = "myExtent",
      list_prods = c("BOA"),
      max_cloud_safe = 1,
      res_s2 = "10m",
      extent_as_mask = T,
      step_atmcorr = "auto",
      overwrite = T,
      overwrite_safe = T,
      path_l1c = "./data/sentinel-2", path_l2a = "./data/sentinel-2",
      path_out = "./data/sentinel-2/sen2r-out")
```
What is the ESA equivalent of the following band names produced by `sen2r()`?

`"S2A2A_20190812_027_myExtent_BOA_10.1"`
`"S2A2A_20190812_027_myExtent_BOA_10.2"`
`"S2A2A_20190812_027_myExtent_BOA_10.3"`
`"S2A2A_20190812_027_myExtent_BOA_10.4"`
`"S2A2A_20190812_027_myExtent_BOA_10.5"`
`"S2A2A_20190812_027_myExtent_BOA_10.6"`
`"S2A2A_20190812_027_myExtent_BOA_10.7"`
`"S2A2A_20190812_027_myExtent_BOA_10.8"`
`"S2A2A_20190812_027_myExtent_BOA_10.9"`
`"S2A2A_20190812_027_myExtent_BOA_10.10"`
`"S2A2A_20190812_027_myExtent_BOA_10.11"`

For example, how do I know which one of these is the `8A` band? In addition, why does `sen2r()` only produce 11 bands instead of the 13 listed [here](https://earth.esa.int/web/sentinel/user-guides/sentinel-2-msi/resolutions/spatial)? 

Thanks for creating such an awesome R wrapper!

**Comment by ranghetti** [comment]
Thank you for your comments. You can fund the answers to your questions here: #208.

**Comment by philiporlando** [comment]
Thank you for the reference. Apologies for creating a duplicate!
