### ISSUE TITLE
The provided credentials are not valid, so the will not be saved.

### ISSUE THREAD

**Issue by RobertSellers** [ranghetti/sen2r#225]
Hello - 

I'm new to this app and Sci Hub, so perhaps I am missing something, but I am successfully logged into https://scihub.copernicus.eu/dhus/#/home, however these permissions don't seem to be recognized with both write_scihub_login(user, pass) & write_scihub_login(user, pass).  Any advice?

![image](https://user-images.githubusercontent.com/15310904/66777367-dbb3a780-ee96-11e9-8c21-46ce04da257e.png)

**Comment by ranghetti** [comment]
Hello,
this could mean that you did not provide the correct values for variables `user` and `pass`, or that you are not able to connect the the SciHub server. 

1. Have you checked that they are exatly the same you are using to connect at https://scihub.copernicus.eu/dhus/#/home?
2. Check that your internet connection is ok:
    ```r
    check_scihub_connection()
    ```

**Comment by ranghetti** [comment]
Hello,
have you solved the problem? If so, can you please specify which of the two situation did you encounter?
Thank you
