### ISSUE TITLE
Downloaded ZIP is not fully extracted, causing files cannot be found

### ISSUE THREAD

**Issue by jitsr** [ranghetti/sen2r#230]
Hi,

I've got some trubble with processing my downloaded images. In some cases the downloaded ZIP file is not fully extracted. This causes the error:

> Error in { : 
>   task 1 failed - "task 1 failed - "cannot open file 'C:/Users/jitsr/Documents/sen2Rdownload/6/level1C_SAFE/S2B_MSIL1C_20190329T104029_N0207_R008_T31UGU_20190329T160204.SAFE/GRANULE/L1C_T31UGU_A010759_20190329T104024/QI_DATA/T31UGU_20190329T104029_PVI.jp2': No such file or directory""

The download is completely finished and when I extract the data itself, it works. But to automate the process this is not a very nice way to work. 
Is there an explaination for this behaviour? Am I doing something wrong?

Operating system and R-version:
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)
```
```
```
> sen2r::load_binpaths()
$gdalinfo
[1] "C:\\OSGEO4~1\\bin\\gdalinfo.exe"

$ogrinfo
[1] "C:\\OSGEO4~1\\bin\\ogrinfo.exe"

$gdal_translate
[1] "C:\\OSGEO4~1\\bin\\GDAL_T~1.EXE"

$gdalwarp
[1] "C:\\OSGEO4~1\\bin\\gdalwarp.exe"

$gdalbuildvrt
[1] "C:\\OSGEO4~1\\bin\\GDALBU~1.EXE"

$gdaldem
[1] "C:\\OSGEO4~1\\bin\\gdaldem.exe"

$python
[1] "C:\\OSGEO4~1\\bin\\python.exe"

$gdal_calc
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_C~1.PY"

$gdal_polygonize
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_P~2.PY"

$gdal_fillnodata
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_F~1.PY"

$sen2cor
[1] "C:\\Users\\jitsr\\DOCUME~1\\STAGEL~1\\Rproject\\RPROJE~1\\SEN2CO~1\\SEN2CO~1.05-\\L2A_PR~1.BAT"

$aria2c
[1] "C:\\Users\\jitsr\\Documents\\aria2\\aria2c.exe"

attr(,"path")
[1] "~/.sen2r/paths.json"
```

sen2r:::init_python()
GDAL version in use: 2.4.1
$py
Module(__builtin__)

$os
Module(os)

$sys
Module(sys)

$subprocess
Module(subprocess)

$re
Module(re)

$numpy
Module(numpy)

$urllib
Module(urllib)

$zipfile
Module(zipfile)

$gdal
Module(gdal)

$osr
Module(osr)
```

JSON parameter file:

```
{
  "preprocess": [true],
  "s2_levels": ["l1c", "l2a"],
  "sel_sensor": ["s2a", "s2b"],
  "online": [true],
  "order_lta": [true],
  "downloader": ["builtin"],
  "overwrite_safe": [true],
  "rm_safe": ["no"],
  "max_cloud_safe": [5],
  "step_atmcorr": ["scihub"],
  "timewindow": ["2019-03-01", "2019-03-31"],
  "timeperiod": ["full"],
  "extent": ["{\n  \"type\": \"FeatureCollection\",\n  \"features\": [\n    {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"X_leaflet_id\": 2115,\n        \"feature_type\": \"rectangle\"\n      },\n      \"geometry\": {\n        \"type\": \"Polygon\",\n        \"coordinates\": [\n          [\n            [6.154189, 52.980638],\n            [6.154189, 52.990921],\n            [6.17084, 52.990921],\n            [6.17084, 52.980638],\n            [6.154189, 52.980638]\n          ]\n        ]\n      }\n    },\n    {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"X_leaflet_id\": 2141,\n        \"feature_type\": \"rectangle\"\n      },\n      \"geometry\": {\n        \"type\": \"Polygon\",\n        \"coordinates\": [\n          [\n            [6.153245, 52.979088],\n            [6.153245, 52.990611],\n            [6.168008, 52.990611],\n            [6.168008, 52.979088],\n            [6.153245, 52.979088]\n          ]\n        ]\n      }\n    }\n  ]\n}"],
  "s2tiles_selected": ["31UGU"],
  "s2orbits_selected": [null],
  "list_prods": ["BOA"],
  "list_indices": ["Chlred-edge", "CRred", "CSI", "EVI", "GNDVI", "MCARI", "MCARI2", "MSAVI2", "NBR", "NDRE", "NDVI", "OSAVI", "SAVI"],
  "list_rgb": ["RGB432B", "RGB843B", "RGBb84B"],
  "rgb_ranges": [
    [0, 2500],
    [
      [0, 7500],
      [0, 2500],
      [0, 2500]
    ],
    [
      [0, 7500],
      [0, 7500],
      [0, 2500]
    ]
  ],
  "index_source": ["BOA"],
  "mask_type": [null],
  "max_mask": [80],
  "mask_smooth": [0],
  "mask_buffer": [0],
  "clip_on_extent": [true],
  "extent_as_mask": [false],
  "extent_name": ["sen2r"],
  "reference_path": [null],
  "res": [null],
  "res_s2": ["10m"],
  "unit": ["Meter"],
  "proj": [null],
  "resampling": ["near"],
  "resampling_scl": ["near"],
  "outformat": ["GTiff"],
  "rgb_outformat": ["GTiff"],
  "index_datatype": ["Int16"],
  "compression": ["LZW"],
  "rgb_compression": ["LZW"],
  "overwrite": [false],
  "path_l1c": ["C:/Users/jitsr/Documents/sen2Rdownload/6/Nieuwenhuis_K01528-0020_nieuwenhuis_edwin-0020_bijstra_lang/level1C_SAFE"],
  "path_l2a": ["C:/Users/jitsr/Documents/sen2Rdownload/6/Nieuwenhuis_K01528-0020_nieuwenhuis_edwin-0020_bijstra_lang/level2A_SAFE"],
  "path_tiles": [null],
  "path_merged": [null],
  "path_out": ["C:/Users/jitsr/Documents/sen2Rdownload/6/Nieuwenhuis_K01528-0020_nieuwenhuis_edwin-0020_bijstra_lang/allFieldRasters"],
  "path_rgb": ["C:/Users/jitsr/Documents/StageLocal/sen3rTestFolder/RGB"],
  "path_indices": ["C:/Users/jitsr/Documents/StageLocal/sen3rTestFolder/spectralIndices"],
  "path_subdirs": [true],
  "thumbnails": [true],
  "log": [null],
  "parallel": [true],
  "processing_order": ["by_groups"],
  "pkg_version": ["1.2.0"]
}

```

**Comment by ranghetti** [comment]
Hi,
it seems to be an issue related to the unzip method which is being used (see e.g. [this](https://stackoverflow.com/questions/14146341/getting-warning-using-setas-to-specify-colclasses-in-r)).

First, try the followings:
1. use a different unzip application in R:
    ```r
    options(unzip = "c:/Program Files/Git/usr/bin/unzip.exe")
    ```
    (replacing `"c:/Program Files/Git/usr/bin/unzip.exe"` with the path of a commandline unzip application you have installed on your pc and which you checked is correctly working to extract the SAFE);
2. reduce the path length storing SAFE archives in a shorter path (alternatively, you can [mount a directory as drive](https://superuser.com/questions/109407/how-do-you-mount-a-directory-as-a-drive-in-windows-7) and use the path of the mounted drive in the json).

**Comment by jitsr** [comment]
Hi, 
Thank you. The first method (different unzipping application in R) did not give any difference. The second method shows a better result. However, it seems like the sen2cor operation takes longer now. I thought the problem might be that the sen2cor installation is now placed at a different path than the created files. Or should this not be a problem?

Another question, if the already corrected 1 C products (now called 2A products) are in a different folder saved, but for another project the same tile is needed. Can this program find the already corrected files? Or does it start all over again if it is not saved in the folder?

**Comment by ranghetti** [comment]
> However, it seems like the sen2cor operation takes longer now. I thought the problem might be that the sen2cor installation is now placed at a different path than the created files. Or should this not be a problem?

I think you could observe a lower speed in case files are placed in a storage whose read/write speed is lower (i.e. an external USB unit, or a network unit, or a HDD storage on a PC using a SSD main disk). If you simply mounted a directory as drive, I doubt this could happen. To be sure of that, you can try storing SAFE files in a directory with a shorter path instead than mounting the SAFE "long" path on a drive.

> Another question, if the already corrected 1 C products (now called 2A products) are in a different folder saved, but for another project the same tile is needed. Can this program find the already corrected files? Or does it start all over again if it is not saved in the folder?

`sen2r()` has two different arguments for L1C and L2A archives (`path_l1c` and `path_l2a`), which are used both as input directories (to read existing files) than output (to save downloaded/corrected archives). So, pointing `path_l2a` to the new directory in the second project would allow reading existing created archives.

**Comment by jitsr** [comment]
Great! Thank you! The speed is something to investigate for me because everything is performed on the same SSD main disk. I can play with different paths and find out if that will make any difference. It is a pity that the paths cannot be that long, but using a directory as drive helps! At least everything is working fine now. Thank you very much for your help!

> sen2r() has two different arguments for L1C and L2A archives (path_l1c and path_l2a), which are used both as input directories (to read existing files) than output (to save downloaded/corrected archives). So, pointing path_l2a to the new directory in the second project would allow reading existing created archives.

This is also a great tip!

**Comment by ranghetti** [comment]
You are welcome! The problem of paths length is that, on Windows, paths can not be longer than 255 characters; and the structure of SAFE archives, including a long main name and long internal filenames, does not help.
