### ISSUE TITLE
Define sen2cor path without GUI

### ISSUE THREAD

**Issue by riazarbi** [ranghetti/sen2r#235]
Hello,

Q: How do I tell `sen2r` where the `sen2cor` installation is without the GUI? 

----------------------------------------------------------------------
# Context

I am trying to incorporate a `sen2r` workflow into an airflow job. The workflow involves launching a new docker container, cloning in an Rscript, and executing it. 

This means I cannot have any user intervention in running the script, and that the environment is always clean - there is no opportunity for `sen2r` to persist config files across jobs.

I am able to load all the binpaths except `sen2cor`. 

`sen2cor` is installed - it was installed by the `root` user during the Docker build. 

The container runs as an unprivileged user `jovyan` when executing R scripts for security purposes.

The `jovyan` user, when executing R scripts, has no way of finding the `sen2cor` installation. I can tell user `jovyan` where the `sen2cor` installation is by using the `sen2cor` GUI but this is not possible when running a noninteractive script.

-----------------------------------------------------------------
# Sessioninfo
```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1
```
--------------------------------------------------------------------------------
# Binpaths
```
> sen2r::load_binpaths()
list()
attr(,"path")
[1] "/tmp/RtmpgKeS5M/paths.json"
```
----------------------------------------------------------------------------------
# Init_python

```
> sen2r:::init_python()
$py
Module(__builtin__)

$os
Module(os)

$sys
Module(sys)

$subprocess
Module(subprocess)

$re
Module(re)

$numpy
Module(numpy)

$urllib
Module(urllib)

$zipfile
Module(zipfile)

$gdal
Module(gdal)

$osr
Module(osr)
```
-----------------------------------------------------------------------------
# Sample Script

```
# Credentials
secrets <- fromJSON(Sys.getenv("SECRETS_FILE"))
scihub_user <- secrets$scihub$username
scihub_password <- secrets$scihub$password

# Validate login
sen2r::check_scihub_login(scihub_user, scihub_password)
sen2r::write_scihub_login(scihub_user, scihub_password)

# Rough work
sen2r::load_binpaths(bins = c("gdal", "sen2cor", "aria2", "python"))
```
# Output

```
Searching for a valid GDAL installation...
GDAL version in use: 2.4.2
$gdalinfo
[1] "/usr/bin/gdalinfo"

$ogrinfo
[1] "/usr/bin/ogrinfo"

$gdal_translate
[1] "/usr/bin/gdal_translate"

$gdalwarp
[1] "/usr/bin/gdalwarp"

$gdalbuildvrt
[1] "/usr/bin/gdalbuildvrt"

$gdaldem
[1] "/usr/bin/gdaldem"

$gdal_calc
[1] "/usr/bin/gdal_calc.py"

$gdal_polygonize
[1] "/usr/bin/gdal_polygonize.py"

$gdal_fillnodata
[1] "/usr/bin/gdal_fillnodata.py"

$aria2c
[1] "/usr/bin/aria2c"

$python
[1] "/usr/bin/python2.7"

attr(,"path")
[1] "/tmp/RtmpcfwaEJ/paths.json"
Warning message:
Sen2Cor was not found in your system; you can install it using the function install_sen2cor().
```

**Comment by riazarbi** [comment]
I have managed a workaround that enables me to run sen2r commands in a new docker image that doesn't have any paths predefined. 

Relevant bit of the Dockerfile:
```
# Install
ARG r_packages="sen2r" 

RUN install2.r --error -n 2 -s --deps TRUE $r_packages 

# Configure sen2r
RUN mkdir /sen2cor_255 \
 && Rscript -e 'sen2r:::install_sen2cor("/sen2cor_255", version = "2.5.5")' \
 && chmod -R 0755 /sen2cor_255

USER $NB_USER
```

Relevant bit of my R script:

```
# Bootstrap sen2r config dir
mainDir <- "/home/jovyan"
subDir <- ".sen2r"
ifelse(!dir.exists(file.path(mainDir, subDir)), dir.create(file.path(mainDir, subDir)), FALSE)
file.copy("paths.json", file.path(mainDir, subDir))

# Load paths for sen2r
sen2r::load_binpaths(bins = c("gdal", "sen2cor", "aria2", "python"))

# Save credentials
scihub_user <- secrets$scihub$username
scihub_password <- secrets$scihub$password
# Validate login
sen2r::check_scihub_login(scihub_user, scihub_password)
# Set login creds
sen2r::write_scihub_login(scihub_user, scihub_password)

# Execute sen2r() job
sen2r::sen2r(param_list = "sen2r_parameters6_offline.json", gui=F)
```

Complete paths.json file:

```
{
  "gdalinfo": ["/usr/bin/gdalinfo"],
  "ogrinfo": ["/usr/bin/ogrinfo"],
  "gdal_translate": ["/usr/bin/gdal_translate"],
  "gdalwarp": ["/usr/bin/gdalwarp"],
  "gdalbuildvrt": ["/usr/bin/gdalbuildvrt"],
  "gdaldem": ["/usr/bin/gdaldem"],
  "gdal_calc": ["/usr/bin/gdal_calc.py"],
  "gdal_polygonize": ["/usr/bin/gdal_polygonize.py"],
  "gdal_fillnodata": ["/usr/bin/gdal_fillnodata.py"],
  "aria2c": ["/usr/bin/aria2c"],
  "sen2cor": ["/sen2cor_255/bin/L2A_Process"],
  "python": ["/usr/bin/python2.7"]
}

```

Some things to note

1. In the Dockerfile sen2cor is downloaded and installed to its own directory, and that directory has the same permissions set as /bin - that is, anyone can execute and read.
2. The docker container runs as unprivileged user `$NB_USER`. This is safer.
3. I avoid the dialog when loading the `sen2r` library by never loading the library. This means every call to a `sen2r` function needs to have the `sen2r::` prefix.
4. I avoid the dialog asking me where the paths are by copying a `path.json` file to the right place in the home directory at runtime.

I will leave this issue open because it is a bit of a hack - I don't think this is the best pattern for noninteractive jobs, but it does work for now. 

Feel free to close @ranghetti if you want to but I would suggest that you enhance the package to allow complete non-interactive behaviour if the user so chooses.

 I would try do it myself but I do not have sufficient skill.

**Comment by riazarbi** [comment]
You can find my Dockerfile [here](https://github.com/riazarbi/jupyter-rstudio-proxy/blob/master/r-heavy/Dockerfile) if you want to see the rest of the context of my docker image.

**Comment by ranghetti** [comment]
Hello @riazarbi,
thank you for reporting this issue and for posting your solution. I implemented the interactive dialog before submitting the package to CRAN, because asking for user permission to write on disk is a mandatory CRAN requirement. Doing that I did not think to non-interactive executions like a docker container. 

In next days I will write a workaround for that (maybe a simple accessory function to give this permission). Moreover, I will fix the sen2r [Dockerfile](https://github.com/ranghetti/sen2r/blob/master/Dockerfile) (actually, after implementing the interactive dialog the sen2r Docker container is no more configured properly).

**Comment by riazarbi** [comment]
Thanks @ranghetti.  If you could set the package to search `$PATH` before prompting the user that might work - I can then make sure `sen2cor` is in `$PATH`

**Comment by ranghetti** [comment]
> If you could set the package to search `$PATH` before prompting the user that might work - I can then make sure `sen2cor` is in `$PATH`

I preferred to skip using PATH because editing PATH is not allowed by CRAN policies. 

I am editing the Dockerfile: it is not yet ready to be pushed on master branch, but you can see it on branch [devel](https://github.com/ranghetti/sen2r/blob/devel/Dockerfile). At this stage, the runtime dependencies are installed/configured at user side.
I wrote a function `link_sen2cor()` to non-interactively link an existing Sen2cor installation, but I still have some problems (Sen2Cor creates a config file at user side, which I should manage); so, for now Sen2Cor is installed at user side.

If you want to propose some edits to the Dockerfile feel free to do it.
Thanks,

**Comment by ranghetti** [comment]
The new Dockerfile is ready, and was used to build the latest [sen2r container](https://hub.docker.com/r/ranghetti/sen2r).

**Comment by riazarbi** [comment]
Great, thanks @ranghetti.
