### ISSUE TITLE
Scale pixel values bands of BOA tiff

### ISSUE THREAD

**Issue by jitsr** [ranghetti/sen2r#236]
Hi,

This might not be a question to ask here, but I can't find it anywhere else.
I'm trying to figure out the scales of the different bands that are returned. 
For the RGB pictures it is easy because it is a setting (mainly 0-2500 or 0-7500). The indices are also clear (0-10000).
But I'm stuck by the ranges of the bands that can be found in the BOA tiff. They are also within the thousands, but is the range between 0-2500, 0-7500 or 0-10000 or even higher? I saw values over 11000 for band 9? So I can't find a clear answer. 
I am using the pixel values for each separate band, but then it is good to understand what are the limits?

I hope you can help or direct me to somewhere where I can find the answer. 
I am sorry for using this place to ask.

**Comment by ranghetti** [comment]
Hi,
the "normal" range is 0-10000, corresponding to 0-1 Surface Reflectances.
You can see [this answer](https://gis.stackexchange.com/questions/233874/what-is-the-range-of-values-of-sentinel-2-level-2a-images) for an explanation of the possibility to retrieve values > 10000 (especially in Level-1C images).

**Comment by jitsr** [comment]
Right! Thank you! 
I only use 2A images, but if I understand it correct, you can't just divide by 10000 to find the 0-1 surface reflectance, but it gives a good approach?

**Comment by ranghetti** [comment]
> I only use 2A images, but if I understand it correct, you can't just divide by 10000 to find the 0-1 surface reflectance, but it gives a good approach?

The division by 10000 is the correct operation to obtain the 0-1 SR values. If I understood correctly, values > 1 can however be found because Sen2Cor parametrisations never exatly correspond to the ground truth.

**Comment by jitsr** [comment]
Oke, thank you!
