### ISSUE TITLE
What is the process for adding indices?

### ISSUE THREAD

**Issue by riazarbi** [ranghetti/sen2r#241]
Hello. 

I am trying to replicate the result of [this paper](https://pdfs.semanticscholar.org/a811/6273836157a0f0609851aa83f8dcc7ba24fe.pdf) on the City of Cape Town. 

In order to replicate this, we need the following indices -

![image](https://user-images.githubusercontent.com/13433911/68922552-9976d200-0784-11ea-959e-c052ed558db6.png)

![image](https://user-images.githubusercontent.com/13433911/68922987-c677b480-0785-11ea-9483-f828d8af66a1.png)

Looking through the documented indices in the `sen2r` gui, it looks like I can perform a replication of the main result with the addition of the following indices - 

1. NDTI
2. NDVIre
3. MNDWI
4. NDBI

Would it be possible to add these, or, failing that, to give me guidance on how to do it myself? 

If we could replicate this result it will be very useful for our urban planners!

**Comment by ranghetti** [comment]
Hello,
I intentionally did not implement a procedure to add custom indices at user side: in this way, missing indices can be requested here and made available for all users. So, this is the correct procedure to add missing indices.

Some of the indices that you required are already present in sen2r, but with different names:

1. _NDTI_ is **NBR2**;
2. _NDVIre_ is **Rededge2** (in the GUI, you must uncheck "Show only verified indices" to see this);
3. _MNDWI_ is **NDSI**.

_NDBI_ is the additive inverse of sen2r's **NDWI**, while take attention that the formula of the provided _NDWI_ corresponds to sen2r's index **NDWI2**, not to **NDWI**.

I have not yet implemented a convenient way to check formulas of the selected indices; you can use function `list_indices()` in this way:
```r
list_indices(c("name","s2_formula","a","checked"), pattern="((^NBR2$)|(^Rededge2$)|(^NDVI$)|(^SAVI$)|(^NDWI2?$)|(^NDSI$))", all=TRUE)
```

I will add indices _NDVIre_ and _NDBI_ soon; regarding to other indices, let me know if you want to add them (duplicating the existing ones with the provided names) or if you would be satisfied with the existing ones.

**Comment by ranghetti** [comment]
The two missing indices were added on GitHub "devel" version, which can be installed with
```r
remotes::install_github("ranghetti/sen2r", ref = "devel")
```
Let me know if you need further integrations.

**Comment by ranghetti** [comment]
Now the missing indices are on master GitHub branch (**not** yet on CRAN):
```r
remotes::install_github("ranghetti/sen2r")
```

I am closing this, feel free to reopen if necessary.

**Comment by riazarbi** [comment]
Thank you @ranghetti! Will send you results if we develop anything interesting.
