### ISSUE TITLE
Error: task 1 failed - ""S2_____.tif", "S2_____.tif" were not recognised.

### ISSUE THREAD

**Issue by jeaggu** [ranghetti/sen2r#246]
Hi Luigi,

I am having an issue that I have not been able to solve for days. When I run the sen2R as shown below then the tool says  The filename or extension is too long. I trid changing the variable path order but it still does not work. So you have any clue about how to solve this?

sen2r(param_list = "D:/Sen2R_parametersMALAYSIA_offlinemode.json",        tmpdir = "D:/Downloads_Jesus")
[2019-12-09 14:43:54] Starting sen2r execution.
GDAL version in use: 2.4.0
Loading required namespace: stringi
[2019-12-09 14:43:55] Computing output names...
Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
[2019-12-09 14:43:56] Updating output names...
Error in { : 
  task 1 failed - "task 1 failed - ""S2_____.tif", "S2_____.tif" were not recognised.""
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\Program Files\R\R-3.6.1\bin\x64;D:\SoftwareInstalledHere\snap\bin;C:\Python27;D:\SoftwareInstalledHere\Anaconda2_27;D:\SoftwareInstalledHere\Anaconda2_27\Library\mingw-w64\bin;D:\SoftwareInstalledHere\Anaconda2_27\Library\usr\bin;D:\SoftwareInstalledHere\Anaconda2_27\Library\bin;D:\SoftwareInstalledHere\Anaconda2_27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Git LFS;C:\Program Files\TortoiseGit\bin;D:\Downloads\phylocom-4.2\w32\phylocom;D:\SoftwareInstalledHere\snap\bin": The filename or extension is too long

sen2r::load_binpaths()
$gdalinfo
[1] "C:\\OSGEO4~1\\bin\\gdalinfo.exe"

$ogrinfo
[1] "C:\\OSGEO4~1\\bin\\ogrinfo.exe"

$gdal_translate
[1] "C:\\OSGEO4~1\\bin\\GDAL_T~1.EXE"

$gdalwarp
[1] "C:\\OSGEO4~1\\bin\\gdalwarp.exe"

$gdalbuildvrt
[1] "C:\\OSGEO4~1\\bin\\GDALBU~1.EXE"

$gdaldem
[1] "C:\\OSGEO4~1\\bin\\gdaldem.exe"

$python
[1] "C:\\OSGEO4~1\\bin\\python.exe"

$gdal_calc
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_C~1.PY"

$gdal_polygonize
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_P~2.PY"

$gdal_fillnodata
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_F~1.PY"

$aria2c
[1] "D:\\SoftwareInstalledHere\\aria2-1.34.0-win-64bit-build1\\aria2c.exe"

$sen2cor
[1] "D:\\SoftwareInstalledHere\\Sen2Cor_2.5.5\\Sen2Cor-02.05.05-win64\\L2A_Process.bat"

attr(,"path")
[1] "~/.sen2r/paths.json"

sen2r:::init_python()
GDAL version in use: 2.4.0
$py
Module(__builtin__)

$os
Module(os)

$sys
Module(sys)

$subprocess
Module(subprocess)

$re
Module(re)

$numpy
Module(numpy)

$urllib
Module(urllib)

$zipfile
Module(zipfile)

$gdal
Module(gdal)

$osr
Module(osr)

Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\Program Files\R\R-3.6.1\bin\x64;D:\SoftwareInstalledHere\snap\bin;C:\Python27;D:\SoftwareInstalledHere\Anaconda2_27;D:\SoftwareInstalledHere\Anaconda2_27\Library\mingw-w64\bin;D:\SoftwareInstalledHere\Anaconda2_27\Library\usr\bin;D:\SoftwareInstalledHere\Anaconda2_27\Library\bin;D:\SoftwareInstalledHere\Anaconda2_27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Git LFS;C:\Program Files\TortoiseGit\bin;D:\Downloads_Jesus\phylocom-4.2\w32\phylocom;D:\SoftwareInstalledHere\snap\bin": The filename or extension is too long

**Comment by ranghetti** [comment]
Hi @jeaggu ,
actually "The filename or extension is too long" is only a warning, which is caused by a recent edit to the management of PATH variable and which I still have to investigate (but it does not affect the processing, probably I only need to hide it).
The error is this:
```
Error in { :
task 1 failed - "task 1 failed - ""S2_____.tif", "S2_____.tif" were not recognised.""
```

To understand it, please post the content of file `D:/Sen2R_parametersMALAYSIA_offlinemode.json`.

(Ps. during next days I have few time for managing sen2r issues, so I could answer late; sorry for that).

**Comment by jeaggu** [comment]
Hi @ranghetti,

Thanks for your reply, here the info requested, the content of the Sen2R_parametersMALAYSIA_offlinemode.json :

{
  "preprocess": [true],
  "s2_levels": ["l1c", "l2a"],
  "sel_sensor": ["s2a", "s2b"],
  "online": [false],
  "order_lta": [true],
  "downloader": ["aria2"],
  "overwrite_safe": [false],
  "rm_safe": ["no"],
  "max_cloud_safe": [10],
  "step_atmcorr": ["auto"],
  "timewindow": ["2016-01-01", "2017-12-01"],
  "timeperiod": ["full"],
  "extent": ["{\n  \"type\": \"FeatureCollection\",\n  \"features\": [\n    {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"FID\": 0,\n        \"Plot_ID\": \"MS\"\n      },\n      \"geometry\": {\n        \"type\": \"Polygon\",\n        \"coordinates\": [\n          [\n            [116.9497104, 4.7540006],\n            [116.9497318, 4.7530851],\n            [116.9508191, 4.7531261],\n            [116.9508113, 4.7533092],\n            [116.9506327, 4.7533033],\n            [116.9506132, 4.7538663],\n            [116.9504346, 4.7538604],\n            [116.9504268, 4.7540455],\n            [116.9497104, 4.7540006]\n          ]\n        ]\n      }\n    },\n    {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"FID\": 1,\n        \"Plot_ID\": \"MB\"\n      },\n      \"geometry\": {\n        \"type\": \"Polygon\",\n        \"coordinates\": [\n          [\n            [116.9693391, 4.7473739],\n            [116.9700041, 4.7467449],\n            [116.9706428, 4.7473857],\n            [116.9700041, 4.7479942],\n            [116.9693391, 4.7473739]\n          ]\n        ]\n      }\n    },\n    {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"FID\": 2,\n        \"Plot_ID\": \"Danum_2\"\n      },\n      \"geometry\": {\n        \"type\": \"Polygon\",\n        \"coordinates\": [\n          [\n            [117.7932854, 4.9538783],\n            [117.7932994, 4.9529768],\n            [117.794202, 4.9529833],\n            [117.7941917, 4.9538848],\n            [117.7932854, 4.9538783]\n          ]\n        ]\n      }\n    },\n    {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"FID\": 3,\n        \"Plot_ID\": \"Danum_1\"\n      },\n      \"geometry\": {\n        \"type\": \"Polygon\",\n        \"coordinates\": [\n          [\n            [117.7956251, 4.9524741],\n            [117.7956353, 4.9515727],\n            [117.7965341, 4.9515754],\n            [117.7965314, 4.952473],\n            [117.7956251, 4.9524741]\n          ]\n        ]\n      }\n    }\n  ]\n}"],
  "s2tiles_selected": ["50NML", "50NNL"],
  "s2orbits_selected": [null],
  "list_prods": ["TOA", "BOA", "SCL"],
  "list_indices": ["BNDVI", "NDRE"],
  "list_rgb": [null],
  "rgb_ranges": [null],
  "index_source": ["BOA"],
  "mask_type": ["land"],
  "max_mask": [80],
  "mask_smooth": [30],
  "mask_buffer": [30],
  "clip_on_extent": [false],
  "extent_as_mask": [false],
  "extent_name": ["Malaysia"],
  "reference_path": [null],
  "res": [null],
  "res_s2": ["10m"],
  "unit": ["Meter"],
  "proj": [null],
  "resampling": ["near"],
  "resampling_scl": ["near"],
  "outformat": ["GTiff"],
  "rgb_outformat": ["GTiff"],
  "index_datatype": ["Int16"],
  "compression": ["NONE"],
  "rgb_compression": ["NONE"],
  "overwrite": [false],
  "path_l1c": ["D:/SoftwareInstalledHere/SENTINEL2images/SENTINELSAT/"],
  "path_l2a": ["D:/SoftwareInstalledHere/SENTINEL2images/SENTINELSAT/"],
  "path_tiles": [null],
  "path_merged": ["D:/SoftwareInstalledHere/SENTINEL2images/Sen2R/AMERICAS"],
  "path_out": ["D:/SoftwareInstalledHere/SENTINEL2images/SENTINELSAT"],
  "path_rgb": [""],
  "path_indices": [""],
  "path_subdirs": [true],
  "thumbnails": [true],
  "log": [null],
  "parallel": [8],
  "processing_order": ["by_groups"],
  "pkg_version": ["1.2.1"]
}

**Comment by ranghetti** [comment]
Sorry for late answer.
Despite I was not able to reproduce your error, I verified that it occurs when, for some reasons, no SAFE products matching the input requirements were found in the sen2r second SAFE check (after downloading them). 

To solve, you can try one of the followings:
1. try running `sen2r()` in online mode;
2. try this alternative chain, which will lead to equivalent output results:
    ```r
    sen2r(
      param_list = "D:/Sen2R_parametersMALAYSIA_offlinemode.json", 
      tmpdir = "D:/Downloads_Jesus",
      extent = s2_tiles()[s2_tiles()$tile_id %in% c("50NML", "50NNL"),], 
      clip_on_extent = TRUE,
      path_out = "D:/SoftwareInstalledHere/SENTINEL2images/Sen2R/AMERICAS",
      path_merged = NA
    )
    ```

In the meanwhile, I will fix the code in order not to return this error in this situation, but only to exit elegantly.
      
Let me know,

**Comment by jeaggu** [comment]
Hi @ranghetti,

Thanks for looking into it. I follow the new script you suggested above and t works when I have tiles available already. Then I also created a new GeoJson file directly in QGis and not ArcGis and runned my original script in online mode and it worked. Thus, I think there is something going on with the GeoJson files created in ArcGis.

Regards,

Jesus
