### ISSUE TITLE
Error: File apihub.txt with.... is missing

### ISSUE THREAD

**Issue by DijoG** [ranghetti/sen2r#247]
Dear Luigi,

sen2r seems to be a very promising package, however I can not get it work.

This issue is as follows:
![grafik](https://user-images.githubusercontent.com/34399619/70528995-cdf56800-1b4f-11ea-8476-16f7ad0fa728.png)

On the https://scihub.copernicus.eu/dhus/#/home login is without any problem.

I have tried to reinstall the package as suggested by you in a similar issue using ref="devel" addition in the install command, but the problem still persists.

Hope to find some solution.
Thank you in advance!
All the best,

Gergo Dioszegi
MSc, University Assistant
Institute of Geomatics
University of Natural Resources and Life Sciences, Vienna
A-1190 Vienna, Peter Jordanstr. 82Tel.: +43 1 47654-85734 
e-mail: gergo.dioszegi@boku.ac.at

**Comment by lbusett** [comment]
Hi @DijoG , 

  when did you create those credentials? Consider that if they are "new", or recently updated, it can take some days before you can use them in sen2r (see https://scihub.copernicus.eu/twiki/do/view/SciHubWebPortal/APIHubDescription). 

What do you get if you issue this command? 

``` r 
check_scihub_login("user", "user")
```

**Comment by DijoG** [comment]
Hello Lorenzo,

it might clear everything, because the registration is only about 3 hours old.

I get TRUE, suggesting I have to wait.

Thanks for clarifying the issue!

**Comment by lbusett** [comment]
Good, that should be the problem, then. In the meantime, if you want to "test" the package, you can try using the "dummy" credentials ("user", "user") 

@ranghetti Note that I will push to devel a possible improvement in documentation, about this problem.

**Comment by ranghetti** [comment]
Thanks @lbusett, this was integrated in master branch (v. 1.2.1.9006).
