### ISSUE TITLE
Band 10 in Level-2 products

### ISSUE THREAD

**Issue by ranghetti** [ranghetti/sen2r#249]
_Message received by e-mail_

> I noticed that after running sen2corr or downloading L2A data, the B10 bands is not present in the directories.
But, I have developed some cloud mask procedures and they need B10 band to take into account of thin and thick cirrus.
About me, the only way to keep the B10 band is to download the L1C product, save the B10 band, process sen2corr and finally, run the cloud mask algorithm using the saved B10 band
Have you any other more efficient method?

**Comment by ranghetti** [comment]
Hello Xavier,
I am not sure to have understood your question.

Band 10 is not present in Level-2A products -- neither downloaded from SciHub nor produced using Sen2Cor -- because it does not include information about bottom-of-atmosphere reflectance (https://sentinel.esa.int/web/sentinel/user-guides/sentinel-2-msi/resolutions/radiometric).
This is not a sen2r feature, but a characteristic of Level-2A products. For this reason you must take it from Level-1C products.

I do not know how your cloud masking procedure works; I suppose that it takes as input files 1. the image to be masked, and 2. the band 10 layer. I interpret your question in this way: which is the more efficent way to obtail these input files using sen2r?

If it is so, you should set the parameters in order to produce
1. the image to be masked (BOA reflectances? A spectral index image?) _and_ 
2. TOA products, from which extracting band 10.

At this stage there is not the possibility to save a single spectral band, so you have to save the whole TOA image, and then extract band 10 from each TOA image by yourself.

Conversely, if your cloud masking code takes as input files SAFE images instead that pre-processed (i.e. clipped) scenes, I think it would be easier to use sen2r only to download/produce Level-1C _and_ Level-2A archives, and then apply your code to these products.

Let me know if I answered to your question,

**Comment by xbailleau** [comment]
Hello Luigi, 
Thanks for the tips, you answered to all my questions
Regards
