### ISSUE TITLE
Missing ogdi.dll

### ISSUE THREAD

**Issue by ranghetti** [ranghetti/sen2r#251]
_Issue received by email._

> I am trying to use the s2_translate() function on a .SAFE folder. However, it throws an error, saying that ogdi.dll is missing. I just installed the latest QGIS version, which also includes ogdi.dll. How do I link it or how do I get it for sen2r?

**Comment by ranghetti** [comment]
Dear Ulrich,
if you are using the CRAN version of the package, try first installing the GitHub version (some improvements which I did recently should have fixed this problem):
```r
remotes::install_github("ranghetti/sen2r")
```
If this will not help, please provide some system information (see #186), together with:
```r
packageVersion("rgdal")
rgdal::rgdal_extSoftVersion()
```

**Comment by UK85** [comment]
Dear Luigi,
I solved the problem by adding the path to my ogdi.dll to R via

`Sys.setenv(PATH=paste(Sys.getenv("PATH"),"C:\\Program Files\\QGIS 3.4\\bin", sep=";"))`

prior to 

`library(sen2r)`

Many thanks,
Ulrich
