### ISSUE TITLE
.tif encoding and CRS fail in merged s2 l2a

### ISSUE THREAD

**Issue by CharlesNickmilder** [ranghetti/sen2r#253]
Hello,
I have been using your package for 2 months and I am facing a quite odd problem:
it seems that the merging of tiles included in the package is not working exactly as it should.
I'm curently using your package to retrieve S-2 tiles from the hub, putting them in L2A and merging them in order to ease the extraction of local values. I was surprised to discover that for some area the extracted values were 0 although the representation of the tile on the hub isn't NULL.
So I explored the merged product with QGIS and the merging appaered to fail. Let's take a reproducible example:
-below the post are my sessionInfo();
-let's consider the area of interest as Belgium;
-the date of interest for this example is : 2019/08/31;
-below the sessionInfo() is the parametrization of the download through sen2r() comand.
The image below shows that the downloaded files are non-zero for B02 for the easthern part of Belgium.
![image](https://user-images.githubusercontent.com/33217516/71969421-eae09200-3206-11ea-8b90-9c5080a2dd7c.png)
The image below is a representation of the merged file with a 10m resolution. It appears that a part of the image can't be shown although it is supposed to exist given that the original data exist.
![image](https://user-images.githubusercontent.com/33217516/71969877-d51f9c80-3207-11ea-91c0-86b64486b178.png)
While zooming or moving the map some errors are thrown. Please find below the corresponding printscreen:
![image](https://user-images.githubusercontent.com/33217516/71970021-1b74fb80-3208-11ea-9b91-246f16aeaf00.png)
I have also discovered another bug: I tried to change the coordinate system of the output files through the sen2r command and it never worked. Even worse: when I load the merged layer I have to reset the CRS because nor R nor QGIS can find it. Maybe it is linked with the previous bug?

Have you any idea of the origin of the problem and how to solve it?

Regards

Charles

`sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] caret_6.0-84       lattice_0.20-38    FactoMineR_2.0     stringr_1.4.0      sen2r_1.2.1        future.apply_1.3.0 future_1.15.1     
 [8] ggplot2_3.2.1      mapview_2.7.0      velox_0.2.0        sf_0.8-0           rgeos_0.5-2        rgdal_1.4-8        gdalUtils_2.0.1.14
[15] data.table_1.12.8  lwgeom_0.1-7       purrr_0.3.3        doParallel_1.0.15  iterators_1.0.12   foreach_1.4.7      units_0.6-5       
[22] dplyr_0.8.3        raster_3.0-7       sp_1.3-2          

loaded via a namespace (and not attached):
  [1] colorspace_1.4-1     class_7.3-15         leaflet_2.0.3        satellite_1.0.2      corpcor_1.6.9        base64enc_0.1-3     
  [7] fs_1.3.1             rstudioapi_0.10      listenv_0.8.0        ggrepel_0.8.1        lubridate_1.7.4      prodlim_2019.11.13  
 [13] codetools_0.2-16     splines_3.6.1        R.methodsS3_1.7.1    leaps_3.0            jsonlite_1.6         cluster_2.1.0       
 [19] png_0.1-7            R.oo_1.23.0          shinydashboard_0.7.1 shiny_1.4.0          compiler_3.6.1       httr_1.4.1          
 [25] assertthat_0.2.1     Matrix_1.2-18        fastmap_1.0.1        lazyeval_0.2.2       survey_3.36          later_1.0.0         
 [31] htmltools_0.4.0      tools_3.6.1          gtable_0.3.0         glue_1.3.1           reshape2_1.4.3       geojson_0.3.2       
 [37] V8_2.3               Rcpp_1.0.3           relaimpo_2.2-3       nlme_3.1-143         crosstalk_1.0.0      timeDate_3043.102   
 [43] gower_0.2.1          globals_0.12.5       mime_0.7             lifecycle_0.1.0      XML_3.98-1.20        jqr_1.1.0           
 [49] MASS_7.3-51.4        scales_1.1.0         ipred_0.9-9          promises_1.1.0       mapedit_0.5.0        yaml_2.2.0          
 [55] curl_4.3             reticulate_1.13      pander_0.6.3         rpart_4.1-15         stringi_1.4.3        maptools_0.9-9      
 [61] e1071_1.7-3          leaflet.extras_1.0.0 boot_1.3-24          lava_1.6.6           rlang_0.4.2          pkgconfig_2.0.3     
 [67] recipes_0.1.8        htmlwidgets_1.5.1    tidyselect_0.2.5     plyr_1.8.5           magrittr_1.5         R6_2.4.1            
 [73] generics_0.0.2       geojsonio_0.8.0      DBI_1.1.0            pillar_1.4.3         foreign_0.8-72       withr_2.1.2         
 [79] stars_0.4-0          nnet_7.3-12          survival_3.1-8       scatterplot3d_0.3-41 abind_1.4-5          tibble_2.1.3        
 [85] crayon_1.3.4         shinyWidgets_0.5.0   shinyFiles_0.7.5     KernSmooth_2.23-16   grid_3.6.1           ModelMetrics_1.2.2  
 [91] digest_0.6.23        classInt_0.4-2       flashClust_1.01-2    webshot_0.5.2        xtable_1.8-4         httpuv_1.5.2        
 [97] R.utils_2.9.2        stats4_3.6.1         munsell_0.5.0        viridisLite_0.3.0    mitools_2.4          shinyjs_1.0
`

`sen2r(gui =F,
        preprocess = T,
        s2_levels = "l2a",
        sel_sensor = c("s2a","s2b"),
        online = T,
        order_lta = T,
        apihub =  paste0(WDSentinel,"/sen2r/apihub.txt"),
        downloader = "aria2",
        overwrite_safe = F,
        rm_safe = "no",
        step_atmcorr = "auto",
        max_cloud_safe = 50,
        timewindow = c(as.Date("2019-08-01"), as.Date("2019-08-31")),
        timeperiod = "full",
        s2tiles_selected = c("31UES", "31UFS", "31UET", "31UFT", "31UGS", "31UDS", "31UER", "31UFR", "31UGR", "31UFQ"),
        list_prods = c("BOA","SCL"),
        mask_type="scl_0_1",
        max_mask=100,
        clip_on_extent = T,
        extent_as_mask = F,
        res = c(10,10),
        proj = "+proj=utm +zone=31 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
        resampling = "near",
        outformat = "GTiff",
        index_datatype="UInt16",
        overwrite = T,
        path_l1c = paste0(WDSentinel,"/sen2r"),
        path_l2a = paste0(WDSentinel,"/sen2r"),
        path_merged = paste0(WDSentinel,"/S2Merged"),
        path_out = paste0(WDSentinel,"/sen2r"),
        thumbnails = F,
        path_subdirs = T,
        parallel = 4,
        processing_order = "4",
        log = paste0(WDSentinel,"/logs.txt"))
`

**Comment by ranghetti** [comment]
Hello,
thank you for signaling that. The reason of the first issue is related to the high output file size (> 4 GB):
```
ERROR 1: TIFFAppendToStrip:Maximum TIFF file size exceeded. Use BIGTIFF=YES creation option.
```

By default, GDAL generates a BigTIFF if the output expected size is > 4GB, but this option fails if compression is used (see https://gdal.org/drivers/raster/gtiff.html).
I will try to automatically modify this default behaviour basing on the number of used S2 tiles; otherwise I will ad an explicit function argument).
I will inform you when this fix will be done. In the meanwhile, you can try this workaround: save outputs as ENVI files (`outformat = "ENVI"`), and then convert them to GeoTIFF using gdal_translate (with the option `-co BIGTIFF=YES`).

Regarding the second issue, it should have been solved with 0082ca146e62187c85c29bd76e10f02cce26e281: try reinstalling the package from GitHub (`remotes::install_github("ranghetti/sen2r")`).

**Comment by CharlesNickmilder** [comment]
Hello,
I downloaded the updated version of sen2r and I'm going to launch my code tonight. We will see if the second bug is solved.
Concerning the first one I gonna need some time givent that I'm not used to gdal_translate.
Regards

**Comment by ranghetti** [comment]
Ok, but take into account that, at this stage (until I will have fixed the
BigTIFF issue), you need in any case to save outputs as ENVI files instead
than GeoTIFF if you want to avoid the first error (and so to check if the
second was fixed).

**Comment by CharlesNickmilder** [comment]
I have set the encoding to ENVI and redownloaded the package (modified code below). Once launched it asked to install miniconda although I already have Anaconda installed on my laptop. I said no and it appears that the sen2r comand does not recognize the installed anaconda nor does want to launch without the version that has been encoded.
Then I tried to reinstall the sen2r package and it does not ask me this anymore nor does it launches the comand. Is this the normal behavior? If it is, I wonder if it's a good idea to keep in memory the choice without giving a chance to the user to choose again.
`
sen2r(gui =F,
        preprocess = T,
        s2_levels = "l2a",
        sel_sensor = c("s2a","s2b"),
        online = T,
        order_lta = T,
        apihub =  paste0(WDSentinel,"/sen2r/apihub.txt"),
        downloader = "aria2",
        overwrite_safe = F,
        rm_safe = "no",
        step_atmcorr = "auto",
        max_cloud_safe = 50,
        timewindow = c(as.Date("2019-08-01"), as.Date("2019-08-31")),
        timeperiod = "full",
        s2tiles_selected = c("31UES", "31UFS", "31UET", "31UFT", "31UGS", "31UDS", "31UER", "31UFR", "31UGR", "31UFQ"),
        list_prods = c("BOA","SCL"),
        mask_type="scl_0_1",
        max_mask=100,
        clip_on_extent = T,
        extent_as_mask = F,
        res = c(10,10),
        proj = "+proj=utm +zone=31 +ellps=WGS84 +datum=WGS84 +units=m +no_defs",
        resampling = "near",
        outformat = "ENVI",
        index_datatype="UInt16",
        overwrite = T,
        path_l1c = paste0(WDSentinel,"/sen2r"),
        path_l2a = paste0(WDSentinel,"/sen2r"),
        path_merged = paste0(WDSentinel,"/S2Merged"),
        path_out = paste0(WDSentinel,"/sen2r"),
        thumbnails = F,
        path_subdirs = T,
        parallel = 4,
        processing_order = "4",
        log = paste0(WDSentinel,"/logs.txt")) 
  
`

**Comment by ranghetti** [comment]
Actually the choice of the runtime dependecies is kept in memory, with the exception of a recent change (492e387cd7f2c21c304a7081db63ac458d5af068): if the Python binary set as dependency has no module "gdal", a different version is searched. This was made necessary by the recent update of GDAL 2 to GDAL 3, which is using Python3 instead than Python2: if Python2 was set as dependency, then it needs to be redefined.
Anaconda cannot be used as dependency on Windows, since the OSGeo4W GDAL version (with its own Python) is a mandatory dependency since some months. 

To understand why miniconda was asked, I would need some more information:
```r
packageVersion("rgdal")
rgdal::rgdal_extSoftVersion()
```
Moreover, please report the error message you encountered.

**Comment by lbusett** [comment]
If it can help: I had a similar issue a couple of days ago (was asked to install miniconda), but that was asked by reticulate, not by sen2r.

**Comment by CharlesNickmilder** [comment]
@ranghetti The response of  @lbusett makes sense given that the behavior described in a git-hub topic (https://github.com/rstudio/reticulate/issues/607) is exactly the one I encountered and I updated all my packages recently. Sorry for the inconvenience.
Concerning Gdal please find below the results and a printscreen of the check_sen2r_deps() command.
`
packageVersion("rgdal")
[1] ‘1.4.8’
> rgdal::rgdal_extSoftVersion()
          GDAL GDAL_with_GEOS         PROJ.4             sp 
       "2.2.3"         "TRUE"        "4.9.3"        "1.3-2" 
`
![image](https://user-images.githubusercontent.com/33217516/72140011-0e831400-3390-11ea-890e-df448deb7e4e.png)

I tried to reinstall the github version. During the installation some files couldn't be found (see the chunk below). Then I tried to launch the sen2r command and it suddenly worked. I will keep you aware of the evolution.

`remotes::install_github("ranghetti/sen2r",force = T)
Downloading GitHub repo ranghetti/sen2r@master
These packages have more recent versions available.
Which would you like to update?
1: All                            
2: CRAN packages only             
3: None                           
4: farver  (2.0.1 -> 2.0.2) [CRAN]
5: stringi (1.4.3 -> 1.4.4) [CRAN]
Enter one or more numbers, or an empty line to skip updates:
1
fansi   (NA    -> 0.4.1) [CRAN]
farver  (2.0.1 -> 2.0.2) [CRAN]
stringi (1.4.3 -> 1.4.4) [CRAN]
Installing 3 packages: fansi, farver, stringi
  There are binary versions available but the source versions are later:
        binary source needs_compilation
fansi    0.4.0  0.4.1              TRUE
farver   2.0.1  2.0.2              TRUE
stringi  1.4.3  1.4.4              TRUE
  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/fansi_0.4.0.zip'
Content type 'application/zip' length 221363 bytes (216 KB)
downloaded 216 KB
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/farver_2.0.1.zip'
Content type 'application/zip' length 1899827 bytes (1.8 MB)
downloaded 1.8 MB
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/stringi_1.4.3.zip'
Content type 'application/zip' length 15297905 bytes (14.6 MB)
downloaded 14.6 MB
package ‘fansi’ successfully unpacked and MD5 sums checked
package ‘farver’ successfully unpacked and MD5 sums checked
package ‘stringi’ successfully unpacked and MD5 sums checked
The downloaded binary packages are in
	C:\Users\CNI\AppData\Local\Temp\RtmpKiWEYi\downloaded_packages
WARNING: Rtools is required to build R packages, but is not currently installed.
Please download and install Rtools custom from http://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\CNI\AppData\Local\Temp\RtmpKiWEYi\remotes1f04367c5bc8\ranghetti-sen2r-2ccc98c/DESCRIPTION' ...
-  preparing 'sen2r': (588ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'sen2r_1.2.1.9006.tar.gz'
   * installing *source* package 'sen2r' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'sen2r'
    finding HTML links ... fini
    abs2rel                                 html  
    add_rgb_image                           html  
    build_example_param_file                html  
    check_gdal                              html  
    check_param_list                        html  
    check_sen2r_deps                        html  
    compute_s2_paths                        html  
    comsub                                  html  
    create_indices_db                       html  
    create_s2_dop                           html  
    editModPoly                             html  
    expand_path                             html  
    fix_envi_format                         html  
    gdal_abs2rel_rel2abs                    html  
    gdal_formats_db                         html  
    gdal_warp                               html  
    gdalwarp_grid                           html  
    geograbber_process                      html  
    give_write_permission                   html  
    init_python                             html  
    install_aria2                           html  
    install_sen2cor                         html  
    list_indices                            html  
    load_binpaths                           html  
    load_extent                             html  
    mountpoint                              html  
    nn                                      html  
    normalize_path                          html  
    path_check                              html  
    print_message                           html  
Rd warning: C:/Users/CNI/AppData/Local/Temp/Rtmpe6nS2o/R.INSTALL26042b45721b/sen2r/man/print_message.Rd:28: file link 'strftime' in package 'base' does not exist and so has been treated as a topic
    projpar                                 html  
    raster2rgb                              html  
    raster_metadata                         html  
    s2_calcindices                          html  
    s2_defNA                                html  
    s2_dop                                  html  
    s2_download                             html  
    s2_gui                                  html  
    s2_list                                 html  
    s2_mask                                 html  
    finding level-2 HTML links ... done
    s2_merge                                html  
    s2_order                                html  
    s2_rgb                                  html  
    s2_thumbnails                           html  
    s2_tiles                                html  
    s2_translate                            html  
    safe_getMetadata                        html  
    safe_is_online                          html  
    safe_shortname                          html  
    safelist-class                          html  
    scihub_login                            html  
    sen2cor                                 html  
    sen2r                                   html  
    sen2r_getElements                       html  
    smooth_mask                             html  
    st_as_text_2                            html  
Rd warning: C:/Users/CNI/AppData/Local/Temp/Rtmpe6nS2o/R.INSTALL26042b45721b/sen2r/man/st_as_text_2.Rd:22: file link 'CRS' in package 'rgdal' does not exist and so has been treated as a topic
    st_crs2                                 html  
    stack2rgb                               html  
    str_pad2                                html  
    suppress_warnings                       html  
    tiles_intersects                        html  
    trace_function                          html  
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (sen2r)`

**Comment by ranghetti** [comment]
> During the installation some files couldn't be found (see the chunk below). 

Do not worry about that:
- RD warning are shown because I usually update html documentation only after a a new release (so there are some incoherences among current version 1.2.1.9006 and documentation of version 1.2.1);
- RTools should not be required, since source code does not need to be compiled.

You are still using GDAL 2, so the "old" Python binary should still be fine. If you will see the miniconda alert again, post the output of command `load_binpaths()$python`.

> Then I tried to launch the sen2r command and it suddenly worked. I will keep you aware of the evolution.

Ok, let me know,

**Comment by ranghetti** [comment]
Hello @CharlesNickmilder,
have you solved your issue?
Let us know,

**Comment by CharlesNickmilder** [comment]
@ranghetti The issue is partially solved: I use the CRAN version of the package and store the merged tils in .envi files. Yet it ain't the perfect solution because these files are quite heavy (10 to 50Gb) and I fear that when the package on CRAN will be updated I won't be able to run my code anymore. I never had the message "conda" again and when I launch my code with the dev version of the package it justs stops.  It doesn't make any operation, it justs stops without even issuing a warning.

**Comment by ranghetti** [comment]
I implemented the support for BigTIFF in **sen2r**: in the next version of the package you will able to use it with the argument `outformat = "BigTIFF"` to `sen2r()` function. Now this feature is only on develop branch: if you can test it, you can install it using
```r
remotes::install_github("ranghetti/sen2r", ref = "devel")
```

Regarding your last error, I can not investigate it withour messages; but I do not explude that recent edits could have fixed it.

Ps. to transform ENVI files in GeoTIFF you can use **gdal_translate** with the option `-co BIGTIFF=YES` (you can also use it through QGIS or **gdalUtils** R package, if you are not familiar with the commandline interface).

**Comment by CharlesNickmilder** [comment]
@ranghetti I reinstalled all the packages and checked the log file when I launch the sen2r function. It appears that the error comes indead from reticulate (cf. further)
I tried to load the package before loading any other package but it appears it doesn't work. and a warning is coming back: "In normalizePath(path.expand(path), winslash, mustWork) : path[1]="""
Gonna try to uninstall R and anaconda and only install Rstudio
`
[2020-01-29 14:36:50] ####  Starting sen2r execution.  ####
GDAL version in use: 3.0.2
ERROR: The requested version of Python ('C:\OSGEO4~1\bin\python.exe') cannot be used, as another version of Python
('C:/OSGeo4W64/bin/python3.exe') has already been initialized. Please restart the R session if you need to attach reticulate to a
different version of Python.
Error in use_python(binpaths$python, required = TRUE) : 
  failed to initialize requested version of Python
`

**Comment by ranghetti** [comment]
Doh... This is a **reticulate** issue which is affecting various users (#265). I will manage this behaviour in **sen2r** as soon as possible, in the meanwhile you can refer to #265 for possible solutions about it.

**Comment by ranghetti** [comment]
Hello @CharlesNickmilder,
issue #265 should have been fixed (**reticulate** is no longer a **sen2r** dependence). 

Can you reinstall the last version from GitHub and let us know if processing can now run using `outformat = "BigTIFF"`?
```r
remotes::install_github("ranghetti/sen2r")
```

**Comment by CharlesNickmilder** [comment]
@ranghetti 
Thanks for the simplification. Given that I changed my working environment (uninstalled Anaconda and all related softwares and installed a clean version of R, Rstudio and the package I needed the 29 jan) I no longer had any issue except one that appears only sometimes and that is related to the length of a string (no longer have the log file). The BigTiff format works fine. My code runs without any error.
I think the reticulate issue was also, at least in part, due to the fact of starting R through Anaconda.
