### ISSUE TITLE
Allow suppressing "gdal" progress messages

### ISSUE THREAD

**Issue by lbusett** [ranghetti/sen2r#257]
Currently, many messages related to GDAL processing are sent to the console, even if launching sen2r with suppressmessages  such as in:

``` r
  out1 <- suppressMessages(sen2r(
        gui = FALSE,
        extent = sel_extent_1,
        timewindow = c("2018-04-21", "2018-05-09"),
        list_rgb = "RGB432T",
        path_l1c = safe_folder,
        path_l2a = safe_folder,
        path_out = out_folder_1
    ))
```
`0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 10980, 10980
Creating output file that is 668P x 666L.
Processing /tmp/Rtmp6HrPzH/sen2r_c46fd80764/groupc46690efe8b/merged/TOA/S2B1C_20180422_135__TOA_10.vrt [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 668, 666
0...10...20...30...40...50...60...70...80...90...100 - done.`

It would be nice to be able to suppress those messages to avoid cluttering the terminal, using something like a `verbose_gdal` keyword, defaulting to TRUE.

**Comment by ranghetti** [comment]
`sys::exec_wait()` seems able to capture Python outputs it setting `std_out = FALSE` (or redirecting it). I will edit Python-based GDAL calls in future (for C-based GDAL calls, maybe we should directly use `sf::gdal_utils()` instead).

**Comment by ranghetti** [comment]
Version 1.3.4 (now on CRAN) includes the suppression of most (C-based) GDAL messages (using `sf::gdal_utils`), and of Python-based GDAL utilities if package **`sys`** is installed.
