### ISSUE TITLE
GDAL; upcoming change in crs objects

### ISSUE THREAD

**Issue by edzer** [ranghetti/sen2r#260]
sen2r now fails on CRAN because GDAL 3.0.3 and PROJ 6.3.0 are installed on the check platforms. 

The upcoming version of sf will no longer support expressions like
```r
st_crs2(32609)[["proj4string"]]
```
but 
```
st_crs2(32609)$proj4string
```
will continue to work (by having the $ operator retrieve it from WKT, using GDAL). In the future, also that might get dropped. In the light of current CRAN error, you may want to reconsider what you want to test in sen2r. See https://github.com/r-spatial/sf/issues/1225 .

**Comment by ranghetti** [comment]
Thank you for signaling it. We already did some edits in order to deal with GDAL 3 / PROJ 6 (squashed in commit ddc6f6ed189b3a5b6f8b5ead71d4a5a9b4ef756f); others were done with 2881a07cb4ff06e78e9d1b3c2da2013b5333bb3c (for now in develop branch).
The test which causes that error will be removed starting for next CRAN released version (we will submit it in the next few days).

**Comment by ranghetti** [comment]
sen2r version 1.3.1, including this patch, is on CRAN.

**Comment by edzer** [comment]
For some reason, upcoming sf still breaks sen2r on CRAN, see https://win-builder.r-project.org/incoming_pretest/sf_0.9-0_20200319_213604/reverseDependencies/summary.txt

**Comment by ranghetti** [comment]
The syntax `st_crs2()[["epsg"]]` was still present in some tests (sorry for that). These were fixed on GitHub and will be foxed on CRAN soon (v. 1.3.3).

Some other errors are a consequence of the first error reported for **stars**, and so they will be still present:
```
> sf::st_crs(stars::read_stars(raster_path))
Coordinate Reference System: NA
```

**Comment by ranghetti** [comment]
Hi @edzer ,
I fixed the **sen2r** related problems (thanks for signaling and for "forcing" us to do that).

Nevertheless, this **stars** problem still affects **sen2r** routines:
```
Package: stars
Check: examples
New result: ERROR
  Running examples in â€˜stars-Ex.Râ€™ failed
  The error most likely occurred in:
  
  > tif = system.file("tif/L7_ETMs.tif", package = "stars")
  > x = read_stars(tif)
  > x
  > st_crs(x)
  Coordinate Reference System: NA
```

In order to understand if bypassing it or waiting, I would ask you: have you planned to fix it soon?

Thanks,

**Comment by edzer** [comment]
Yes, I plan to fix this soon!

**Comment by ranghetti** [comment]
Closing after the release of `stars` 0.4-1 on CRAN, which solved.
