### ISSUE TITLE
Error after downloading SAFE and before unzipping it

### ISSUE THREAD

**Issue by VicenteYago** [ranghetti/sen2r#263]
Im using the json generated from the function`build_example_param_file()` , but adapted to my timewindow, extent and output paths:

```{json}
{
  "preprocess": [true],
  "s2_levels": ["l1c", "l2a"],
  "sel_sensor": ["s2a", "s2b"],
  "online": [true],
  "order_lta": [true],
  "downloader": ["builtin"],
  "overwrite_safe": [false],
  "rm_safe": ["no"],
  "max_cloud_safe": [100],
  "step_atmcorr": ["l2a"],
  "timewindow": ["2020-01-23", "2020-01-26"],
  "timeperiod": ["full"],
  "extent": ["~/host/AOIs/aoi_json.geojson"],
  "s2tiles_selected": [null],
  "s2orbits_selected": [null],
  "list_prods": ["BOA", "SCL"],
  "list_indices": ["MSAVI2", "NDVI"],
  "list_rgb": ["RGB432B", "RGB843B"],
  "rgb_ranges": [
    [0, 2500],
    [
      [0, 7500],
      [0, 2500],
      [0, 2500]
    ]
  ],
  "index_source": ["BOA"],
  "mask_type": [null],
  "max_mask": [80],
  "mask_smooth": [0],
  "mask_buffer": [0],
  "clip_on_extent": [true],
  "extent_as_mask": [false],
  "extent_name": ["sen2r"],
  "reference_path": [null],
  "res": [null],
  "res_s2": ["10m"],
  "unit": ["Meter"],
  "proj": [null],
  "resampling": ["near"],
  "resampling_scl": ["near"],
  "outformat": ["GTiff"],
  "rgb_outformat": ["GTiff"],
  "index_datatype": ["Int16"],
  "compression": ["DEFLATE"],
  "rgb_compression": ["DEFLATE"],
  "overwrite": [false],
  "path_l1c": ["~/host/l1c"],
  "path_l2a": ["~/host/l2a"],
  "path_tiles": [null],
  "path_merged": [null],
  "path_out": ["~/host/out"],
  "path_rgb": [""],
  "path_indices": ["~/host/indices"],
  "path_subdirs": [true],
  "thumbnails": [true],
  "log": [null],
  "parallel": [false],
  "processing_order": ["by_groups"],
  "pkg_version": ["1.2.1.9006"]
}
```
when I run it:  `sen2r("~/host/params.json")` I obtain:

[2020-01-27 04:40:19] Starting sen2r execution.
[2020-01-27 04:40:19] Searching for available SAFE products on SciHub...
[2020-01-27 04:40:21] Computing output names...
[2020-01-27 04:40:23] Starting to download the required level-2A SAFE products.
No L2A images needed
[2020-01-27 04:40:23] Check if products are available for download...
[2020-01-27 04:40:23] 1 Sentinel-2 images are already available and will not be ordered.
[2020-01-27 04:40:23] Downloading Sentinel-2 image 1 of 1 (S2B_MSIL2A_20200126T105229_N0213_R051_T30SXH_20200126T123028.SAFE)...
  |=====================================================================================| 100%

and the the following error occurs: 

Error in { : 
  task 1 failed - "task 1 failed - "missing value where TRUE/FALSE needed""

The product its download successfully but just after that the function breaks and the file remains compressed. 

Im using the dockerised version.

UPDATE: 

Here is the content of the file geojson file:

```{geojson}
{"type":"Polygon","coordinates":[[[-1.4634,38.0584],[-1.4619,38.059],[-1.4606,38.0578],[-1.4596,38.0563],[-1.4591,38.0547],[-1.4588,38.0527],[-1.46,38.051],[-1.4617,38.0511],[-1.4625,38.0524],[-1.4621,38.0538],[-1.4606,38.0543],[-1.4613,38.0548],[-1.4618,38.0549],[-1.463,38.0561],[-1.463,38.0568],[-1.4634,38.0584]]]}
```

Thanks.

**Comment by ranghetti** [comment]
Commit ae089ff03818c7ba42e1d48fd4b947fab2de7bc9 fixed it; re-pull the docker image to try again.
Please let me know if this solved.

**Comment by VicenteYago** [comment]
I confirm it works now. 💯
