### ISSUE TITLE
Problem with OSGEO python conflict with reticulate python version

### ISSUE THREAD

**Issue by WalterCh** [ranghetti/sen2r#265]
Hi. I'm having this problem while trying to launch the GUI for sen2r() 
```
> sen2r()
[2020-01-28 12:30:27] Starting sen2r execution.
GDAL version in use: 2.4.1
ERROR: The requested version of Python ('C:\OSGEO4~1\bin\python.exe') cannot be used, as another version of Python
('C:/Users/Radar/AppData/Local/r-miniconda/envs/r-reticulate/python.exe') has already been initialized. Please restart the R session
if you need to attach reticulate to a different version of Python.
Error in use_python(binpaths$python, required = TRUE) : 
  failed to initialize requested version of Python
```
I tried reinstalling sen2r using the command 
```
remotes::install_github("ranghetti/sen2r")
```
And it worked the first time, but after a restart of the computer I get the same error. I read in another issue that you requested this output
```
> Sys.getenv("PATH")
[1] "C:\\Users\\Radar\\AppData\\Local\\r-miniconda\\envs\\r-reticulate;C:\\Users\\Radar\\AppData\\Local\\r-miniconda\\envs\\r-reticulate\\Scripts;C:\\Users\\Radar\\AppData\\Local\\r-miniconda\\envs\\r-reticulate\\Library\\bin;C:/OSGEO4~1/bin;C:\\Program Files\\R\\R-3.6.2\\bin\\x64;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\MATLAB\\R2018b\\bin;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\120\\DTS\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\Git\\cmd;C:\\Users\\Radar\\AppData\\Local\\Microsoft\\WindowsApps"
```
This is the output related to Python, which it seems to have a conflict with the reticulate version
```
> sen2r:::init_python()
GDAL version in use: 2.4.1
ERROR: The requested version of Python ('C:\OSGEO4~1\bin\python.exe') cannot be used, as another version of Python
('C:/Users/Radar/AppData/Local/r-miniconda/envs/r-reticulate/python.exe') has already been initialized. Please restart the R session
if you need to attach reticulate to a different version of Python.
Error in use_python(binpaths$python, required = TRUE) : 
  failed to initialize requested version of Python
```
Thanks, 
Walter

**Comment by ranghetti** [comment]
Hi, this is an issue related to package **reticulate**, not to **sen2r**: you should avoid setting miniconda to be used. Have a look to https://stackoverflow.com/questions/50145643/unable-to-change-python-path-in-reticulate-r or to similar issues.

**Comment by ranghetti** [comment]
(Nevertheless, in the future I will update the package to avoid this conflict. This is an improvement which requires some time to be implemented, so in the meanwhile you should solve the problem changing the settings of **reticulate** Python version. I leave this issue open as a reminder to do this change.)

**Comment by lbusett** [comment]
@WalterCh I wonder if this can be fixed /alleviated by installing /loading the library from a fresh R/rstudio session, before loading any other packages that may use `reticulate`. Would you be able to test?

**Comment by WalterCh** [comment]
@lbusett I've tried this and I get the same error, I guess is because it's not about reticulate being attach to the session (which was not the case), is about a directory conflict.

**Comment by lbusett** [comment]
I see.... Could you try, in a fresh session: 

```r
Sys.setenv(RETICULATE_PYTHON = "C:/OSGEO4~1/bin/")
sen2r:::init_python()
```

**Comment by WalterCh** [comment]
Ok, now it works sen2r(), just because reticulate no longer uses the miniconda python, and therefore reticulate no longer works (I don't use it anyway, so far...)
```
> sen2r:::init_python()
GDAL version in use: 2.4.1
$py
Module(__builtin__)

$os
Module(os)

$sys
Module(sys)

$subprocess
Module(subprocess)

$re
Module(re)

$numpy
Module(numpy)

$urllib
Module(urllib)

$zipfile
Module(zipfile)

$gdal
Module(gdal)

$osr
Module(osr)

Warning messages:
1: In system2(command = python, args = paste0("\"", config_script,  :
  running command '"C:/OSGeo4W64/bin/python.exe" "C:/Users/Radar/Documents/R/win-library/3.6/reticulate/config/config.py"' had status 1
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
3: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
```
```
> reticulate::py_config()
Error in python_config(python_version, required_module, python_version,  : 
  Error 1 occurred running C:/OSGeo4W64/bin/python.exe 
In addition: Warning message:
In system2(command = python, args = paste0("\"", config_script,  :
  running command '"C:/OSGeo4W64/bin/python.exe" "C:/Users/Radar/Documents/R/win-library/3.6/reticulate/config/config.py"' had status 1
```

**Comment by lbusett** [comment]
Difficult to debug...   ;-)

Out of curiosity, what do you get from: 

``` r
reticulate::py_discover_config(required_module = "gdal")
```

If possible, both on a "session" where you set  "RETICULATE_PYTHON" and on a session where you do not set it ? 

and from: 

``` r 
file.exists("C:/OSGeo4W64/bin/python.exe")
file.exists("C:/OSGEO4~1/bin/python.exe")
```

**Comment by WalterCh** [comment]
```
> reticulate::py_discover_config(required_module = "gdal")
python:         C:/Users/Radar/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/Radar/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/Radar/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/Radar/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.18.1
```
```
> reticulate::py_discover_config(required_module = "gdal")
python:         C:/OSGeo4W64/bin/python.exe
libpython:      C:/OSGeo4W64/bin/python27.dll
pythonhome:     C:/OSGeo4W64/apps/Python27
version:        2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/OSGeo4W64/apps/Python27/Lib/site-packages/numpy
numpy_version:  1.16.5
gdal:           C:\OSGEO4~1\apps\Python27\lib\site-packages\gdal.py

NOTE: Python version was forced by RETICULATE_PYTHON
```
```
> file.exists("C:/OSGeo4W64/bin/python.exe")
[1] TRUE
```
```
> file.exists("C:/OSGEO4~1/bin/python.exe")
[1] TRUE
```

**Comment by lbusett** [comment]
ok. So, I guess this error you get when you "force"  RETICULATE_PYTHON:

> reticulate::py_config()
Error in python_config(python_version, required_module, python_version,  : 
  Error 1 occurred running C:/OSGeo4W64/bin/python.exe 
In addition: Warning message:
In system2(command = python, args = paste0("\"", config_script,  :
  running command '"C:/OSGeo4W64/bin/python.exe" "C:/Users/Radar/Documents/R/win-library/3.6/reticulate/config/config.py"' had status 1

apparetly comes from the fact that reticulate is somehow "mixing" a 2.7 with a 3.6 installation. 

As a further test, could you try to manually  remove all entries whic refer to "r-reticulate" from your Windows PATH ? (If you do not know how to do it tell me).

**Comment by WalterCh** [comment]
Fine, pls tell me how

**Comment by lbusett** [comment]
@WalterCh 
 
    sorry for the late reply. Since in the end @ranghetti decided to drop the reticulate dependency so to avoid thesse kind of problems, this should no longer apply on the next `sen2r()` version. I think that you could already test it by installing the current `devel` branch from github. 

  Lorenzo

**Comment by ranghetti** [comment]
Yes, **reticulate** is no longer a **sen2r** dependence, so your issue should be fixed.
Can you reinstall the last version from GitHub and let us know if processing run without problems?
```r
remotes::install_github("ranghetti/sen2r")
```

**Comment by CharlesNickmilder** [comment]
@WalterCh Do you launch Rstudio through Anaconda? I had similar issues and the solution from @ranghetti came simultaneously with my desinstallation of Anaconda. Thus I wonder if there may be a link between the bug and the use of Anaconda that implies the launch of another version of python. ;)

**Comment by WalterCh** [comment]
@CharlesNickmilder no, I lauch it from the desktop.
And @lbusett @ranghetti I will reinstall it, but I'm afraid that with the changes I dit to reticulate it will no longer work in the future.

**Comment by ranghetti** [comment]
> And @lbusett @ranghetti I will reinstall it, but I'm afraid that with the changes I dit to reticulate it will no longer work in the future.

I do not understand this sentence: are you referring to **sen2r** or **reticulate**? **sen2r** will work as well as before this change; to restore **reticulate** default settings, I think it would be sufficient to reinstall it.

**Comment by WalterCh** [comment]
Yes, I will reinstall both. Issue closed.

**Comment by ranghetti** [comment]
@WalterCh, when you will have reinstalled and re-run the code, please remember to let us know if the performed edits contributed to solve your issue (refer to the last note of the README: #186).
