### ISSUE TITLE
error in timewindow param as single integer value

### ISSUE THREAD

**Issue by VicenteYago** [ranghetti/sen2r#274]
Hi, 

here is my param json:

```{json}
{
  "preprocess": [true],
  "s2_levels": ["l1c", "l2a"],
  "sel_sensor": ["s2a", "s2b"],
  "online": [true],
  "order_lta": [true],
  "downloader": ["builtin"],
  "overwrite_safe": [true],
  "rm_safe": ["yes"],
  "max_cloud_safe": [100],
  "step_atmcorr": ["l2a"],
  "sen2cor_use_dem": [null],
  "sen2cor_gipp": [null],
  "timewindow": [5],
  "timeperiod": ["full"],
  "extent": ["./tmp/5e38431dcff41014f876cc547c251caea81e.geojson"],
  "s2tiles_selected": [null],
  "s2orbits_selected": [null],
  "list_prods": [null],
  "list_indices": ["NDMI", "NDVI", "NDWI", "NBR", "SAVI", "EVI"],
  "list_rgb": ["RGB432B"],
  "rgb_ranges": [[0, 2500]],
  "index_source": ["BOA"],
  "mask_type": [null],
  "max_mask": [80],
  "mask_smooth": [0],
  "mask_buffer": [0],
  "clip_on_extent": [true],
  "extent_as_mask": [true],
  "extent_name": ["bruh"],
  "reference_path": [null],
  "res": [null],
  "res_s2": ["10m"],
  "unit": ["Meter"],
  "proj": [null],
  "resampling": ["near"],
  "resampling_scl": ["near"],
  "outformat": ["GTiff"],
  "rgb_outformat": ["GTiff"],
  "index_datatype": ["Float32"],
  "compression": ["DEFLATE"],
  "rgb_compression": ["DEFLATE"],
  "overwrite": [false],
  "path_l1c": ["./l1c"],
  "path_l2a": ["./l2a"],
  "path_tiles": [null],
  "path_merged": [null],
  "path_out": ["./out"],
  "path_rgb": [""],
  "path_indices": ["./indices"],
  "path_subdirs": [true],
  "thumbnails": [true],
  "log": ["./log"],
  "parallel": [false],
  "processing_order": ["by_groups"],
  "pkg_version": ["1.3.0"]
} 
```
and my geojson file or `extent` : 

```{geojson}
{"type":"FeatureCollection","features":[{"type":"Feature","id":0,"properties":{"dummy":0},"geometry":{"type":"Polygon","coordinates":[[[-1.4436,38.0653],[-1.4414,38.064],[-1.4402,38.0631],[-1.4392,38.0613],[-1.4398,38.0579],[-1.4407,38.0553],[-1.4444,38.0567],[-1.4447,38.0585],[-1.4427,38.0598],[-1.4431,38.0617],[-1.4449,38.062],[-1.4468,38.0647],[-1.4436,38.0653]]]}}]}
```

when i run `sen2r(param_list = myfile)` i obtain the following error:

`
[2020-02-06 22:02:35] ####  Starting sen2r execution.  ####
[2020-02-06 22:02:36] Searching for available SAFE products on SciHub...
[2020-02-06 22:02:40] No SAFE products matching the settings were found.
╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════
║ sen2r Processing Report
╟─────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error in !attr(s2names, "paths_istemp")[names(s2names$exp)] : 
  invalid argument type
`
i find the problem is in the `timewindow` param wich is 5, when i switch it to 6 all works fine. 
Doing some experiments i find that the same error occurs when the `timewindow` is 1,2,3, or 4

some days ago this json file works good !, so i fear the error its due to some actualization or by the following:

the time resolution of sentinel2 is 5 days as you know, It could be that just the last image taken was 5 days ago, and that sen2r therefore did not find an image to download in that range and therefore fails.

Thank you!

**Comment by ranghetti** [comment]
Hi,
yes, this was a recent bug fixed with commit 877d4f8fc78b00c9cc41ed467d369b0ec115375c .
Today I am planning to release a new version which include that fix. If you want to test it now, you can install the develop version (actually the RC for new version) with
```r
remotes::install_github("ranghetti/sen2r", ref = "devel")
```

**Comment by ranghetti** [comment]
The new version is on CRAN, you can reinstall it using 
```r
install.packages("sen2r", type = "source")
```
Let me know if you will get your problem solved,

**Comment by VicenteYago** [comment]
I confirm its fixed :100:
