### ISSUE TITLE
Extent with multiple tiles

### ISSUE THREAD

**Issue by ranghetti** [ranghetti/sen2r#277]
_Question received by email_
> in case the required spatial extent contains several Sentinel-2 images, will the sen2r() command work with the size of the shp of the concerned area (extent = "path to file")?
If yes:
Shall the clip_on_extent argument be set to TRUE or FALSE?

**Comment by ranghetti** [comment]
Dear Gergo,
in case an area of interest (AOI) is covered by multiple tiles, all the tiles required to cover the AOI are downloaded and merged, even if they are not explicited by the argument `s2tiles_selected`. Passing tile names explicitly is useful to consider a subset of them (this is useful e.g. to exclude tiles which only cover a negligible portion of the AOI).

The behaviour of argument `clip_on_extent` is the same for AOI covered by a single tile / by multiple tiles: 
- with `clip_on_extent = TRUE`, outputs are clipped on the extent of the AOI;
- with `clip_on_extent = FALSE`, outputs cover the whole extent of the considered tiles (in case of an AOI covered by a single tile, the extent of that tile).

Did I interpret your question correctly?

**Comment by DijoG** [comment]
Dear Luigi,

yes, this automatized merging of tiles and clipping to AOI is really helpful!
Issue can be considered as closed.

Thank you!
