### ISSUE TITLE
The value of index

### ISSUE THREAD

**Issue by Fay07** [ranghetti/sen2r#279]
Hi, 

I tried to download EVI, EVI2, NDFI, NDFI2, and NDVI for a small area. But I found that the values are all very large (e.g., -126948). Is there anything wrong with the product? Or, I have to multiply by a scale factor (0.0001)?

**Comment by Fay07** [comment]
My code is as follow. Thanks. 

aoi <-st_as_sfc(st_bbox(c(xmin = -121.87, xmax = -121.57, ymin = 39.26, ymax = 39.38), crs = st_crs(4326)))

sen2r(
  gui = FALSE,
  s2_levels = "l2a",
  timewindow = c(as.Date("2019-01-01"), as.Date("2019-12-31")),
  extent = aoi, extent_name = "Myextent",
  list_prods = c("BOA"),
  list_indices = c("EVI","EVI2","NDVI","NDFI","NDFI2"),
  mask_type = "cloud_and_shadow",
  extent_as_mask = FALSE,
  path_l1c = "~/SAFE", path_l2a = "~/SAFE", path_out = "~/sen2rtest/out1"
)

**Comment by ranghetti** [comment]
Hi, see #264.
