### ISSUE TITLE
Pixels losts in .tif images

### ISSUE THREAD

**Issue by VicenteYago** [ranghetti/sen2r#281]
Hi, 
im testing the package over a region full of plastic greenhouses, there are a lot of saturated white pixels due to the natural color of the greenhouses. This is one example in RGB color, (calculated with `sen2r`) :

![S2B2A_20200215_051_5e45239868207b0a8d7cc718_RGB432B_10](https://user-images.githubusercontent.com/16523144/75092098-e7b22300-5574-11ea-91f2-010476eaabc4.png)

The problem arise in vegetation indexes, for example NDVI, the following its an QGIS screenshot of the output file generated directly from `sen2r`:

![Screenshot from 2020-02-22 13-19-12](https://user-images.githubusercontent.com/16523144/75092262-3a400f00-5576-11ea-94c1-689ba56a1ba7.png)
2942ce00-5575-11ea-91be-05bc4fa6253c.png)

There are many holes which are filled with the background color (in this case black but usually its white or alpha transparent), at first i though it was the problem of my code (im using `gdaldem` from `gdalUtils` library).

> NDVI

![S2B2A_20200215_051_5e45239868207b0a8d7cc718_NDVI_10](https://user-images.githubusercontent.com/16523144/75092302-8db25d00-5576-11ea-9f2c-d9f9a7cde7e9.png)

> NDWI:

![S2B2A_20200215_051_5e45239868207b0a8d7cc718_NDWI_10](https://user-images.githubusercontent.com/16523144/75092484-3f05c280-5578-11ea-8c01-f5ef8e1b43ff.png)

```{r}
  gdaldem(mode = "color-relief",
          input_dem = file,
          output = file,
          b = 1,
          alpha = T,
          nearest_color_entry = T,
          color_text_file = colorfile)
```

QGIS shows the same problem, so i think the problem may be in the construction of the image, related to `sen2r `or my ingorance in configuration file setting :) .

My configuration file its the following:

```{r}
{
  "preprocess": [true],
  "s2_levels": ["l1c", "l2a"],
  "sel_sensor": ["s2a", "s2b"],
  "online": [true],
    "order_lta": [true],
    "downloader": ["builtin"],
  "overwrite_safe": [true],
  "rm_safe": ["no"],
  "max_cloud_safe": [30],
  "step_atmcorr": ["l2a"],
  "sen2cor_use_dem": [null],
  "sen2cor_gipp": [null],
  "timewindow": [null],
  "timeperiod": ["full"],
  "extent": [null],
  "s2tiles_selected": [null],
  "s2orbits_selected": [null],
  "list_prods": [null],
  "list_indices": ["NDMI", "NDVI", "NDWI", "NBR", "SAVI", "EVI"],
  "list_rgb": ["RGB432B"],
  "rgb_ranges": [[0, 2500]],
  "index_source": ["BOA"],
  "mask_type": ["scl_0_8_9_11"],
  "max_mask": [20],
  "mask_smooth": [0],
  "mask_buffer": [0],
  "clip_on_extent": [true],
  "extent_as_mask": [true],
  "extent_name": [null],
  "reference_path": [null],
  "res": [null],
  "res_s2": ["10m"],
  "unit": ["Meter"],
  "proj": [null],
  "resampling": ["near"],
  "resampling_scl": ["near"],
  "outformat": ["GTiff"],
  "rgb_outformat": ["GTiff"],
  "index_datatype": ["Float32"],
  "compression": ["DEFLATE"],
  "rgb_compression": ["DEFLATE"],
  "overwrite": [false],
  "path_l1c": ["./l1c"],
  "path_l2a": ["./l2a"],
  "path_tiles": [null],
  "path_merged": [null],
  "path_out": ["./out"],
  "path_rgb": [""],
  "path_indices": ["./indices"],
  "path_subdirs": [true],
  "thumbnails": [false],
  "log": ["./log"],
  "parallel": [true],
  "processing_order": ["by_groups"],
  "pkg_version": ["1.3.0"]
} 
```
i refill the config file with the `extent` and `timewindow`

Thanks!

UPDATE:

Here is the .tif file as is generated by sen2r function :
https://gofile.io/?c=gdl343

**Comment by ranghetti** [comment]
Hi,
missing area were masked according to the used `mask_type` argument value. Producing also the SCL can help deepening this issue:
![S2B2A_20200215_051_5e45239868207b0a8d7cc718_SCL_10](https://user-images.githubusercontent.com/6874239/75134024-498d9c80-56dd-11ea-9c18-2e43621dce7b.png)
([here](https://earth.esa.int/web/sentinel/technical-guides/sentinel-2-msi/level-2a/algorithm) the legend).

There is nothing to do in case of mismatching SCL classification (this is an output of Sen2Cor, not sen2r). In case of a high number of misclassificated pixels, I would suggest to skip cloud masking.

Ps. I retrieved `time_window` and `extent` from the filename and the bounding box of the GeoTIFF you uploaded next time, please ensure to attach a reproducible example (the README #186 must be read before opening new issues).
