### ISSUE TITLE
Retrieval of offline S-2 products with sen2r()

### ISSUE THREAD

**Issue by Leprechault** [ranghetti/sen2r#283]
Please, I've like to know when the S-2 products will be online before `Ordering 1 Sentinel-2 image stored in the Long Term Archive` with `sen2r()` function? In my code:

```

[2020-02-26 22:33:09] #### Starting sen2r execution. ####
[2020-02-26 22:33:10] Searching for available SAFE products on SciHub...
[2020-02-26 22:33:17] Ordering 1 Sentinel-2 images stored in the Long Term
       Archive...
[2020-02-26 22:33:18] 1 of 1 Sentinel-2 images were correctly ordered.
+--------------------------------------------------------------------------
¦ sen2r Processing Report
¦--------------------------------------------------------------------------
¦ Dates to be processed based on processing parameters: 1
¦ Processing completed for: 0 out of 1 expected dates.
¦ Outputs for: 1 out of 1 expected dates not created because all/some
¦ required images are currently offline.
¦ Order for: 1 out of 1 offline images successfull.
¦ You can check later if the ordered images are online with the command:
¦   safe_is_online("C:/Users/fores/Documents/.sen2r/lta_orders/lta_20200226_223318.json")
¦ When additional images are online, you can relaunch the processing chain
¦ using the command:
¦   sen2r("C:/Users/fores/Documents/.sen2r/proc_par/s2proc_20200226_223309.json")
+--------------------------------------------------------------------------
[2020-02-26 22:33:18] #### sen2r session terminated. ####
```
But despite the `[2020-02-26 22:33:18] 1 of 1 Sentinel-2 images were correctly ordered.` message, when I try to check the availability the output is:

```
safe_is_online("C:/Users/fores/Documents/.sen2r/lta_orders/lta_20200226_223318.json")
0 out of 1 products are online.
S2A_MSIL1C_20170706T140051_N0205_R067_T21LVC_20170706T140051.SAFE 
                                                            FALSE
```

**Comment by ranghetti** [comment]
This is a question related to ESA policy, not to sen2r; you can find the answer here:
https://scihub.copernicus.eu/userguide/LongTermArchive

> Access to the product URL for data that are no longer available online will automatically trigger the retrieval from the LTA. The actual download can be initiated by the user once the data are restored (within 24 hours).
A user quota on the maximum number of requests per hour per user is set.
Products restored from the long term archives are kept online for a period of at least 3 days. Quota and keeping time will be fine tuned according to the usage patterns to ensure efficient access to the most recent and frequently downloaded data.
