### ISSUE TITLE
Re-open: Retrieval of offline S-2 products with sen2r()

### ISSUE THREAD

**Issue by Leprechault** [ranghetti/sen2r#284]
I re-open this issue again because I reading before my answer the topic (https://scihub.copernicus.eu/userguide/LongTermArchive), but I've like to know if the `Ordering 1 Sentinel-2 image stored in the Long Term Archive` with `sen2r()` will be considered by (https://scihub.copernicus.eu), because when I go to my profile in the (https://scihub.copernicus.eu) my `User's Cart` is empty despite the `Ordering 1 Sentinel-2 image stored in the Long Term Archive` message in R and the use the same credentials in `read_scihub_login()` function and in my profile in (https://scihub.copernicus.eu).

**Comment by ranghetti** [comment]
[this continues from #383]

Ok, this was not clear from previous question ;)
By default, sen2r functions makes use of **apihub** protocol (https://scihub.copernicus.eu/twiki/do/view/SciHubWebPortal/APIHubDescription) instead than **dhus** (which is used by [Open Hub](https://scihub.copernicus.eu/dhus)).

To use **dhus** protocol, set `service = "dhus"` in function `s2_order()`.

Anyway, notice that the ordered product will not be moved to the Open Hub cart: this is an operation made by the interface after ordering the product, which (for what I know) can not be reproduced using API. In any case, if the product is in the output of `s2_order()` and not in its attribute `"notordered"` (see the [function reference](https://sen2r.ranghetti.info/reference/s2_order) if this is not clear), the order was made.

Ps. in future, if you need to repoen a closed issue to continue with _the same_ topic, you can simply reopen that issue, without the needing to open a new one.

**Comment by Leprechault** [comment]
Thank you very much Ranghetti for your explanation and sorry about my first unclear question and badly reopen a closed issue. I will be more careful in next posts.
