### ISSUE TITLE
sen2cor(): L1C content got deleted

### ISSUE THREAD

**Issue by DorHe** [ranghetti/sen2r#288]
For any reason it did not process when temp_dir and out_dir was provided.
Hence, I changed tmpdir and outdir to the input l1c_dir.
As a consequence, all downloaded L1C files got deleted.
This has not been the case for a single file in another orbit.

sen2cor(names(orb22_s2_list), 
        l1c_dir = ("e:.../L1C/Orbit_022/"), # all has to be in one folder - reported bug
        tmpdir = ("e:.../L1C/Orbit_022"), 
        outdir = ("e:.../L1C/Orbit_022"),
        use_dem = TRUE,
        parallel = TRUE)

**Comment by ranghetti** [comment]
Sorry, I do not understand what you have written: please better define the problem. But before doing that, carefully read the README (#186) and provide the missing information (system information, reproducible example, ...).

In any case, do not use the same value for `tmpdir` and `outdir`/`l1c_dir` (I will add a check to prevent users doing that).

**Comment by DorHe** [comment]
Thanks for your help

:: Deletion: one orbit only gave me one scene. Here downloading and processing worked finely (Example on Orbit 122). The other orbit gave me ~6 scenes. Here it got stucked with the first processing from L1C to L2A. 

Sry, hope this helps.

# Orbit 122
orb122_s2_list <- s2_list(spatial_extent=pos, 
                              tile="32TQT", level = "L1C", orbit = "122",
                              max_cloud = 20, 
                              time_interval = time_window, time_period = "seasonal",
                              availability = "online")

sen2cor(names(orb122_s2_list), 
        l1c_dir = ("e:/.../L1C/Orbit_122/"), # all has to be in one folder - reported bug
        tmpdir = ("e:/.../L1C/Orbit_122/"), 
        outdir = ("e:/.../L2C/Orbit_122/"),
        use_dem = TRUE)

**Comment by DorHe** [comment]
Good morning and sorry for the inconvenience,




In any case, do not use the same value for tmpdir and outdir/l1c_dir (I will add a check to prevent users doing that).
This might have caused the problem?!



here the info ab the system etc.

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] sf_0.8-1    shiny_1.4.0 sen2r_1.3.2

loaded via a namespace (and not attached):
[1] Rcpp_1.0.3           lattice_0.20-38      class_7.3-15         shinyWidgets_0.5.0   digest_0.6.25
 [6] foreach_1.4.8        V8_3.0.1             mime_0.9             R6_2.4.1             sys_3.3
[11] leaflet.extras_1.0.0 e1071_1.7-3          httr_1.4.1           geojson_0.3.2        pillar_1.4.3
[16] rlang_0.4.4          geojsonlint_0.4.0    lazyeval_0.2.2       curl_4.3             rstudioapi_0.11
[21] data.table_1.12.8    raster_3.0-12        geojsonio_0.9.0      shinyjs_1.1          jqr_1.1.0
[26] foreign_0.8-75       htmlwidgets_1.5.1    munsell_0.5.0        compiler_3.6.0       httpuv_1.5.2
[31] pkgconfig_2.0.3      rgeos_0.5-2          htmltools_0.4.0      mapedit_0.6.0        tibble_2.1.3
[36] httpcode_0.2.0       codetools_0.2-16     XML_3.99-0.3         jsonvalidate_1.1.0   crayon_1.3.4
[41] later_1.0.0          crul_0.9.0           grid_3.6.0           lwgeom_0.2-1         jsonlite_1.6.1
[46] xtable_1.8-4         lifecycle_0.1.0      DBI_1.1.0            magrittr_1.5         units_0.6-5
[51] scales_1.1.0         KernSmooth_2.23-16   stringi_1.4.6        fs_1.3.1             promises_1.1.0
[56] leaflet_2.0.3        doParallel_1.0.15    sp_1.4-1             xml2_1.2.2           shinyFiles_0.7.5
[61] iterators_1.0.12     tools_3.6.0          crosstalk_1.0.0      rsconnect_0.8.16     yaml_2.2.1
[66] abind_1.4-5          parallel_3.6.0       fastmap_1.0.1        colorspace_1.4-1     stars_0.4-0
[71] maptools_0.9-9       shinydashboard_0.7.1 classInt_0.4-2
> packageVersion("sen2r")
[1] ‘1.3.2’



Kind regards,
Doris


Doris Hermle
M.Sc.

----------------------------------------------------------
Stipendiatin Hanns-Seidel-Stiftung e.V.
Landslide Research Group
Technical University of Munich
Arcisstr. 21, D-80333 München, Germany
Room N2609A
Tel: +49 (0)89 289 25896
e-Mail: doris.hermle@tum.de<mailto:doris.hermle@tum.de>

https://www.bgu.tum.de/landslides/staff/phd-students/doris-hermle/
http://www.landslides.geo.tum.de/news/
https://www.researchgate.net/profile/Doris_Hermle


Von: Luigi Ranghetti [mailto:notifications@github.com]
Gesendet: Dienstag, 3. März 2020 16:56
An: ranghetti/sen2r <sen2r@noreply.github.com>
Cc: Hermle, Doris <doris.hermle@tum.de>; Author <author@noreply.github.com>
Betreff: Re: [ranghetti/sen2r] sen2cor(): L1C content got deleted (#288)


Sorry, I do not understand what you have written: please better define the problem. But before doing that, carefully read the README (#186<https://github.com/ranghetti/sen2r/issues/186>) and provide the missing information (system information, reproducible example, ...).

In any case, do not use the same value for tmpdir and outdir/l1c_dir (I will add a check to prevent users doing that).

**Comment by ranghetti** [comment]
Try using:
```r
sen2cor(
  names(orb122_s2_list),
  l1c_dir = ("e:/.../L1C/Orbit_122/"),
  tmpdir = ("e:/.../L1C/Orbit_122/tempdir"),
  outdir = ("e:/.../L2C/Orbit_122/"),
  rmtmp = FALSE,
  use_dem = TRUE
)
```

If this will not solve, I will need a reproducible example to deepen the problem:
- `spatial_extent=pos`: what is `pos`? If it is a spatial file, load it; if it a bounding box, post it;
- `time_interval = time_window`: what is `time_window`?

Moreover, from the README:

> If you are re-launching a processing chain which you already used (i.e. if your output folders are not empty), report also the content of these directories.

In your case, report the content of `"e:/.../L1C/Orbit_122/"`.

> Report the output produced by the function which is producing an error

In your case, report the output of `sen2cor(...)`.

**Comment by DorHe** [comment]
Buongiorno e grazie per tua riposta veloce!

I did a workaround as I downloaded and processed in two steps.
Do you wish to reproduce it for finding the error?

Ciao
Doris

Doris Hermle
M.Sc.

----------------------------------------------------------
Stipendiatin Hanns-Seidel-Stiftung e.V.
Landslide Research Group
Technical University of Munich
Arcisstr. 21, D-80333 München, Germany
Room N2609A
Tel: +49 (0)89 289 25896
e-Mail: doris.hermle@tum.de<mailto:doris.hermle@tum.de>

https://www.bgu.tum.de/landslides/staff/phd-students/doris-hermle/
http://www.landslides.geo.tum.de/news/
https://www.researchgate.net/profile/Doris_Hermle


Von: Luigi Ranghetti [mailto:notifications@github.com]
Gesendet: Mittwoch, 4. März 2020 09:30
An: ranghetti/sen2r <sen2r@noreply.github.com>
Cc: Hermle, Doris <doris.hermle@tum.de>; Author <author@noreply.github.com>
Betreff: Re: [ranghetti/sen2r] sen2cor(): L1C content got deleted (#288)


Try using:

sen2cor(

  names(orb122_s2_list),

  l1c_dir = ("e:/.../L1C/Orbit_122/"),

  tmpdir = ("e:/.../L1C/Orbit_122/tempdir"),

  outdir = ("e:/.../L2C/Orbit_122/"),

  rmtmp = FALSE,

  use_dem = TRUE

)

If this will not solve, I will need a reproducible example to deepen the problem:

  *   spatial_extent=pos: what is pos? If it is a spatial file, load it; if it a bounding box, post it;
  *   time_interval = time_window: what is time_window?

Moreover, from the README:

If you are re-launching a processing chain which you already used (i.e. if your output folders are not empty), report also the content of these directories.

In your case, report the content of "e:/.../L1C/Orbit_122/".

Report the output produced by the function which is producing an error

In your case, report the output of sen2cor(...).

**Comment by ranghetti** [comment]
> Do you wish to reproduce it for finding the error?

If the command posted in the message below will work, I will not need to reproduce your code; otherwise yes, and I will need the required information for reproducing it.

**Comment by DorHe** [comment]
Recently after submitting the task, the L2A got written and stored in the l1c_dir
[cid:image003.png@01D5F210.CF066900]

Then after 20 min:


[2020-03-04 10:10:36] Launching Sen2Cor on S2A_MSIL1C_20150830T100016_N0204_R122_T32TQT_20150830T100547.SAFE
           (1/1)...
[2020-03-04 10:30:36] Running Sen2Cor on S2A_MSIL1C_20150830T100016_N0204_R122_T32TQT_20150830T100547.SAFE
           finished after 20 mins.
[1] "e:/01_Sattelkar/01_Sattelkar_satellite/Sentinel-2_Data/L2A/Orbit_122//S2A_MSIL2A_20150830T100016_N0204_R122_T32TQT_20150830T100547.SAFE"

The existing L2A is a temporary product I should delete or is this a proper corrected scene?!


sen2cor(
  names(orb122_s2_list),
  l1c_dir = ("e:/…/L1C/Orbit_122/"),
  tmpdir = ("e:/…/L1C/Orbit_122/TMP"),
  outdir = ("e:/…/L2A/Orbit_122/"),
  rmtmp = FALSE,
  use_dem = TRUE
)


pos <- st_sfc(st_point(c(12.28, 47.16)), crs=st_crs(4326))
time_window <- as.Date(c("2014-05-01","2019-10-01"))


Before I forget to mention – sen2cor is an amazing and great help for me, I am glad that I met you at LPS 2019.


Ciao
Doris


Doris Hermle
M.Sc.

----------------------------------------------------------
Stipendiatin Hanns-Seidel-Stiftung e.V.
Landslide Research Group
Technical University of Munich
Arcisstr. 21, D-80333 München, Germany
Room N2609A
Tel: +49 (0)89 289 25896
e-Mail: doris.hermle@tum.de<mailto:doris.hermle@tum.de>

https://www.bgu.tum.de/landslides/staff/phd-students/doris-hermle/
http://www.landslides.geo.tum.de/news/
https://www.researchgate.net/profile/Doris_Hermle


Von: Luigi Ranghetti [mailto:notifications@github.com]
Gesendet: Mittwoch, 4. März 2020 09:30
An: ranghetti/sen2r <sen2r@noreply.github.com>
Cc: Hermle, Doris <doris.hermle@tum.de>; Author <author@noreply.github.com>
Betreff: Re: [ranghetti/sen2r] sen2cor(): L1C content got deleted (#288)


Try using:

sen2cor(

  names(orb122_s2_list),

  l1c_dir = ("e:/.../L1C/Orbit_122/"),

  tmpdir = ("e:/.../L1C/Orbit_122/tempdir"),

  outdir = ("e:/.../L2C/Orbit_122/"),

  rmtmp = FALSE,

  use_dem = TRUE

)

If this will not solve, I will need a reproducible example to deepen the problem:

  *   spatial_extent=pos: what is pos? If it is a spatial file, load it; if it a bounding box, post it;
  *   time_interval = time_window: what is time_window?

Moreover, from the README:

If you are re-launching a processing chain which you already used (i.e. if your output folders are not empty), report also the content of these directories.

In your case, report the content of "e:/.../L1C/Orbit_122/".

Report the output produced by the function which is producing an error

In your case, report the output of sen2cor(...).

**Comment by ranghetti** [comment]
Thank you fo your appreciation.

> The existing L2A is a temporary product I should delete or is this a proper corrected scene?!

No, but, at the end of the function [`sen2cor()`](https://github.com/ranghetti/sen2r/blob/master/R/sen2cor.R) there is this instruction:
```r
  # Remove temporary directory
  if (rmtmp == TRUE & !is.na(tmpdir)) {
    unlink(tmpdir, recursive=TRUE)
  }
```

So, if you used the same value for `tmpdir` and `outdir`, the content of `outdir` would be removed. This is the reason why I will add a check to prevent users setting `tmpdir = outdir`.

Before reproducing the code, can you say me if the modified `sen2cor()` instruction (with the addition of `  tmpdir = ("e:/…/L1C/Orbit_122/TMP")` and `rmtmp = TRUE`) allowed you obtaining the L2A products?

**Comment by DorHe** [comment]
Ah, now I see what you meant that tmpdir should not be same as outdir.

Okay, both files in my TMP and L2A are the same.

What I provided you in the last mail has been the result of your code

> sen2cor(
+   names(orb122_s2_list),
+   l1c_dir = ("e:/01_Sattelkar/01_Sattelkar_satellite/Sentinel-2_Data/L1C/Orbit_122/"),
+   tmpdir = ("e:/01_Sattelkar/01_Sattelkar_satellite/Sentinel-2_Data/L1C/Orbit_122/TMP"),
+   outdir = ("e:/01_Sattelkar/01_Sattelkar_satellite/Sentinel-2_Data/L2A/Orbit_122/"),
+   rmtmp = FALSE,
+   use_dem = TRUE
+ )


Grazie mille,
saluti Doris

Doris Hermle
M.Sc.

----------------------------------------------------------
Stipendiatin Hanns-Seidel-Stiftung e.V.
Landslide Research Group
Technical University of Munich
Arcisstr. 21, D-80333 München, Germany
Room N2609A
Tel: +49 (0)89 289 25896
e-Mail: doris.hermle@tum.de<mailto:doris.hermle@tum.de>

https://www.bgu.tum.de/landslides/staff/phd-students/doris-hermle/
http://www.landslides.geo.tum.de/news/
https://www.researchgate.net/profile/Doris_Hermle


Von: Luigi Ranghetti [mailto:notifications@github.com]
Gesendet: Mittwoch, 4. März 2020 11:41
An: ranghetti/sen2r <sen2r@noreply.github.com>
Cc: Hermle, Doris <doris.hermle@tum.de>; Author <author@noreply.github.com>
Betreff: Re: [ranghetti/sen2r] sen2cor(): L1C content got deleted (#288)


Thank you fo your appreciation.

The existing L2A is a temporary product I should delete or is this a proper corrected scene?!

No, but, at the end of the function sen2cor()<https://github.com/ranghetti/sen2r/blob/master/R/sen2cor.R> there is this instruction:

  # Remove temporary directory



  if (rmtmp == TRUE & !is.na(tmpdir)) {



    unlink(tmpdir, recursive=TRUE)



  }

So, if you used the same value for tmpdir and outdir, the content of outdir would be removed. This is the reason why I will add a check to prevent users setting tmpdir = outdir.

Before reproducing the code, can you say me if the modified sen2cor() instruction (with the addition of tmpdir = ("e:/…/L1C/Orbit_122/TMP") and rmtmp = TRUE) allowed you obtaining the L2A products?

**Comment by ranghetti** [comment]
Ok, but I have not yet understood if you solved your problem using the modified `sen2cor()` instruction (with the addition of `  tmpdir = ("e:/…/L1C/Orbit_122/TMP")` and `rmtmp = TRUE`). In other words: have you obtained the desired L2A products? Can you find them in `outdir`, or they got deleted again? This can not be extrapolated from the output of the code, and I do not undestand your sentence ("Okay, both files in my TMP and L2A are the same.": the same what? Empty directories? A duplicate od the output products?).
I hope I have been clear, this time.

**Comment by DorHe** [comment]
Hi!

Oh, did you not get the screenshots I pasted into the mail? Sorry!

Yes, everything is fine, thank you!
Well, it first wrote the L2A into the tmpdir = ("e:/…/L1C/Orbit_122/TMP"
Then ~20 min later the same L2A was also in outdir = ("e:/…/L2A/Orbit_122/") which is why I asked whether they are the same.

Thank you for asking!

[2020-03-04 10:10:36] Launching Sen2Cor on S2A_MSIL1C_20150830T100016_N0204_R122_T32TQT_20150830T100547.SAFE
           (1/1)...
[2020-03-04 10:30:36] Running Sen2Cor on S2A_MSIL1C_20150830T100016_N0204_R122_T32TQT_20150830T100547.SAFE
           finished after 20 mins.
[1] "e:/01_Sattelkar/01_Sattelkar_satellite/Sentinel-2_Data/L2A/Orbit_122//S2A_MSIL2A_20150830T100016_N0204_R122_T32TQT_20150830T100547.SAFE"


Doris Hermle
M.Sc.

----------------------------------------------------------
Stipendiatin Hanns-Seidel-Stiftung e.V.
Landslide Research Group
Technical University of Munich
Arcisstr. 21, D-80333 München, Germany
Room N2609A
Tel: +49 (0)89 289 25896
e-Mail: doris.hermle@tum.de<mailto:doris.hermle@tum.de>

https://www.bgu.tum.de/landslides/staff/phd-students/doris-hermle/
http://www.landslides.geo.tum.de/news/
https://www.researchgate.net/profile/Doris_Hermle


Von: Luigi Ranghetti [mailto:notifications@github.com]
Gesendet: Mittwoch, 4. März 2020 13:58
An: ranghetti/sen2r <sen2r@noreply.github.com>
Cc: Hermle, Doris <doris.hermle@tum.de>; Author <author@noreply.github.com>
Betreff: Re: [ranghetti/sen2r] sen2cor(): L1C content got deleted (#288)


Ok, but I have not yet understood if you solved your problem using the modified sen2cor() instruction (with the addition of tmpdir = ("e:/…/L1C/Orbit_122/TMP") and rmtmp = TRUE). In other words: have you obtained the desired L2A products? Can you find them in outdir, or they got deleted again? This can not be extrapolated from the output of the code, and I do not undestand your sentence ("Okay, both files in my TMP and L2A are the same.": the same what? Empty directories? A duplicate od the output products?).
I hope I have been clear, this time.

**Comment by ranghetti** [comment]
> Oh, did you not get the screenshots I pasted into the mail? Sorry!

No, because you are not sending emails, you are writing on GitHub ;) (if you answer to a Github notification, your answer is added as message in the GitHub issue; but attachments are lost).

This is what is happening: the L2A SAFE folder is created in `tmpdir`, then Sen2Cor produces the output (this operation is 20 minutes long, in your case). At the end, the SAFE is copied from `tmpdir` to `outdir`.
If this process is going well, you can try skipping `rmtmp = FALSE`: this will avoid duplicating the output.
