### ISSUE TITLE
Problem installing runtime dependencies

### ISSUE THREAD

**Issue by ranghetti** [ranghetti/sen2r#291]
_Issue received by email._

I am contacting you because I installed your sen2r package in order to download sentinel-2 images but it does not work ! In fact, I am missing (at least!) the dependent sen2cor package which I cannot install at all. (cf. below). I also cannot launch the function  `check_sen2r_deps()`

If possible, I would like you to help me properly install sen2r with the packages necessary for it to work properly.

Thank you in advance for your response.

Operating system : Windows 8.1 (64 bits)
Software : R version 3.6.3
                R Studio v. 1.2.5033
THE PROBLEM :

```
> library(raster)
> library(sp)
> library(rgeos)
> library(rgdal)
> library(rjson)
> library(exactextractr)
> library(sf)
> library(data.table)
> library(sen2r)
Welcome to sen2r. To use the package from a GUI, launch
 > sen2r()
Documentation: http://sen2r.ranghetti.info

IMPORTANT: sen2r depends on some external tools;
before using it, it is strongly recommended to run function
 > check_sen2r_deps()
to check them and install the missing ones.
Erreur : package or namespace load failed for ‘sen2r’:
 .onAttach a échoué dans attachNamespace() pour 'sen2r', détails :
  appel : dir.exists(settings_dir)
  erreur : problème de conversion de nom de fichier -- nom trop long ?
> install.packages("sen2cor")
Installing package into ‘C:/Users/Loïc/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘sen2cor’ is not available (for R version 3.6.3)
```

**Comment by ranghetti** [comment]
>  I also cannot launch the function  `check_sen2r_deps()`

In order to understand the reason of this problem, you should report the error you received launching this command. Please also report the package version you are using (see the README at #186).

> ```
> install.packages("sen2cor")
> Installing package into ‘C:/Users/Loïc/Documents/R/win-library/3.6’
> (as ‘lib’ is unspecified)
> Warning in install.packages :
>   package ‘sen2cor’ is not available (for R version 3.6.3)
> ```

This because Sen2Cor is a runtime dependencies, not an R package (see [this vignette](https://sen2r.ranghetti.info/articles/installation.html)).

By the way, you can install Sen2Cor also using the function [`install_sen2cor()`](https://sen2r.ranghetti.info/reference/install_sen2cor.html).

Let me know,

**Comment by lovalery** [comment]
Thank you very much for your response and sorry for not submitting my request directly to you via github.

You will find below the different procedures that you asked me. At the moment I still can't get sen2r to work and the command you gave me to install sen2cor doesn't work either (maybe I made a syntax error?)

Thank you in advance for your help.
Loïc

> setwd("D:\\Mastère spécialisé SILAT\\Projet_groupe_commandite")
> library(sp)
> library(raster)
> library(rgeos)
> library(rgdal)
> library(rjson)
> library(jqr)
> library(exactextractr)
> library(sf)
> library(V8)
> library(ncdf4)
> library(protolite)
> library(Cairo)
> library(gdtools)
> library(XML)
> library(openssl)
> library(sen2r)
Welcome to sen2r. To use the package from a GUI, launch
 > sen2r()
Documentation: http://sen2r.ranghetti.info

IMPORTANT: sen2r depends on some external tools;
before using it, it is strongly recommended to run function
 > check_sen2r_deps()
to check them and install the missing ones.
Erreur : package or namespace load failed for ‘sen2r’:
 .onAttach a échoué dans attachNamespace() pour 'sen2r', détails :
  appel : dir.exists(settings_dir)
  erreur : problème de conversion de nom de fichier -- nom trop long ?
> sen2r()
Error in sen2r() : impossible de trouver la fonction "sen2r"
> check_sen2r_deps()
Error in check_sen2r_deps() : 
  impossible de trouver la fonction "check_sen2r_deps"
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] openssl_1.4.1       XML_3.99-0.3        gdtools_0.2.1       Cairo_1.5-11        jqr_1.1.0           protolite_2.1       ncdf4_1.17         
 [8] V8_3.0.1            sf_0.8-1            exactextractr_0.2.0 rjson_0.2.20        rgdal_1.4-8         rgeos_0.5-2         raster_3.0-12      
[15] sp_1.4-1           

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3           lattice_0.20-38      class_7.3-15         shinyWidgets_0.5.1   digest_0.6.25        foreach_1.4.8       
 [7] mime_0.9             R6_2.4.1             leaflet.extras_1.0.0 e1071_1.7-3          httr_1.4.1           geojson_0.3.2       
[13] pillar_1.4.3         rlang_0.4.5          lazyeval_0.2.2       curl_4.3             rstudioapi_0.11      data.table_1.12.8   
[19] geojsonio_0.9.0      sen2r_1.3.2          shinyjs_1.1          foreign_0.8-75       htmlwidgets_1.5.1    munsell_0.5.0       
[25] shiny_1.4.0.1        compiler_3.6.3       httpuv_1.5.2         pkgconfig_2.0.3      askpass_1.1          systemfonts_0.1.1   
[31] htmltools_0.4.0      mapedit_0.6.0        tibble_2.1.3         httpcode_0.2.0       codetools_0.2-16     crayon_1.3.4        
[37] later_1.0.0          crul_0.9.0           grid_3.6.3           lwgeom_0.2-1         jsonlite_1.6.1       xtable_1.8-4        
[43] lifecycle_0.2.0      DBI_1.1.0            magrittr_1.5         units_0.6-5          scales_1.1.0         KernSmooth_2.23-16  
[49] fs_1.3.2             promises_1.1.0       leaflet_2.0.3        doParallel_1.0.15    shinyFiles_0.7.5     iterators_1.0.12    
[55] tools_3.6.3          crosstalk_1.0.0      abind_1.4-5          parallel_3.6.3       fastmap_1.0.1        colorspace_1.4-1    
[61] stars_0.4-0          maptools_0.9-9       shinydashboard_0.7.1 classInt_0.4-2      
> packageVersion("sen2r")
[1] ‘1.3.2’
> sen2r::load_binpaths()
list()
attr(,"path")
[1] "C:\\Users\\LOC~1\\AppData\\Local\\Temp\\RtmpeKZxYn/paths.json"
> install_sen2cor(sen2cor_dir = "C:\\Users\\Loïc\\Documents\\R", version = "2.8.0", force = FALSE)
Error in install_sen2cor(sen2cor_dir = "C:\\Users\\Loïc\\Documents\\R",  : 
  impossible de trouver la fonction "install_sen2cor"

**Comment by ranghetti** [comment]
Can you run the following commands?
```r
normalizePath("~/.sen2r", mustWork = FALSE)
normalize_path("~/.sen2r", mustWork = FALSE)
.rs.listIndexedPackages()[grep("sen2r", .rs.listIndexedPackages())]
```

**Comment by lovalery** [comment]
Here are the results of the commands you asked me to execute :+1: 
> normalizePath("~/.sen2r", mustWork = FALSE)
[1] "C:\\Users\\Loïc\\Documents\\.sen2r"
> normalize_path("~/.sen2r", mustWork = FALSE)
Error in normalize_path("~/.sen2r", mustWork = FALSE) : 
  impossible de trouver la fonction "normalize_path"
> .rs.listIndexedPackages()[grep("sen2r", .rs.listIndexedPackages())]
character(0)

**Comment by ranghetti** [comment]
Ok, the packages was not installed (I thought it was installed but errored when loaded).
Can you report me the messages returned during installation?
```r
remove.packages("sen2r")
install.packages("sen2r")
library(sen2r)
```

**Comment by lovalery** [comment]
Here are the results of the commands you asked me to execute (by the way, thank you very much for helping me solve this problem) :

> remove.packages("sen2r")
Removing package from ‘C:/Users/Loïc/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
> install.packages("sen2r")
Error in install.packages : Updating loaded packages

Restarting R session...

Error in gzfile(file, "wb") : impossible d'ouvrir la connexion
Error saving session (options): R code execution error
WARNING: Forcing suspend of process in spite of all session data not being fully saved.
> install.packages("sen2r")
Installing package into ‘C:/Users/Loïc/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
essai de l'URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/sen2r_1.3.2.zip'
Content type 'application/zip' length 2285650 bytes (2.2 MB)
downloaded 2.2 MB

package ‘sen2r’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Loïc\AppData\Local\Temp\RtmpgHD6yg\downloaded_packages
> library(sen2r)
Welcome to sen2r. To use the package from a GUI, launch
 > sen2r()
Documentation: http://sen2r.ranghetti.info

IMPORTANT: sen2r depends on some external tools;
before using it, it is strongly recommended to run function
 > check_sen2r_deps()
to check them and install the missing ones.
Erreur : package or namespace load failed for ‘sen2r’:
 .onAttach a échoué dans attachNamespace() pour 'sen2r', détails :
  appel : dir.exists(settings_dir)
  erreur : problème de conversion de nom de fichier -- nom trop long ?

**Comment by ranghetti** [comment]
I am sorry but I cannot understand the reason of this problem. `settings_dir` is `"C:\Users\Loïc\Documents\.sen2r"`, which is not a long file path.
The only think I can suggest is to delete that directory and restart R: when loading the package sen2r, you will have to answer "yes" (giving the permission to write in that folder).
If this will not help, I do not ave any other idea to solve the problem (unless "drastic" attempts like reinstalling R -- but I do not think this could solve, if you did not encounter the same problem using other packages).

**Comment by lovalery** [comment]
You don't have to be sorry. I have no more idea than you! However, it's still a bit annoying not being able to find the source of the problem. I put forward three hypotheses (see below). Thank you in advance for your answers to these 3 new questions.

I tried the procedure (i.e. delete the sen2r directory and restart R) that you advised me but it doesn't work either (when loading the package sen2r, I get the same Error message than the one indicated at the end of my previous post : "Erreur : package or namespace load failed for ‘sen2r’ [...] -- nom trop long ?") And at no time do I have to answer the question of write permission...

All the other packages work fine: so, like you, I don't think I have to reinstall R.
The exact path is: C: \ Users \ Loïc \ Documents \ R \ win-library \ 3.6 \ sen2r
1 - IN YOUR OPINION, CAN THE UMLAUT ON THE i OF "Loïc" BE A PROBLEM?

When installing the package sen2r, R returns: "Installing package into‘ C: /Users/Loïc/Documents/R/win-library/3.6 "
(as ‘lib’ is unspecified)
2 - SHOULD WE CREATE A 'lib' DIRECTORY AND, IF SO, AT WHAT "LEVEL" IN THE PATH?

Last, but (may be !) not least ! When trying to re-install sen2r, here is the error message (a little different from the previous ones) : 

> install.packages("sen2r")
Error in install.packages : Updating loaded packages

Restarting R session...

Error in gzfile(file, "wb") : impossible d'ouvrir la connexion 
Error saving session (options): R code execution error
WARNING: Forcing suspend of process in spite of all session data not being fully saved.
> install.packages("sen2r")
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  impossible d'ouvrir l'URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Installing package into ‘C:/Users/Loïc/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  impossible d'ouvrir l'URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘sen2r’ is not available (for R version 3.6.3)
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/bin/windows/contrib/3.6:
  impossible d'ouvrir l'URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/PACKAGES'

3 - COULD THE PROBLEM COME FROM THE ERROR MESSAGE ABOVE : Error in gzfile(file, "wb") : impossible d'ouvrir la connexion AS R SEEMS TO FAIL TO ACCESS TO CRAN?

**Comment by ranghetti** [comment]
> 1 - IN YOUR OPINION, CAN THE UMLAUT ON THE i OF "Loïc" BE A PROBLEM?

I think neither, if your locale can manage it (otherwise, you would encounter the same problem using other packages).

> 2 - SHOULD WE CREATE A 'lib' DIRECTORY AND, IF SO, AT WHAT "LEVEL" IN THE PATH?

No, this should not be necessary (you are using the default library). Nevertheless, if you want to be sure you could specify a directory outside `C: \ Users \ Loïc` (so to check also the first doubt) in which you have write permissions. Then, you should specify the same directory loading the library: `library(sen2r, lib.loc= "...")`.

> 3 - COULD THE PROBLEM COME FROM THE ERROR MESSAGE ABOVE : Error in gzfile(file, "wb") : impossible d'ouvrir la connexion AS R SEEMS TO FAIL TO ACCESS TO CRAN?

This seems to be a different error due to a CRAN unavailability, which should be temporary.

**Comment by lovalery** [comment]
Here are my remarks to your previous answers :

1- Yes, I actually have no problem with the"ï". So you are right.

2 - I did the test by creating a "lib" directory in which I put the s2r folder. The path was as follows: 
C: \Users\lib\s2r
Unfortunately, R still return the same error message ! ("Erreur : package or namespace load failed for ‘sen2r’ [...] -- nom trop long ?")

3 - O.K. I don't have this error message anymore and R seems to access to cran.

Actually, I really have no idea. If ever you have an idea, please let me know. I will always be available for testing.
Likewise, if I ever find the solution (which remains unlikely given my limited skills in this area!), I will communicate it to you on github.

Let's keep in touch
Loïc

**Comment by ranghetti** [comment]
Ok. In the meanwhile, in order to have sen2r working, you could try running it in a Docker: https://sen2r.ranghetti.info/articles/docker 
Alternatively, if the use of a docker is not clear, you could create a virtual machine with Virtualbox and installing R / sen2r there.

**Comment by lovalery** [comment]
Thank you very much for these two temporary solutions while waiting to solve the problem (although I'm not sure to succeed in implementing them because I enter a world that is completely new to me!)

**Comment by ranghetti** [comment]
Closing (feel free to reopen if necessary).
