### ISSUE TITLE
missing parameter (extra comma)

### ISSUE THREAD

**Issue by r2evans** [ranghetti/sen2r#292]
There is an extra comma in a call to `print_message`:

https://github.com/ranghetti/sen2r/blob/668d351d98f3e841da5df1415b2dd4c60fd604ce/R/sen2r.R#L674-L679

This is a syntax error and results in the app stopping:

```
Error in paste(c(...), collapse = sep) :    argument is missing, with no default.
```

This was submitted as a question on StackOverflow, https://stackoverflow.com/questions/60795974/any-users-of-the-sen2r-package

**Comment by ranghetti** [comment]
Thank you for reporting here this issue, which was fixed.

For any future readers: until the CRAN version will be updated, the issue can be solved:

1. installling the GitHub version (`remotes::install_github("ranghetti/sen2r")`), or
2. launching `check_gdal()` before running `sen2r()`.

**Comment by ranghetti** [comment]
For some reasons, patch 67fbce4d7916f26b2989b654d897cffb2ecd8eb2 was reverted before submitting v. 1.3.3 to CRAN, thus resulting bugged. It was reintroduced in GitHub version with 62fe4211ee6091d0776ba46fbb4d98c63caa24b6.

Until version 1.3.4 will be on CRAN, users may follow the previous message to get the package working.

This issue will remain open until solved on CRAN.

**Comment by ranghetti** [comment]
Version 1.3.4 is now on CRAN (I will close this as soon as Windows binaries will be ready).
