### ISSUE TITLE
displacement of sentinel2 images

### ISSUE THREAD

**Issue by VicenteYago** [ranghetti/sen2r#299]
Hi, i made this gif with sen2r, but i noticed that there is some displacement between frames. 
I think it's not related to sen2r or underlying libraries, but to the satellite itself (and there's no easy solution.) What do you think?
![evolucion](https://user-images.githubusercontent.com/16523144/78341424-f8a07c00-7597-11ea-9446-136f241d9c03.gif)

Thanks.

**Comment by ranghetti** [comment]
It is so, you could see the same problem within original SAFE images.
