### ISSUE TITLE
sen2r cannot find gdal

### ISSUE THREAD

**Issue by trosim** [ranghetti/sen2r#301]
Hi!
This package looks super-interesting! However, I can not manage to get started. I have read the scientific paper, and followed the instructions. Also tried to download gdal via OSGEO4 five times in different ways, and located on different places on the computer. I got this error message:

> check_gdal()
Searching for a valid GDAL installation...
Error: 
You do not have installed the Python GDAL executables.
Using the OSGeo4W installer (http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe), choose the "Advanced install" and check
the package "gdal-python".

When I try to start the interface I got this message:

> sen2r()
[2020-04-10 13:21:05] #### Starting sen2r execution. ####
In online mode, at least one parameter among 'extent' and 's2tiles_selected' must be provided.
[2020-04-10 13:21:05] Launching GUI...
Error in tag("div", list(...)) : argument is missing, with no default

I have tried advanced install install, and put OSgeo4 in another folkder, but does not work... Now I dont know what to do. 

Thank you for the effort, the package looks great.
Hope you can help!
Best, Trond Simensen

**Comment by ranghetti** [comment]
Hi,
I need some more information about your OS to understand (see #186, in particular point 4).

Moreover, check the existence of scripts `gdal_calc.py` and `gdal_fillnodata.py` in your installed environment (they should be present if you checked the package `gdal-python`).

By the way, the standard folder should work fine (better than custom ones). If you use a different folder, run `check_gdal()` specifying the argument `gdal_path` properly.

**Comment by trosim** [comment]
Hi!
Thank you for your swift reply! These are the commands i tried:

> check_gdal(abort = TRUE, gdal_path = "C:/Users/trosim/Documents/GIS_Trond/OSGeo4W64", force = TRUE, full_scan = FALSE)
Searching for a valid GDAL installation (this could take a long time, depending on the content of "gdal_path")...
Error: invalid version specification ‘character(0)’
In addition: Warning message:
In FUN(X[[i]], ...) :
  running command 'C:\Users\trosim\DOCUME~1\GIS_TR~1\OSGEO4~1\apps\gdal-dev\bin\gdalinfo.exe --version' had status 309

#Locations of file: 
C:\Users\trosim\Documents\GIS_Trond\OSGeo4W64\apps\Python37\Scripts\gdal_calc.py

C:\Users\trosim\Documents\GIS_Trond\OSGeo4W64\apps\Python37\Scriptsgdal_fillnodata.py

session info below,
Best, Trond

Session info:

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=Norwegian Bokmål_Norway.1252  LC_CTYPE=Norwegian Bokmål_Norway.1252    LC_MONETARY=Norwegian Bokmål_Norway.1252
[4] LC_NUMERIC=C                             LC_TIME=Norwegian Bokmål_Norway.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1   
> packageVersion("sen2r")
[1] ‘1.3.3’

**Comment by trosim** [comment]
Also tried the standard folder, and to specify the full path to the scripts folder... Still not able to connect...
Searching for a valid GDAL installation (this could take a long time, depending on the content of "gdal_path")...

> check_gdal(abort = TRUE, gdal_path = "C:/Users/trosim/Documents/GIS_Trond/OSGeo4W64/apps/Python37/Scripts", force = TRUE, full_scan = FALSE)
Error: 
GDAL was not foundwithin path "C:\Users\trosim\DOCUME~1\GIS_TR~1\OSGEO4~1\apps\Python37\Scripts" within the defined GDAL path,
please install it or define another value for argument "gdal_path".

**Comment by ranghetti** [comment]
> 
```
  running command 'C:\Users\trosim\DOCUME~1\GIS_TR~1\OSGEO4~1\apps\gdal-dev\bin\gdalinfo.exe --version' had status 309
```
This looks strange.
Can you try running the command `C:\Users\trosim\DOCUME~1\GIS_TR~1\OSGEO4~1\apps\gdal-dev\bin\gdalinfo.exe --version` in a command prompt?

**Comment by ranghetti** [comment]
Ok, I am noticing that, if you installed GDAL in `C:\Users\trosim\DOCUME~1\GIS_TR~1\OSGEO4~1\`, the correct gdalinfo path should be `C:\Users\trosim\DOCUME~1\GIS_TR~1\OSGEO4~1\bin\gdalinfo.exe`, not the found one. Did you install the package `gdal-dev`? If so, try installing GDAL in another directory, selecting **only** the package `gdal-dev`.

**Comment by trosim** [comment]
Thanks again. 
I tried this, but I am sorry to tell that I am still struggling.

> C:\Users\trosim\DOCUME~1\GIS_TR~1\OSGEO4~1\bin\gdalinfo.exe
Error: unexpected input in "C:\"

Download of the gdal-dev (only) was successful. I created a new folder ..."gdal2"
Downloaded and installed (advanced installation). Resulted in a folder with the size 45, MB containing the following folders:
"apps"; "bin"; "etc"; "http..."; "var"; and the file: "OSGeo4W". 
Furthermore, the folder "apps" contain the folder "gdal-dev", which contain the folders "bin"; "include"; "lib"; and "share". 

But then: 

> check_gdal(abort = TRUE, gdal_path = "C:/Users/trosim/Documents/GIS_Trond/gdal2/apps/Python37/Scripts", force = TRUE, full_scan = FALSE)
Error: 
The directory passed as main GDAL path does not exist.

I also got a message in the pop-up-window: 

"Wait while the OSGeo4W installer is being downloaded...
OSGeo4W was correctly downloaded.
The installer window was opened; please install the package "gdal-python" following the instructions.
The installation was terminated; please close the interface, restart R and repeat the check to be sure all was correctly installed."

Sorry to bother you with this.
Best, Trond

**Comment by ranghetti** [comment]
Sorry, I wrongly wrote "selecting **only** the package `gdal-dev`", while I meant  "selecting **only** the package `gdal-python`". The reason is that gdal-dev, which probably was installed in `"C:/Users/trosim/Documents/GIS_Trond/gdal2/apps/Python37/Scripts"`, provides additional GDAL binaries, which I suppose were wrongly detected by `check_gdal()` instead that the stable ones.
I have to ask you to re-try with another new installtion, selecting only `gdal-python`. Sorry for that.

**Comment by trosim** [comment]
Thanks, but that did not work either. If you prefer, we could do a brief video-meeting (skype, zoome, jitsi, or any other platform) briefly and I will share my screen.
Best, Trond

**Comment by trosim** [comment]
> check_gdal(abort = TRUE, gdal_path = "C:/Users/trosim/Documents/GIS_Trond/gdal3/apps/Python27/Scripts/", force = TRUE, full_scan = FALSE)
Searching for a valid GDAL installation (this could take a long time, depending on the content of "gdal_path")...
Error: 
GDAL was not foundwithin path "C:\Users\trosim\DOCUME~1\GIS_TR~1\gdal3\apps\Python27\Scripts\" within the defined GDAL path, please install it or
define another value for argument "gdal_path".
>

**Comment by ranghetti** [comment]
Use `gdal_path = "C:/Users/trosim/Documents/GIS_Trond/gdal3"`, not `gdal_path = "C:/Users/trosim/Documents/GIS_Trond/gdal3/apps/Python27/Scripts/"`.

Also, check that, in `C:\Users\trosim\Documents\GIS_Trond\gdal3`, the executable `bin\gdalinfo.exe` is present and `apps\gdal-dev\bin\gdalinfo.exe` is not.

**Comment by trosim** [comment]
https://meet.jit.si/SuccessfulDrumsMeanNot

**Comment by ranghetti** [comment]
I would prefer to remain on GitHub, so to ensure reproducibility in case other users will encounter the same issue. If you want to share your screen you can attach screenshots.

**Comment by trosim** [comment]
No problem. Copied the executable file to the folder. Still do not work.
![image](https://user-images.githubusercontent.com/33878864/78995968-de404280-7b43-11ea-861c-47e700a10674.png)

**Comment by trosim** [comment]
> check_gdal(abort = TRUE, gdal_path = "C:/Users/trosim/Documents/GIS_Trond/gdal3", force = TRUE, full_scan = FALSE)
Searching for a valid GDAL installation (this could take a long time, depending on the content of "gdal_path")...
Error: invalid version specification ‘character(0)’
In addition: Warning message:
In FUN(X[[i]], ...) :
  running command 'C:\Users\trosim\DOCUME~1\GIS_TR~1\gdal3\bin\gdalinfo.exe --version' had status 309

**Comment by trosim** [comment]
I also have QGIS, SAGA-GIS, ArcGis and the r-package rgdal installed on my computer. Does that affect the use of the package?

**Comment by ranghetti** [comment]
`running command 'C:\Users\trosim\DOCUME~1\GIS_TR~1\gdal3\bin\gdalinfo.exe --version' had status 309`
This suggests that GDAL does not work properly, as well as the gdal-dev version.

Can you try running the command `C:\Users\trosim\DOCUME~1\GIS_TR~1\gdal3\bin\gdalinfo.exe --version` in a command prompt?

**Comment by trosim** [comment]
Cannot find the program... Although installed multiple times... 
![image](https://user-images.githubusercontent.com/33878864/78996818-ae923a00-7b45-11ea-9241-a23d1566a73e.png)

**Comment by trosim** [comment]
sorry for the norwegian text... The error message says: Code cannot continue because gdal201.dll was not found. Try new installation

**Comment by trosim** [comment]
Perhaps I need to uninstall and remove all versions of Qgis, grass-gis and all previous versions of OSGeo4W, then try install again.

**Comment by ranghetti** [comment]
This is definitively an error related to GDAL and not to sen2r.
By the way, try re-opening the OSGeo4W installer and select also the package `gdal201dll`. If you do that on the same GDAL directory you used the last time (C.\...\gdal3) you will not have to reinstall also `gdal-python`.
I do not know why on your PC you should select it manually, if it is required... but that seems to be.

**Comment by trosim** [comment]
Thank you for your time! 
I will try a completely new installation of the OSGeo4W. 
Excited to try the new package (hopefully) soon. Have a great day!
Best, Trond

**Comment by ranghetti** [comment]
Ok, let me know if this will let you solve. 
Bye,

**Comment by trosim** [comment]
Succeeded! Removed all previous versions of gdal. After a selective installation from advanced options in the installer, i succeeded, by also installing dependencies for the gdal-python files. Now all the dependencies are OK. But sen2r still not working. When I run: 

sen2r(), it will not launch, either in R og in R studio. This is the error message:

[2020-04-11 12:01:38] #### Starting sen2r execution. ####
In online mode, at least one parameter among 'extent' and
's2tiles_selected' must be provided.
[2020-04-11 12:01:38] Launching GUI...
Error in tag("div", list(...)) : argument is missing, with no default

**Comment by ranghetti** [comment]
Does this error appear after installing the latest GitHub releaase?
```r
remotes::install_github("ranghetti/sen2r")
```

**Comment by trosim** [comment]
Now it worked! Thank you. Problem solved.
