### ISSUE TITLE
sen2r() / Launch processing

### ISSUE THREAD

**Issue by Olive-r** [ranghetti/sen2r#303]
Hello everyone,

When I try to run the command "sen2r()" I get an error message: 

> sen2r()
Error in paste(c(...), collapse = sep) : 
  argumento ausente, sin argumento por omisión

However, I can run te command "s2_gui()", but without the "Launch processing" option. 

Thank you in advance.

Oliver

**Comment by ranghetti** [comment]
Hi, see #292.
