### ISSUE TITLE
Warning: Parameter "apihub" was not specified

### ISSUE THREAD

**Issue by mexxwel** [ranghetti/sen2r#307]
Hi!

Great package and kudos for the efforts put into this tool.
I tried to use it but when I start the processing,  it gives me the following warning:

`Warning: Parameter "apihub" was not specified; setting it to the default ('NA').`

After that I get the constant message:

`Request failed [500]. Retrying in x seconds...`

Do have any indication, on what the problem is here?

Thanks a lot,
greetings

**Comment by ranghetti** [comment]
Hi,
it seems an internet connection problem. What is the output of `check_scihub_connection()`?

**Comment by mexxwel** [comment]
Internet connection is perfectly fine and the output of `check_scihub_connection` is `TRUE`

**Comment by ranghetti** [comment]
Have you set your SciHub credentials using the GUI or function `read_scihub_login()`? Is `write_scihub_login()` returning the proper credentials?

**Comment by mexxwel** [comment]
`read_scihub_login()` returns the matrix of my user and pw. The credentials were entered through the web version of the gui (because the gui does not open the ''select" windows).

`write_scihub_login()` returns nothing, but the read command does.

**Comment by ranghetti** [comment]
Sorry, I switched the two commands in the previous message.

In this case, I need to have more information in order to understand the problem. Read the README ad #186 and provide the required details.

**Comment by ranghetti** [comment]
Closing after 10 days of inactivity; reopen if necessary.
