### ISSUE TITLE
Error in ignorelist$dates_cloudcovered :    $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by federicotomas79** [ranghetti/sen2r#308]
To whom it may concern, I am trying to draw a polygon over New Zealand to find images between 01/01/2020 and today. I am following the clear documentation but it keeps giving me this error
```
Registered S3 method overwritten by 'geojsonlint':
  method         from 
  print.location dplyr
[2020-04-22 13:36:05] Gui closed by the user. Starting processing.
[2020-04-22 13:36:07] Searching for available SAFE products on SciHub...
[2020-04-22 13:36:09] No SAFE products matching the settings were found.
+--------------------------------------------------------------------------------------------------------------------------------------------------
¦ sen2r Processing Report
¦--------------------------------------------------------------------------------------------------------------------------------------------------
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In st_is_longlat(x) :
  bounding box has potentially an invalid value range for longlat data
```

Any help would be greatly appreciate

Thanks

**Comment by ranghetti** [comment]
The warning `bounding box has potentially an invalid value range for longlat data` is probably due to the fact that you are overlapping the international date line.

`Error: $ operator is invalid for atomic vectors` is particularly difficult to find: I need a fully reproducible example. Please read the README at #186 (which you should already have read) and provide the required information.

**Comment by ranghetti** [comment]
I should have found the problem: please install the develop branch of the package and verify if the issue was solved.
```r
install.packages("remotes")
remotes::install_github("ranghetti/sen2r", ref = "devel")
```

**Comment by ranghetti** [comment]
@federicotomas79 ,
have you checked if the issue was solved?
Let me know,
