### ISSUE TITLE
check_sen2r_deps can't find GDAL installation on OSX Catalina

### ISSUE THREAD

**Issue by n3tmaster** [ranghetti/sen2r#309]
I installed all needed libraries following sen2r instruction. In particular I installed osgeo-gdal-python through brew. GDAL was installed successfully (version 3.0.4), I test it without any problem.

Unfortunately when I run check_sen2r_deps in RStudio it couldn't find GDAL installation and said:
 "Warning: You do not have installed the Python GDAL executables (to do it, open a terminal
and type "brew install osgeo-gdal-python")."

my OS is Catalina, with last version of python 2.7, homebrew and pip.

Where am I wrong?
thank you in advance

regards

**Comment by ranghetti** [comment]
It seems that the installation instructions which I prepared for macOS using an older version are not valid for Catalina. But unfortunately I have no access to a Catalina machine, so I cannot investigate the problem.
Have a look at #290, with particular attention to the last posts. I proposed to search the local paths of GDAL utilities and manually edit the configuration file in order to set the correct paths (I do not know if the method works since @kpmainali did not provide me a feedback yet). 
Try that method: search the paths in which `gdalinfo` and `gdal_calc.py` are stored (do _not_ use the exact paths cited in that issue before checking them!) and edit the file `paths.json` as described.

Let me know,

**Comment by avolag** [comment]
Dear Luigi, 
my OS is Mojave, I have the same problem of @kpmainali with the identical output - 
I have gdalinfo in the following location:
/usr/local/Cellar/osgeo-gdal/3.0.4_2/bin/gdalinfo
I have osgeo-gdal-python in the same parent directory and this contains gdal_calc.py:
/usr/local/Cellar/osgeo-gdal-python/3.0.4_4/bin/gdal_calc.py
When I run "check_sen2r_deps()" under R environment it seems that GDAL needs to be installed or searched in a different directory. It is several day that I trying to check different folder.
I tried to following your instructions, modifying ( or better) creating the file ~/.sen2r/paths.json, following your instruction, but unfortunately it seems not work.

I true, I have several version of GDAL

Thanks a lot for you work (I'm using your docker rstudio version) and I appreciate your help.
Giovanni

**Comment by ranghetti** [comment]
To install aria2 you should use brew; nevertheless, after recent updates I think the default installer is fine enough (I will evaluate to remove aria2 in future), so you can simply skip this check.
Regarding sen2cor, probably the file permissions got wrong after the manual update; you can manually edit it, adding the line:
```json
  "sen2cor": ["/Users/Giovanni/.sen2r/sen2cor/bin/L2A_Process"],
```
Let me know if it will work after this change,

**Comment by avolag** [comment]
"_Regarding sen2cor, probably the file permissions got wrong after the manual update; you can manually edit it, adding the line_" ...
Thanks ... it is work!!!

**Comment by avolag** [comment]
I installed also aria2 (brew install aria2)
and I added the summary line (## 🍺  /usr/local/Cellar/aria2/1.35.0) in the paths.json 
Now it is working also aria2. 
Thanks a lot

**Comment by n3tmaster** [comment]
> It seems that the installation instructions which I prepared for macOS using an older version are not valid for Catalina. But unfortunately I have no access to a Catalina machine, so I cannot investigate the problem.
> Have a look at #290, with particular attention to the last posts. I proposed to search the local paths of GDAL utilities and manually edit the configuration file in order to set the correct paths (I do not know if the method works since @kpmainali did not provide me a feedback yet).
> Try that method: search the paths in which `gdalinfo` and `gdal_calc.py` are stored (do _not_ use the exact paths cited in that issue before checking them!) and edit the file `paths.json` as described.
> 
> Let me know,

Hi Ranghetti, I followed your suggestions and I changed path.json with :

 ```
 "gdalinfo": ["/usr/local/opt/osgeo-gdal/bin/gdalinfo"],
  "ogrinfo": ["/usr/local/opt/osgeo-gdal/bin/ogrinfo"],
  "gdal_translate": ["/usr/local/opt/osgeo-gdal/bin/gdal_translate"],
  "gdalwarp": ["/usr/local/opt/osgeo-gdal/bin/gdalwarp"],
  "gdalbuildvrt": ["/usr/local/opt/osgeo-gdal/bin/gdalbuildvrt"],
  "gdaldem": ["/usr/local/opt/osgeo-gdal/bin/gdaldem"],
  "gdal_calc": ["/usr/local/opt/osgeo-gdal-python/bin/gdal_calc.py"],
  "gdal_polygonize": ["/usr/local/opt/osgeo-gdal-python/bin/gdal_polygonize.py"],
  "gdal_fillnodata": ["/usr/local/opt/osgeo-gdal-python/bin/gdal_fillnodata.py"]
```
And now everything works like charm!

Note: Homebrew creates symlinks in /usr/local/opt for our convenient 

Thanks a lot.

regards

**Comment by avolag** [comment]
Dear Luigi,
I obtained the three green checks (check_sen2r_deps()), but when I run "s2_translate" I have  this error feedback:
Error: You do not have installed the Python GDAL executables (to do it, open a terminal and
type "brew install osgeo-gdal-python"_)._
Thanks in advance

**Comment by ranghetti** [comment]
This message is returned when the path of gdal_calc.py found in the file `paths.json` is not found on system. When you manually edit this file, have you checked all the paths to be correct? Basically, gdalinfo, ogrinfo, gdal_translate, gdalwarp, gdalbuildvrt and gdaldem should have the same parent directory, while gdal_calc, gdal_polygonize and gdal_fillnodata could have another one.

**Comment by n3tmaster** [comment]
> Dear Luigi,
> I obtained the three green checks (check_sen2r_deps()), but when I run "s2_translate" I have this error feedback:
> Error: You do not have installed the Python GDAL executables (to do it, open a terminal and
> type "brew install osgeo-gdal-python"_)._
> Thanks in advance

Dear avolag,
try to change GDAL path in path.json following my example posted above. home-brew command creates symlinks, for all needed GDAL commands, in /usr/local/opt. Please, take look above and you will note that some commands are stored in /usr/local/opt/osgeo-gdal/bin while other are stored in /usr/local/opt/osgeo-gdal-python/bin

**Comment by kpmainali** [comment]
Hi Luigi,

With reference to another thread I started, I tried everything you suggested for GDAL set up in iMac. Nothing worked. Eventually, I used a Windows machine to download and process the data with your library. Just to let you and @n3tmaster know, the GDAL set up in my iMac got disrupted as I tried to set it up for sen2r and I am no longer able to run other code I wrote (the script was function) that depended on GDAL.

**Comment by n3tmaster** [comment]
> Hi Luigi,
> 
> With reference to another thread I started, I tried everything you suggested for GDAL set up in iMac. Nothing worked. Eventually, I used a Windows machine to download and process the data with your library. Just to let you and @n3tmaster know, the GDAL set up in my iMac got disrupted as I tried to set it up for sen2r and I am no longer able to run other code I wrote (the script was function) that depended on GDAL.

What did you mean when you say your GDAL set up got disrupted? Changing paths.json file of sen2r doesn't make GDAL suite unavailable ... Are you using GDAL from HomeBrew? Are you using  OSGEO-GDAL package?

**Comment by kpmainali** [comment]
I am using GDAL resources from within R environment.

**Comment by ranghetti** [comment]
@avolag, have you solved following our indications?

**Comment by avolag** [comment]
@ranghetti, I followed both your indications (@n3tmaster), obtaining all the three green check when I run the check_sen2r_deps. No problem when I launch GUI from sen2r() command. But when I tried to use the s2_translate function, it return: Error: You do not have installed the Python GDAL executables (to do it, open a terminal and type "brew install osgeo-gdal-python").
Thank you in advance

**Comment by ranghetti** [comment]
Ok, this is what you wrote in your last message (https://github.com/ranghetti/sen2r/issues/309#issuecomment-623296625). After that, I suggested what to do with message https://github.com/ranghetti/sen2r/issues/309#issuecomment-623319409, and another explaination came from https://github.com/ranghetti/sen2r/issues/309#issuecomment-623358426. Have you tried that? Can you post the content of your `path.json` file?

**Comment by avolag** [comment]
is it paths.json or path.json? anyway, I tried both.

{
  "gdalinfo": ["/usr/local/Cellar/osgeo-gdal/3.0.4_3/bin/gdalinfo"],
  "ogrinfo": ["/usr/local/opt/osgeo-gdal/bin/ogrinfo"],
  "gdal_translate": ["/usr/local/opt/osgeo-gdal/bin/gdal_translate"],
  "gdalwarp": ["/usr/local/opt/osgeo-gdal/bin/gdalwarp"],
  "gdalbuildvrt": ["/usr/local/opt/osgeo-gdal/bin/gdalbuildvrt"],
  "gdaldem": ["/usr/local/opt/osgeo-gdal/bin/gdaldem"],
  "gdal_calc": ["/usr/local/Cellar/osgeo-gdal-python/3.0.4_6/bin/gdal_calc.py"],
  "gdal_polygonize": ["/usr/local/opt/osgeo-gdal-python/bin/gdal_polygonize.py"$
  "gdal_fillnodata": ["/usr/local/Cellar/osgeo-gdal-python/3.0.4_6/bin/gdal_fil$
  "sen2cor": ["/Users/Giovanni/.sen2r/sen2cor/bin/L2A_Process"],
  "aria2c": ["/usr/local/Cellar/aria2/1.35.0"]
}

**Comment by ranghetti** [comment]
`paths.json`, sorry.

This is strange and probably wrong:
```
"gdal_calc": ["/usr/local/Cellar/osgeo-gdal-python/3.0.4_6/bin/gdal_calc.py"],
"gdal_polygonize": ["/usr/local/opt/osgeo-gdal-python/bin/gdal_polygonize.py"$
"gdal_fillnodata": ["/usr/local/Cellar/osgeo-gdal-python/3.0.4_6/bin/gdal_fil$
```
You have different paths for Python-GDAL executables, which should be the same:
- `/usr/local/Cellar/osgeo-gdal-python/3.0.4_6/bin/` (gdal_calc and gdal_fillnodata)
- `/usr/local/opt/osgeo-gdal-python/bin` (gdal_polygonize)

Have you manually edited some of them but not all?

Check on your file system which is the correct path (the one containing the three executables), and change the other ones properly.

Let me know,

**Comment by avolag** [comment]
You are right, coping the patch here I noticed the errors. I changed all in the _/usr/local/opt/_ version, but nothing seems changed. 
Thanks

**Comment by ranghetti** [comment]
Please, report the output of
```r
list.files("/usr/local/opt/osgeo-gdal-python/bin/")
list.files("/usr/local/Cellar/osgeo-gdal-python/3.0.4_6/bin/")
```
and the new content of `paths.json`.

**Comment by avolag** [comment]
> list.files("/usr/local/opt/osgeo-gdal-python/bin/")
 [1] "epsg_tr.py"         "esri2wkt.py"        "gcps2vec.py"        "gcps2wld.py"        "gdal_auth.py"       "gdal_calc.py"       "gdal_edit.py"      
 [8] "gdal_fillnodata.py" "gdal_merge.py"      "gdal_pansharpen.py" "gdal_polygonize.py" "gdal_proximity.py"  "gdal_retile.py"     "gdal_sieve.py"     
[15] "gdal2tiles.py"      "gdal2xyz.py"        "gdalchksum.py"      "gdalcompare.py"     "gdalident.py"       "gdalimport.py"      "gdalmove.py"       
[22] "mkgraticule.py"     "ogrmerge.py"        "pct2rgb.py"         "rgb2pct.py"         "tests"             
> list.files("/usr/local/Cellar/osgeo-gdal-python/3.0.4_6/bin/")
 [1] "epsg_tr.py"         "esri2wkt.py"        "gcps2vec.py"        "gcps2wld.py"        "gdal_auth.py"       "gdal_calc.py"       "gdal_edit.py"      
 [8] "gdal_fillnodata.py" "gdal_merge.py"      "gdal_pansharpen.py" "gdal_polygonize.py" "gdal_proximity.py"  "gdal_retile.py"     "gdal_sieve.py"     
[15] "gdal2tiles.py"      "gdal2xyz.py"        "gdalchksum.py"      "gdalcompare.py"     "gdalident.py"       "gdalimport.py"      "gdalmove.py"       
[22] "mkgraticule.py"     "ogrmerge.py"        "pct2rgb.py"         "rgb2pct.py"         "tests"             
>

**Comment by ranghetti** [comment]
> and the new content of `paths.json`.

**Comment by avolag** [comment]
{
  "gdalinfo": ["/usr/local/opt/osgeo-gdal/bin/gdalinfo"],
  "ogrinfo": ["/usr/local/opt/osgeo-gdal/bin/ogrinfo"],
  "gdal_translate": ["/usr/local/opt/osgeo-gdal/bin/gdal_translate"],
  "gdalwarp": ["/usr/local/opt/osgeo-gdal/bin/gdalwarp"],
  "gdalbuildvrt": ["/usr/local/opt/osgeo-gdal/bin/gdalbuildvrt"],
  "gdaldem": ["/usr/local/opt/osgeo-gdal/bin/gdaldem"],
  "gdal_calc": ["/usr/local/opt/osgeo-gdal-python/bin/gdal_calc.py"],
  "gdal_polygonize": ["/usr/local/opt/osgeo-gdal-python/bin/gdal_polygonize.py"],
  "gdal_fillnodata": ["/usr/local/opt/osgeo-gdal-python/bin/gdal_fillnodata.py"],
  "sen2cor": ["/Users/Giovanni/.sen2r/sen2cor/bin/L2A_Process"],
  "aria2c": ["/usr/local/opt/aria2/"]
}
This is the paths.json I saved (ctrl +o and ctrl +x). But something seems wrong ... when  I re-open the file with nano, it is ok. But after that I run the r script with s2_translate .... the paths changed in the old version with the errors
{
  "gdalinfo": ["/usr/local/Cellar/osgeo-gdal/3.0.4_3/bin/gdalinfo"],
  "ogrinfo": ["/usr/local/opt/osgeo-gdal/bin/ogrinfo"],
  "gdal_translate": ["/usr/local/opt/osgeo-gdal/bin/gdal_translate"],
  "gdalwarp": ["/usr/local/opt/osgeo-gdal/bin/gdalwarp"],
  "gdalbuildvrt": ["/usr/local/opt/osgeo-gdal/bin/gdalbuildvrt"],
  "gdaldem": ["/usr/local/opt/osgeo-gdal/bin/gdaldem"],
  "gdal_calc": ["/usr/local/Cellar/osgeo-gdal-python/3.0.4_6/bin/gdal_calc.py"],
  "gdal_polygonize": ["/usr/local/opt/osgeo-gdal-python/bin/gdal_polygonize.py"],
  "gdal_fillnodata": ["/usr/local/Cellar/osgeo-gdal-python/3.0.4_6/bin/gdal_fillnodata.py"],
  "sen2cor": ["/Users/Giovanni/.sen2r/sen2cor/bin/L2A_Process"],
  "aria2c": ["/usr/local/opt/aria2/"]
}

**Comment by ranghetti** [comment]
Does your script contain some `check_gdal()` instructions?

**Comment by ranghetti** [comment]
@avolag I'm closing this issue since the original author solved and I did not received yet a feedback from you. If you need furher assistence, please answer to my previous message in a new issue.
