### ISSUE TITLE
Is it possible to only produce individual tile outputs and not merge by orbit?

### ISSUE THREAD

**Issue by AndrewMAPSS** [ranghetti/sen2r#315]
Hi,

I may have missed something, but is it possible to only produce individual tile outputs and not products merged by orbit?

Thank you in advance,
Andrew

**Comment by ranghetti** [comment]
Hi,  in the GUI you can set "Clip outputs on the selected extent?" to "No" (3rd sheet) and select a single tile (2nd sheet). With the function: 
```r
sen2r(
  ..., 
  clip_on_extent = FALSE, 
  s2tiles_selected = "<tile_id>"
)
```
(without passing the argument `extent`).

**Comment by AndrewMAPSS** [comment]
Thanks a million for the speedy response!
