### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by achoknyz** [ranghetti/sen2r#325]
Error emanating from GDAL hence failure to produce output images. Your support is highly appreciated
[new Sen2r error.pdf](https://github.com/ranghetti/sen2r/files/4729886/new.Sen2r.error.pdf)

**Comment by ranghetti** [comment]
As already asked you in the previous issue, follow the indications in #186 and provide the required information.

**Comment by achoknyz** [comment]
Thank you, I will have a look and if all goes well I will give feedback on the previous issue.

**Comment by ranghetti** [comment]
Probably I was not clear: in order to understand your problem, I need that you report the information requinred in the README. You already attached the information required at point 3; I still need points 1, 4 and 5. Report it here, since they are related to this issue and not to the previous (for which I did not asked you that because I understood the problem -- with the sentence "As already asked you in the previous issue" I was referring to the fact that I asked you to provide this information when I asked to open a new issue).

**Comment by achoknyz** [comment]
Sorry for the misunderstanding. Am using a windows system and running Sen2r GUI version. I did make the installations as instructed and all seemed to have ticked ok. I opened the GUI and filled the various parameters (see attached ) JSON file. I did create all output folders for the desired results. On launching the processing, the folder on level 2 has data in level 2A as expected, the output folder creates 2 additional folders (BOA, SCL) of which both are empty,  indices folder is as well empty and for the RGB folder, a new folder is created (RGB423B) but as well empty. I have attached as well other required info based on instructions in #186. Thank you and hope this is clear
[new Sen2r error.pdf](https://github.com/ranghetti/sen2r/files/4730130/new.Sen2r.error.pdf)
[Test_3_JSON_filecontents.txt](https://github.com/ranghetti/sen2r/files/4730142/Test_3_JSON_filecontents.txt)

**Comment by ranghetti** [comment]
Ok, it seems an error related to the OSGeo4W GDAL installation.

I see that you required a mask smooth/buffer of 30m. If you can skip that, the easiest way to solve this problem is to open the file `C:\Users\James\DOCUME~1\SEN2R~1\paths.json` wit a text editor and delete all the entries related to GDAL (leaving only aria2 and Sen2Cor). In this way, internal methods will be used instead of calling runtime GDAL (this is possible starting from sen2r 1.3.5).

If you need mask smoothing/buffering, runtime GDAL is mandatory. In this case, I would suggest reinstalling it (to do it you can follow the indication above and then relaunch `check_sen2r_deps()` in order to recheck GDAL and, when it will not be found, download and launch the OSGeo4W installer). Being a problem related to GDAL and not to sen2r, I cannot ensure this will solve the problem (it could also depend on system variables).

**Comment by achoknyz** [comment]
The GDAL issue has been solved by completely installing everything and doing a clean installation. Thank you

**Comment by ranghetti** [comment]
Moved from issue #323 

> I have made a fresh installation from "install.packages("sen2r", type = "source")" the part of the challenge solved. What still remains is that the process does not save my desired out indices. It manages to save level 2, output (BOA, SCL) and the RGB but not the indices. I have attached the required information
> ![Reportoutput](https://user-images.githubusercontent.com/5365067/83800719-d6ae9d00-a69f-11ea-8ead-e2cd020a3098.JPG)
> ![SessionInfo](https://user-images.githubusercontent.com/5365067/83800721-d7473380-a69f-11ea-9915-59e200bcf76b.JPG)
> [Test2_JSONfile.txt](https://github.com/ranghetti/sen2r/files/4732252/Test2_JSONfile.txt)

**Comment by ranghetti** [comment]
Let's continue here, because this is like to be related with GDAL (or to be a different error, but not related with bug #323).

I need the output of the running to understand your problem, report it.

**Comment by achoknyz** [comment]
My interest is to have an output of indices (EVI, MSAVI2 & NDVI) plus the RGB images to help me compute at a later stage the green chromatic coordinate (GCC) (would help if Sen2r had away to compute the same) anyway, All other processes, like the creation of level 2 images and the BOA and SCL look ok. The masking is being done as expected and the only issue is just the indices. I also noticed that you cannot select a folder path for the RGB and you have to enter the path manually. I hope this information together with the info above will aid in you understanding the problem. let me know if you require more information

**Comment by ranghetti** [comment]
No, it does not help: as I asked yesterday, I need _the output of the running_ (like the PDF you uploaded in your first message -- which I suppose to be changed, now that BOA/SCL were created).

Anyway: have you tried what I suggested in this previous message https://github.com/ranghetti/sen2r/issues/325#issuecomment-638837639? In particular, have you removed the GDAL entries from `paths.json`  and launched your processing without smoothing/buffering the mask?

**Comment by achoknyz** [comment]
Am sorry, please find attached output running of my previous comment. 
![output or the running](https://user-images.githubusercontent.com/5365067/83861603-b1aa4080-a718-11ea-8ac6-221710249a68.JPG)
I have as well made the changes as you specified in #325 and seems to be working ok and all the outputs are produced. See below output running
![Without_cloud masking](https://user-images.githubusercontent.com/5365067/83861775-eddda100-a718-11ea-85dd-7a03525d4da1.JPG)
![paths](https://user-images.githubusercontent.com/5365067/83861979-372df080-a719-11ea-87b0-7c93230a8884.JPG)
[Test3_nocloudmasking_JSONfile.txt](https://github.com/ranghetti/sen2r/files/4735215/Test3_nocloudmasking_JSONfile.txt)
I hope the information will help to diagnose the problem.

**Comment by ranghetti** [comment]
> and seems to be working ok and all the outputs are produced

> I hope the information will help to diagnose the problem.

I cannot understand you. If now all the outputs were generated, what is the problem?

**Comment by achoknyz** [comment]
The problem is that i need to cloud mask the images and smooth. However, when i undertake cloud masking, the indices are not generated and saved in the appropriate folder

**Comment by ranghetti** [comment]
If you need to smooth/mask clouds you have to send me the output of the processing which includes that, showing the error you are receiving. If you send me the output without cloud/mask I cannot understand.

**Comment by achoknyz** [comment]
As highlighted earlier, am acquiring sentinel 2 images over a location, with aim of preprocessing and getting vegetation indices. The process runs ok but fails to output expected vegetation indices hence the indices folder is empty. I have attached both the session information and the JSON file for your review and advice.
[Sen2_processing_JSONfile.txt](https://github.com/ranghetti/sen2r/files/4736315/Sen2_processing_JSONfile.txt)
![SessionInfo_1](https://user-images.githubusercontent.com/5365067/83880664-63586a00-a737-11ea-9b49-9c0e690f852b.JPG)

**Comment by ranghetti** [comment]
I made a code edit in order to restrict the usage of GDAL. Try reinstalling the package with
```r
install.packages("remotes")
remotes::install_github("ranghetti/sen2r", ref = "devel")
```
Then reboot R and report the output of
```r
library(sen2r)
packageVersion("sen2r")
```
After that, relaunch your processing and provide me the output (instead than making screenshots, which are incomplete, copy the text and paste it here - don't worry if it is too long).

**Comment by achoknyz** [comment]
Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> library(sen2r)
Welcome to sen2r. To use the package from a GUI, launch
 > sen2r()
Documentation: http://sen2r.ranghetti.info
Help and bug report: https://github.com/ranghetti/sen2r/issues
> packageVersion("sen2r")
[1] ‘1.3.6.9001’
> sen2r()
[2020-06-05 15:47:55] #### Starting sen2r execution. ####
[2020-06-05 15:47:55] Launching GUI...
Loading required package: shiny

Listening on http://127.0.0.1:5951
Warning: Parameter "apihub" was not specified; setting it to the default ('NA').
Loading required namespace: stringi
[2020-06-05 15:48:23] Gui closed by the user. Starting processing.
[2020-06-05 15:48:23] Searching for available SAFE products on SciHub...
[2020-06-05 15:49:11] Computing output names...
Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
[2020-06-05 15:49:17] Processing group 1 of 46...
[2020-06-05 15:49:17] Starting to download the required level-2A SAFE products.
[2020-06-05 15:49:17] Check if products are available for download...
[2020-06-05 15:49:18] 1 Sentinel-2 images are already online.
[2020-06-05 15:49:18] Downloading Sentinel-2 image 1 of 1
            (S2A_MSIL2A_20190109T074301_N0211_R092_T37MBU_20190109T104211.SAFE)...
[2020-06-05 15:57:50] Download of level-2A SAFE products terminated.
[2020-06-05 15:57:50] Starting to download the required level-1C SAFE products.
No L1C images are needed.
[2020-06-05 15:57:50] Download of level-1C SAFE products terminated.
[2020-06-05 15:57:50] Updating output names...
[2020-06-05 15:57:50] Starting to translate SAFE products in custom format.
Using UTM zone 37S.
2 output files were correctly created.
[2020-06-05 15:57:51] Starting to merge tiles by orbit.
Using projection "EPSG:32737".
[2020-06-05 15:57:51] Starting to edit geometry (clip, reproject, rescale).
[2020-06-05 15:57:51] Starting to apply cloud masks.
[2020-06-05 15:57:51] Masking file S2A2A_20190109_092_sen2r_BOA_10.tif...
Traceback (most recent call last):
  File "C:\OSGEO4~1\bin\GDAL_F~1.PY", line 34, in <module>
    from osgeo import gdal
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\__init__.py", line 41, in <module>
    _gdal = swig_import_helper()
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\__init__.py", line 24, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: The specified module could not be found.
Error in normalizePath(path.expand(path), winslash, mustWork) : 
  path[1]="C:\Users\James\AppData\Local\Temp\RtmpYnmsiB\sen2r_37185b3f55b/group371844b65fe/s2_mask/mask_37184dfd1462_2.tif": The system cannot find the file specified
[2020-06-05 15:57:59] Producing required RGB images.
[2020-06-05 15:57:59] Generating image S2A2A_20190109_092_sen2r_RGB432B_10.tif...
  |============================================================================================================================| 100%
1 output RGB files were correctly created.
[2020-06-05 15:58:05] Generating thumbnails.
2 output files were correctly created.
[2020-06-05 15:58:06] Processing group 2 of 46...
[2020-06-05 15:58:06] Starting to download the required level-2A SAFE products.
[2020-06-05 15:58:06] Check if products are available for download...
[2020-06-05 15:58:06] 1 Sentinel-2 images are already online.
[2020-06-05 15:58:07] Downloading Sentinel-2 image 1 of 1
            (S2B_MSIL2A_20190114T074249_N0211_R092_T37MBU_20190114T101616.SAFE)...

> sen2r::load_binpaths()
$sen2cor
[1] "C:\\Users\\James\\DOCUME~1\\Sen2Cor\\SEN2CO~1.05-\\L2A_PR~1.BAT"

$gdalinfo
[1] "C:\\OSGEO4~1\\bin\\gdalinfo.exe"

$python
[1] "C:\\OSGEO4~1\\bin\\python.exe"

$gdal_calc
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_C~1.PY"

$gdal_fillnodata
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_F~1.PY"

$aria2c
[1] "C:\\Users\\James\\DOCUME~1\\aria2\\aria2c.exe"

attr(,"path")
[1] "C:\\Users\\James\\DOCUME~1\\SEN2R~1/paths.json"
>

**Comment by achoknyz** [comment]
The problem still exists even after following the new instructions. Actually this time around, the output folder for BOA was empty and so is the target output vegetation indices. The RGB products have been created ok

**Comment by ranghetti** [comment]
Ok, now the issue is finally clear: the error comes in the only place in which GDAL is currently called (generating masked BOA with smoothing / buffering). RGB have been created because, in develop version 1.3.6.9001, this step does not make use of GDAL. 

The error is definitively a GDAL problem:
```
Traceback (most recent call last):
  File "C:\OSGEO4~1\bin\GDAL_F~1.PY", line 34, in <module>
    from osgeo import gdal
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\__init__.py", line 41, in <module>
    _gdal = swig_import_helper()
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\__init__.py", line 24, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: The specified module could not be found.
```
In this case I cannot help you, you can ask help on GDAL-related forums. If you will not be able to configure a working GDAL environment on your machine, you can the dockerised version (https://sen2r.ranghetti.info/articles/docker).
