### ISSUE TITLE
Error with offline SciHub: curl::curl_fetch_disk(url, x$path, handle = handle): Failed to open file

### ISSUE THREAD

**Issue by agronomofiorentini** [ranghetti/sen2r#326]
hello
I'm a strong user of this package and I appreciate its capabilities very much.

But from this morning i am getting the following error:

1. Error in curl::curl_fetch_disk(url, x$path, handle = handle): Failed to open file C:\Users\FIOREN~1\AppData\Local\Temp\Rtmp2lsqkW\sen2r_748465262a8\group74810f73efd\SAFE\S2B_MSIL1C_20200510T100029_N0209_R122_T32TQP_20200515T004952.SAFE.zip. (x3times).

2. Error in { : 
  task 1 failed - "task 1 failed - "task 1 failed - "Failed to open file C:\Users\FIOREN~1\AppData\Local\Temp\Rtmp2lsqkW\sen2r_748465262a8\group74810f73efd\SAFE\S2B_MSIL1C_20200510T100029_N0209_R122_T32TQP_20200515T004952.SAFE.zip."""

By using the follow code:

sen2r(
  gui = FALSE,
  extent = marche_wgs84,
  extent_name = "Marche",
  extent_as_mask = TRUE,
  s2tiles_selected = c("32TQP", "33TUH", "33TUJ"),
  timewindow = c(as.Date("2020-05-01"), as.Date("2020-05-22")),
  timeperiod = "full",
  list_prods = "BOA",
  s2_levels = "l2a",
  overwrite_safe = TRUE,
  rm_safe = "yes",
  online = TRUE,
  proj = "+proj=longlat +datum=WGS84",
  sel_sensor = c("s2b"),
  outformat = "GTiff",
  max_cloud_safe = 20,
  parallel = TRUE,
  path_l2a = "F:/Sentinel_2_images/sentinel_2_images_sen2r",
  path_out = "F:/Sentinel_2_images/sentinel_2_images_sen2r"
)

when I am going to use sen2r GUI with the same parameters I don't have any error and I don't understand where the problem comes from.
I would like to solve this problem so i can automate a elaboration process.

**Comment by ranghetti** [comment]
Hello, have you closed the issue because solved?

**Comment by agronomofiorentini** [comment]
yes I closed the issue because after changing some parameters it went back to work without problems.
If this problem returns I will reopen the issue.
best regards

**Comment by agronomofiorentini** [comment]
I am so sorry but i have to reopen the issue.
When i am lunching the code is going well, in fact it downloads me the required data, but try, even if not required, to download of L1C products, and when this happens I get stuck with the procedure.

And it does not allow me to perform the preprocessing operations for which I use this function.

I will attach a word document where i put the entire error_report.
[error_report_sen2r.docx](https://github.com/ranghetti/sen2r/files/4785220/error_report_sen2r.docx)

**Comment by ranghetti** [comment]
Two notes.
1. ESA SciHub appears to be unavailable at this moment (https://scihub.copernicus.eu/dhus/), as announced by https://scihub.copernicus.eu/news/News00705; so retry this evening or the day after tomorrow.
2. L1C products are usually downloaded when the corresponding L2A is not available (so to manually correct them with Sen2Cor). To avoid that (skipping the unavailable L2A), set `step_atmcorr = "l2a"`. To correct them with Sen2Cor, specify also the argument `path_l2a = "F:/Sentinel_2_images/sentinel_2_images_sen2r"` (or another path) and ensure Sen2cor to be installed and correctly configured.

**Comment by agronomofiorentini** [comment]
Hi, the problem that i reported before disappeared and it was related to the copernicus released data.
But before to close the issue that i opened, I'd like to ask you something.
When I use your function as you know it's create thumbnails, which are very useful to understand if a date is appropriate to be considered as a good image.
But sometimes I get strange cases, I would like to know what the reason could be.
i will attach the cases
![S2B2A_20200311_122_Marche_BOA_10](https://user-images.githubusercontent.com/66969646/85044248-a4b43500-b18d-11ea-87cc-5e0ae93f4519.jpg)
![S2B2A_20200410_122_Marche_BOA_10](https://user-images.githubusercontent.com/66969646/85044250-a54ccb80-b18d-11ea-82cc-ac9dfacf584c.jpg)

I think is related to a shoot delay made by sentinel

**Comment by ranghetti** [comment]
@agronomofiorentini this is a different issue, I opened #329 for it (make a comment in that issue if you want to be updated when I will have a look at it).

**Comment by ranghetti** [comment]
@agronomofiorentini have you looked at #329 and checked if my fix solved? Please leave a feedback in #329.
