### ISSUE TITLE
Incomplete output images with multiple tiles and different CRSs

### ISSUE THREAD

**Issue by ranghetti** [ranghetti/sen2r#329]
_From #326._

> Hi, the problem that i reported before disappeared and it was related to the copernicus released data.
But before to close the issue that i opened, I'd like to ask you something.
When I use your function as you know it's create thumbnails, which are very useful to understand if a date is appropriate to be considered as a good image.
But sometimes I get strange cases, I would like to know what the reason could be.
i will attach the cases
![S2B2A_20200311_122_Marche_BOA_10](https://user-images.githubusercontent.com/66969646/85044248-a4b43500-b18d-11ea-87cc-5e0ae93f4519.jpg)
![S2B2A_20200410_122_Marche_BOA_10](https://user-images.githubusercontent.com/66969646/85044250-a54ccb80-b18d-11ea-82cc-ac9dfacf584c.jpg)
>
> I think is related to a shoot delay made by sentinel

**Comment by ranghetti** [comment]
I will have a look as soon as possible.

**Comment by ranghetti** [comment]
I added a patch to fix this problem (related to merging multiple tiles dealing with different CRS).
Try instanning the develop version and running again your code (before doing it, delete existing files, since also GeoTIFFs contains black areas, not only thumbnails):
```r
install.packages("remotes")
remotes::install_github("ranghetti/sen2r", ref = "devel")
```

Let me know,

**Comment by agronomofiorentini** [comment]
Now with the latest change it works perfectly.
Thank you
![S2B2A_20200410_122_Marche_BOA_10](https://user-images.githubusercontent.com/66969646/85397612-24f2e580-b554-11ea-97e0-dd0a3b070c1f.jpg)

**Comment by agronomofiorentini** [comment]
I have to reopen an issue.

I have the same problem as reported in Marche (Italy) in Sardegna (Italy).
I kindly ask to @ranghetti to fix this.

I think is again about "different CRSs problem".

I will post the thumbnails output of sen2r and also i will attach the r code.

Thanks

![S2A2A_20200408_022_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/95368132-f7993000-08d5-11eb-98a6-851af78cc43b.jpg)

![S2A2A_20200411_065_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/95368141-fa942080-08d5-11eb-9579-8beab3d77a0a.jpg)

![S2A2A_20200401_065_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/95368153-fd8f1100-08d5-11eb-8591-0364e8ec38bb.jpg)

sen2r(gui = FALSE,
      extent = sardegna,
      extent_name = "Sardegna",
      extent_as_mask = TRUE,
      s2tiles_selected = c("32TML", "32TNL", 
                           "32TMK", "32TNK", 
                           "32SMJ", "32SNJ"),
      timewindow = c(as.Date("2020-04-01"), as.Date("2020-04-30")),
      timeperiod = "full",
      list_prods = "BOA",
      s2_levels = "l2a",
      step_atmcorr = "l2a",
      overwrite_safe = TRUE,
      rm_safe = "yes",
      online = TRUE,
      proj = "+proj=longlat +datum=WGS84",
      sel_sensor = c("s2a", "s2b"),
      outformat = "GTiff",
      max_cloud_safe = 20,
      parallel = TRUE,
      path_l2a = "F:/Sentinel_2_images/sentinel_2_images_sen2r_sardegna",
      path_out = "F:/Sentinel_2_images/sentinel_2_images_sen2r_sardegna")

**Comment by ranghetti** [comment]
This is not related to this topic; please report it in a new issue.

_Ps. I will not be at work until October 18th; I will deepen it later._
