### ISSUE TITLE
Add additional Indices (GCC & ExG)

### ISSUE THREAD

**Issue by achoknyz** [ranghetti/sen2r#330]
Please consider the addition of satellite-based Green chromatic coordinates (GCC) and Excess green (ExG) for phenological applications especially to compare with digital repeat photography. 
publication (Sonnentag, O., Hufkens, K., Teshera-Sterne, C., Young, A.M., Friedl, M., Braswell, B.H., Milliman, T., O’Keefe, J. and Richardson, A.D., 2012. Digital repeat photography for phenological research in forest ecosystems. Agricultural and Forest Meteorology, 152, pp.159-177.)

**Comment by ranghetti** [comment]
To add new indices I need the following feedbacks:

1. confirm index formulas:
    ExG = 2 * band3 − (band2 + band4)
    gcc = band3 / (band2 + band3 + band4)

2. manually compute two example rasters from Sentinel-2 data and attach them (specifying the sensing date); they will be used to validate the index computation.

**Comment by achoknyz** [comment]
Please find RGB plus GCC & ExG bands. The indices have computed from "S2B_MSIL2A_20191220T074229_N0213_R092_T37MBU_20191220T101537.SAFE" and clipped to a smaller area. The indices have computed using SNAP band maths.
[S2B2A_20191220_092_RGB432B_GCC_ExG10.zip](https://github.com/ranghetti/sen2r/files/4805835/S2B2A_20191220_092_RGB432B_GCC_ExG10.zip)
Thank you

**Comment by ranghetti** [comment]
@achoknyz the file you attached is a RGB image (all 3 bands have range 0-255), while I need example images in the right output range. Please attach two rasters (one per index) in the right format.

Moreover, you did not confirm me formulas.

**Comment by achoknyz** [comment]
I confirm the formulas are ok. I have attached two files as requested though in SNAP default format just to ensure i maintain the right format and values. Please the index will be found as an additional band and can be displayed easily on SNAP. I hope this will help

[S2B_MSIL2A_20191220_T37MBU_ExG.zip](https://github.com/ranghetti/sen2r/files/4825121/S2B_MSIL2A_20191220_T37MBU_ExG.zip)
[S2B_MSIL2A_20191220_T37MBU_GCC.zip](https://github.com/ranghetti/sen2r/files/4825123/S2B_MSIL2A_20191220_T37MBU_GCC.zip)

**Comment by ranghetti** [comment]
Indices `Rcc`, `Gcc`, `Bcc` and `ExG` were added in the GitHub release 1.3.6.9002; install it with 
```r
install.packages("remotes")
remotes::install_github("ranghetti/sen2r")
```
Feel free to reopen this issues in case of problems with these indices.
