### ISSUE TITLE
error in NDVI index

### ISSUE THREAD

**Issue by julianainpe** [ranghetti/sen2r#333]
Hi,
I'm using sen2r (gui interface in R program) to obtain BOA images (L2A) and generating NDVI index. However, the final values of NDVI index don't range to -1 to 1. 
For example, the final images have values range from -4735 to 9443. I did the processing several times, and I can't find the reason. Do you have any idea what can I be doing wrong?
Thanks, Juliana

**Comment by ranghetti** [comment]
Default index range is -10000 to 10000; see the online documentation at https://sen2r.ranghetti.info/articles/outstructure.html#spectral-indices and https://sen2r.ranghetti.info/reference/s2_calcindices.html, as well as #279 and #264.
