### ISSUE TITLE
Cannot delete download folder due to file permission error

### ISSUE THREAD

**Issue by jamesfitton** [ranghetti/sen2r#336]
Hi,

I am attempting to use sen2r to download a number of images. To save on HD space, I want to download the first image, translate it, then delete the original download folder, then move on the second image in my safelist, and so on.

However, when I try to delete the original download folder within R, I get a file permission error, and that the folder is in use (specifically the files within the grandule IMG_DATE folder). The files remain in use by "R for Windows terminal front-end".

The s2_translate is complete and an output produced, so it's not that I am trying to delete these files before the s2_translate has finished. No code is being run, and this error still occurs.

If I restart/close the R kernel, this solves the problem, but this is not helpful to my use case. I have tried using both file.remove() and unlink() to delete the folder and the same issue occurs.

I am using  sen2r version 1.3.7., R (4.0.1) in Jupyter Notebook on Windows and a Anaconda Environment.

Any ideas why the files are still being used or how to work around this? Thanks!

The below should be a reproducible example:

```R
library(sen2r)

#Set the temp path
path = tempdir()
print(path)

single_s2 <- paste0("https://scihub.copernicus.eu/apihub/odata/v1/", "Products(\'2cd1d044-375d-4be8-8277-e81c7d1da06d\')/$value")
names(single_s2) <- "S2A_MSIL1C_20150804T112046_N0204_R037_T30VWH_20150804T112539.SAFE"

#download the image - adjust to own credentials
s2_download(single_s2, outdir=path, apihub = "../../xx_accounts/scihub.txt")

#image path
imagePath <- paste0(path,"/S2A_MSIL1C_20150804T112046_N0204_R037_T30VWH_20150804T112539.SAFE")

#translate the image
s2_translate(imagePath,format="GTiff", tmpdir = path, subdirs = FALSE)

#ERROR HERE: If you try and delete the folder containing the downloaded image a "Permission denied" error occurs.
file.remove(imagePath)
```

**Comment by ranghetti** [comment]
Hi, what happens using `unlink(imagePath, recursive = TRUE)`?

**Comment by jamesfitton** [comment]
Thanks for getting back to me.

Using unlink(imagePath, recursive = TRUE), there is no error message, however, it deletes every folder/file in the directory other than the 12 jp2 files in the \GRANULE\L1C_T30VWH_A000606_20150804T112539\IMG_DATA directory.

**Comment by ranghetti** [comment]
Ok, that was what you asked for:
> then delete the original download folder

Instead, to download only the jp2 images within `IMG_DATA` you can use something like
```r
all_jp2_paths <- list.files(imagePath, "jp2$", recursive = TRUE, full.names = TRUE)
img_jp2_paths <- all_jp2_paths[grepl("GRANULE/.+/IMG_DATA", all_jp2_paths)]
sapply(img_jp2_paths, file.remove)
```

**Comment by jamesfitton** [comment]
Thanks for this.

I don't think I was clear in my previous reply - the reason the unlink deletes everything except the jp2 files is because they are still being used by R, i.e. "permission denied".

This is confirmed when I run the code snippet you provided for the jp2 paths - it finds the jp2 images, but again, permission denied.
![image](https://user-images.githubusercontent.com/13408188/87761785-fa6e1280-c809-11ea-9d24-d372bbe8c4c2.png)

I think this is more of an issue related R more than to sen2r to be honest so I'll do some more research and see if I can identify why the files are being used resulting in the permission denied error.

**Comment by ranghetti** [comment]
Sorry for misunderstanding, now I was able to reproduce the issue. It is not related to `{sen2r}` but to the `{sf}` command `gdal_utils()` called by `s2_translate()`: see https://github.com/r-spatial/sf/issues/1452 (I am closing this; let us continue there).

**Comment by jamesfitton** [comment]
No problem - it was my fault for not describing it correctly.

Thanks for looking into this and raising the issue on sf.

**Comment by ranghetti** [comment]
Issue in {sf} was fixed: @jamesfitton to get your code working, install the GitHub version of package {sf}:
```r
remotes::install_github("r-spatial/sf")
```

**Comment by jamesfitton** [comment]
Great stuff - many thanks for pursuing this!

**Comment by sermomon** [comment]
I got the same error as @jamesfitton . I have tried to install the Github version of sf but I get the following:

```
> remotes::install_github("r-spatial/sf")
Downloading GitHub repo r-spatial/sf@HEAD
Running `R CMD build`...
* checking for file 'C:\Users\sergi\AppData\Local\Temp\RtmpglZiBH\remotes4bcc63af5798\r-spatial-sf-d31ff41/DESCRIPTION' ... OK
* preparing 'sf':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'sf_1.0-7.tar.gz'
Installing package into ‘C:/Users/sergi/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'sf' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'sf'
* removing 'C:/Users/sergi/Documents/R/win-library/4.1/sf'
* restoring previous 'C:/Users/sergi/Documents/R/win-library/4.1/sf'
Warning messages:
1: In missing_devel_warning(pkgdir) :
  Package sf has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
  Install Rtools (https://cran.r-project.org/bin/windows/Rtools/).Then use the pkgbuild package, or make sure that Rtools in the PATH.
2: In i.p(...) :
  installation of package ‘C:/Users/sergi/AppData/Local/Temp/RtmpglZiBH/file4bcc46e31678/sf_1.0-7.tar.gz’ had non-zero exit status
```

**Comment by sermomon** [comment]
> 




> I got the same error as @jamesfitton . I have tried to install the Github version of `sf` but I get the following:
> 
> ```
> > remotes::install_github("r-spatial/sf")
> Downloading GitHub repo r-spatial/sf@HEAD
> Running `R CMD build`...
> * checking for file 'C:\Users\sergi\AppData\Local\Temp\RtmpglZiBH\remotes4bcc63af5798\r-spatial-sf-d31ff41/DESCRIPTION' ... OK
> * preparing 'sf':
> * checking DESCRIPTION meta-information ... OK
> * cleaning src
> * checking for LF line-endings in source and make files and shell scripts
> * checking for empty or unneeded directories
> * building 'sf_1.0-7.tar.gz'
> Installing package into ‘C:/Users/sergi/Documents/R/win-library/4.1’
> (as ‘lib’ is unspecified)
> * installing *source* package 'sf' ...
> ** using staged installation
> 
>    **********************************************
>    WARNING: this package has a configure script
>          It probably needs manual configuration
>    **********************************************
> 
> 
> ** libs
> 
> *** arch - i386
> Warning in system(cmd) : 'make' not found
> ERROR: compilation failed for package 'sf'
> * removing 'C:/Users/sergi/Documents/R/win-library/4.1/sf'
> * restoring previous 'C:/Users/sergi/Documents/R/win-library/4.1/sf'
> Warning messages:
> 1: In missing_devel_warning(pkgdir) :
>   Package sf has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
>   Install Rtools (https://cran.r-project.org/bin/windows/Rtools/).Then use the pkgbuild package, or make sure that Rtools in the PATH.
> 2: In i.p(...) :
>   installation of package ‘C:/Users/sergi/AppData/Local/Temp/RtmpglZiBH/file4bcc46e31678/sf_1.0-7.tar.gz’ had non-zero exit status
> ```
> 
> I'm not able to install `Rtools` for my R version 4.1.2.
> 
> ```
> > install.packages("Rtools")
> WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:
> 
> https://cran.rstudio.com/bin/windows/Rtools/
> Installing package into ‘C:/Users/sergi/Documents/R/win-library/4.1’
> (as ‘lib’ is unspecified)
> Warning in install.packages :
>   package ‘Rtools’ is not available for this version of R
> 
> A version of this package for your version of R might be available elsewhere,
> see the ideas at
> https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
> ```

Finally I fixed the problem by manually installing `Rtools` from https://cran.r-project.org/bin/windows/Rtools/rtools40.html and following the steps indicated:

```
write('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', file = "~/.Renviron", append = TRUE)
Sys.which("make")
```
Then I was able to install `sf` from Github and fix the problem.
