### ISSUE TITLE
Error after download images: 'task-1 failed numero di dimensioni errato'

### ISSUE THREAD

**Issue by mmazzucato** [ranghetti/sen2r#338]
I'm Matteo Mazzucato and I work in a public organisation related to animal health.
I'm currently trying to implement the sen2r library in our workflow to obtain moderate resolution vegetative indeces images over the North-Eastern part of Italy.

Upon launching my script, after downloading some Sentinel-2A images, an error is raised stating that '**task-1 failed numero di dimensioni errato**'.
I haven't already figured out what caused it, so I'm asking for help.

I also attach the script and an image of the error message.
![errore_20200721](https://user-images.githubusercontent.com/18416101/88370166-c8bcf480-cd91-11ea-9384-6b6d94b031fa.jpg)
[sen2r_test.txt](https://github.com/ranghetti/sen2r/files/4970723/sen2r_test.txt)

The extent is limited using an Triveneto poligon present in a shapefile (epsg: 32632).

Thank you in advance for your help.
Best regards.

**Comment by ranghetti** [comment]
Thanks for signaling it, it was a bug in a non-tracked situation (simoultaneously clip, reproject and mask).
I fixed it and added an automatic test for that.

Before merging in the master branch, can you check if now it is working properly? To do it, install the development branch:
```r
remotes::install_github("ranghetti/sen2r", ref = "devel")
```

**Comment by mmazzucato** [comment]
Dear @ranghetti ,
thank you very much for you quick reply.

Un fortunately I use the official package present at the official R-CRAN repo, so I don't use the git-branch-package.

I will try to use it before the merge if you need.
thanks

**Comment by ranghetti** [comment]
You can install the Github version even if you installed the CRAN version before, both to have a working non-bugged version (I do not plan to push the patched version to Cran before the end of August) and to provide me a feedback.

(PS. in this case I am quite confident that the bug have been fixed, so I do not _strictly_ need your feedback, but surely it could be useful as "litmus test".)

**Comment by ranghetti** [comment]
New fixed version 1.3.8 is now on CRAN.
