### ISSUE TITLE
Error in generating indexes from already downloaded images

### ISSUE THREAD

**Issue by jsscgrnt** [ranghetti/sen2r#340]
Hey guys,

First of all I would like to congratule the team for making this awesome app! This is really nice!!

I am new in using it, and I am having some problems. I have already downloaded Sentinel 2 BOA images through sen2r and I would like to generate some spectral indexes from the images. 

I am trying to generate an index such as EVI through this code:

sen2r::s2_calcindices(infiles = indir,
                      indices = "EVI",
                      outdir = outdir,
                      source = 'BOA', proc_mode = 'raster')

I always get this error (even thought the "EVI" name seems to be correct):

Error: 
"index" were not recognised.

Any advice would be really helpfull.

Thanks a lot!!

**Comment by ranghetti** [comment]
Hi, thank you for your appreciation.
I suppose `indir` being the path of the directory containing BOA files, while the argument `infiles` must contain the single paths of BOA files to be used (see [documentation](https://sen2r.ranghetti.info/reference/s2_calcindices)).

If this suggestion will not help, in order to understand your situation I need more information (follow the README at #186 _and_ provide the content of `indir` and `outdir` variables).

**Comment by ranghetti** [comment]
@jsscgrnt have you solved?

**Comment by jsscgrnt** [comment]
Yes, your tip helped a lot! I was wrongly using the role directory in the variable "indir" and not the path to the image itself.

I was able to generate all indexes I needed, except the  SBI (Tasselled Cap - brightness). In the SBI it returned "null" and did not create any output image.

Thank you very much for your attetion.

**Comment by ranghetti** [comment]
The formula of SBI index involves band 10 (cirrus), which is not present in Level-2A products. So, to use this index choose TOA (Level-1C) as index source.

_PS: all the indices in the "Tasselled Cap" group are non verified (meaning that I have no checked the formula provided by the [IDB](https://www.indexdatabase.de/db/i-single.php?id=91) for their correctness), so verify the formula before using them. Moreover, these indices make use of specific coefficients for each band, so I do not know if they must be computed from TOA, BOA or both. Again, check their references to know about that._
