### ISSUE TITLE
failed to launch the gui due to web connection

### ISSUE THREAD

**Issue by earthcli** [ranghetti/sen2r#341]
I have got an error when initialize the gui by sen2r():

```
# Listening on http://127.0.0.1:5508
# Warning: Error in readRDS: error reading from connection
# 52: readRDS
# 51: s2_tiles
# 50: server
# Error in readRDS(s2tiles_rds) : error reading from connection
```

Apparently this is due to the proxy of my web failed to connect to the server from github readRDS(s2tiles_rds), although I have tried to set in proxy by set_config(use_proxy(url = ip, port = port)) and Sys.setenv(http_proxy = ...).
However, I can visit the github from chrome by proxy, I wonder whether I can manually download the s2tiles_rds and run the GUI offline？Or is there other settings for proxy?

**Comment by ranghetti** [comment]
This is not related to SciHub but to the vector file of Sentinel-2 tiles, which is downloaded from Github repository the first time the packages is launched.

First, try relaunching the GUI (maybe it was a temporary server down, which now is reachable).

If nothing changed, check if you are able to reach https://raw.githubusercontent.com/ranghetti/sen2r/master/utils/vector/s2_tiles.rds: if neither, it is a problem of your connection.
Conversely, run the following code and post the output:
```r
file.info(file.path(dirname(attr(load_binpaths(), "path")), "s2_tiles.rds"))
readRDS(file.path(dirname(attr(load_binpaths(), "path")), "s2_tiles.rds"))
```

**Comment by earthcli** [comment]
@ranghetti Thanks for your quick response. I thinkd it is a problem of my connection. I can not reach raw.githubusercontent.com
both from chrome and R. 
> file.info(file.path(dirname(attr(load_binpaths(), "path")), "s2_tiles.rds"))
                                           size isdir mode               mtime
C:/Users/QIN/DOCUME~1/SEN2R~1/s2_tiles.rds    0 FALSE  666 2020-07-26 22:04:47
                                                         ctime               atime exe
C:/Users/QIN/DOCUME~1/SEN2R~1/s2_tiles.rds 2020-07-26 22:04:21 2020-07-26 22:04:47  no
> readRDS(file.path(dirname(attr(load_binpaths(), "path")), "s2_tiles.rds"))
Error in readRDS(file.path(dirname(attr(load_binpaths(), "path")), "s2_tiles.rds")) : 
  error reading from connection

**Comment by ranghetti** [comment]
And from here?
https://github.com/ranghetti/sen2r/raw/master/utils/vector/s2_tiles.rds

**Comment by earthcli** [comment]
@ranghetti I can download from the new url, but I get a file of 99kb from chrome, and 74kb if download from R. there is an error of "unknown input format".

> file.info(file.path(dirname(attr(load_binpaths(), "path")), "s2_tiles.rds"))
                                            size isdir mode               mtime
C:/Users/QIN/DOCUME~1/SEN2R~1/s2_tiles.rds 75304 FALSE  666 2020-07-27 16:48:29
                                                         ctime               atime
C:/Users/QIN/DOCUME~1/SEN2R~1/s2_tiles.rds 2020-07-27 16:44:06 2020-07-27 16:48:49
                                           exe
C:/Users/QIN/DOCUME~1/SEN2R~1/s2_tiles.rds  no
> readRDS(file.path(dirname(attr(load_binpaths(), "path")), "s2_tiles.rds"))
Error in readRDS(file.path(dirname(attr(load_binpaths(), "path")), "s2_tiles.rds")) : 
  unknown input format

**Comment by ranghetti** [comment]
I reaaly can not understand the reason of this strange behaviour; but ok, take the file from [here](https://we.tl/t-07I1rcxph1) (MD5 `66663c60e4c2ee41f6494a6032564ac4`, 3.46 MB) and replace the wrong file with it.
Let me know if after doing it the GUI will start,

**Comment by earthcli** [comment]
@ranghetti It works, thanks.
