### ISSUE TITLE
Check if Sen2Cor applied topographic correction

### ISSUE THREAD

**Issue by ranghetti** [ranghetti/sen2r#347]
Sen2Cor can produce L2A SAFE archives both applying topographic correction or not. It is possible to know if it was applied or not, but users must parse the Sen2Cor XML report (#346).

Add functionalities to:
- [ ] check if a SAFE folder is topographically corrected or not (in `safe_isvalid()` or a similar function);
- [ ] delete uncorrected SAFEs (in `rm_invalid_safe()` or a similar function);
- [ ] warn if topographic correction was required by `sen2cor()` / `sen2r()`, but some outputs were produced without correction;
- [ ] exclude non topographically corrected SAFEs from a `sen2r()` processing chain.

**Comment by lachmoeve** [comment]
Just for clearification if I run "safe_isvalid()" on a SAFE folder and the output is TRUE it means that the data has been topographically rorrected, right?

**Comment by ranghetti** [comment]
No: now `safe_isvalid()` simply checks if a SAFE contains the files (jp2 bands) required by {sen2r}; the expected enhancement is to extend the function (or create another one) to do what you write.
(This is an ehnancement issue, meaning that the points above are functionalities not currently implemented).

**Comment by ranghetti** [comment]
Closing due to the end of the package development (this improvement will not be implemented, sorry).
