### ISSUE TITLE
Aquisition time in .hdr file missing - ENVI

### ISSUE THREAD

**Issue by lachmoeve** [ranghetti/sen2r#349]
I have one question considering the data type ENVI: To do time series analysis in ENVI it is important that the .hdr file contains a line with the acquisition time looking like this "acquisition time = 2016-06-15T18:33:12.027Z". I recognized that if I am calculating for example the NDVI in sen2r the acquisition time in the .hdr file gets lost. If possible it would be wonderful if the time could be added to the .hdr file.

**Comment by ranghetti** [comment]
I will have a look on this enhancement as soon as possible.

**Comment by ranghetti** [comment]
Closing due to the end of the package development (this improvement will not be implemented, sorry).
