### ISSUE TITLE
Another test issue with recent PROJ/GDAL

### ISSUE THREAD

**Issue by rsbivand** [ranghetti/sen2r#350]
Running revdep checks with devel **sf** (@edzer) and released and master **sen2r**, and PROJ 7.1.1 and GDAL 3.1.3, I see problems in test-projpar.R, lines 8 and 9:

```
> c(projname(crs_totest))
[1] "WGS 84 (with axis order normalized for visualization)"
> c(projpar(crs_totest, "geogcs"))
[1] "WGS 84 (with axis order normalized for visualization)"
Warning message:
par = "geogcs" is now an alias of par = "name", and will be deprecated
in future. 
```
There is a further error on line 64 in test-st_crs2.R, which I have not been able to identify, I'm afraid. I think that a release of **sf** is expected soon.

**Comment by ranghetti** [comment]
Thanks for signaling it. I noticed no errors wit sf 0.9.6 using GDAL 3.0.4, PROJ 6.3.2 and GDAL 2.2.3, PROJ 4.9.3. I will have a look using develop GDAL/PROJ as soon as possible.

**Comment by rsbivand** [comment]
This is also worrying, but perhaps a separate issue:

```
> projpar(4326, "name")
[1] "WGS 84 (with axis order normalized for visualization)"
attr(,"crs")
Coordinate Reference System:
  User input: EPSG:4326 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["unknown"],
        AREA["World"],
        BBOX[-90,-180,90,180]],
    ID["EPSG",4326]]
```
We are considering advising against EPSG:4326 in all cases except where users really expect swapped axes. Some software may respect a saved file with the axis order specification. We are considering:
```
> projpar("OGC:CRS84", "name")
[1] "unknown"
attr(,"crs")
Coordinate Reference System:
  User input: OGC:CRS84 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]],
        ID["EPSG",6326]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8901]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]
```
instead. Any thoughts?

**Comment by edzer** [comment]
Not sure how important this is, but `sf` 0.9-6 is on CRAN.

**Comment by lbusett** [comment]
@rsbivand 

not directly related, but I was wondering if this could affect also the use of `leaflet` maps, which expect data to be provided in 4326 EPSG.  Any thoughts about this? 

Lorenzo

**Comment by edzer** [comment]
@rsbivand maybe we could/should bring up this issue on the https://github.com/r-spatial/discuss repo.

**Comment by rsbivand** [comment]
Yes, I'd had exactly the same thought. Are there contrasting files in the wild, with declared 4326 as specified and declared 4326 in "visualization order"? Vector and raster? Having smoking guns and knowing who created them and why would be useful.

@lbusett I think that **leaflet** and the JS follow the geojson standard of a WGS84 datum, visualization order and decimal degrees. This is OGC:CRS84, not EPSG:4326, which uses specified order (lat, long).  See https://github.com/rstudio/leaflet/commit/d1e2d98b5db603c485d498b7a4ef7b6d29e26657 and https://github.com/r-spatial/sf/issues/1474, where we see that **leaflet** is being tested on PROJ 4.9.3, so much earlier than the inclusion of GDAL barn-raising code. From PROJ >= 6 and GDAL >= 3, we see the axis order issue beginning to bite. My question on https://lists.osgeo.org/pipermail/proj/2020-September/009802.html got a quick answer, as did my tweet: https://twitter.com/RogerBivand/status/1303070211831197703, see Ian Turton's reply. So I think that geojson actually uses OGC:CRS84, but because this and EPSG:4326 were the same PROJ < 6 and GDAL < 3, people have termed it EPSG:4326 without paying attention to the axis order.

**Comment by lbusett** [comment]
@rsbivand Thanks for the clarification. I guess that to avoid problems I'll start to change all st_transform calls towards 4326 to get "good" objects for leaflet towards calls to OGC:CRS84, then!

**Comment by rsbivand** [comment]
sen2r 1.3.8 checked against forthcoming GEOS/PROJ/GDAL used in **sf** and **rgdal**/**rgeos** now has other problems in addition to those on CRAN - I have not tried to debug

[sen2r_00check.log](https://github.com/ranghetti/sen2r/files/5360875/sen2r_00check.log)
[testthat.zip](https://github.com/ranghetti/sen2r/files/5360877/testthat.zip)

For example, for `@test-gdal_warp.R#163`:

```
> exp_meta_r$size
 x  y 
29 43 
```

which are not as expected, suggesting that something has happened in `gdal_warp()`.

**Comment by rsbivand** [comment]
I'm afraid that the degradation is real; running the tests on Win10 with the CRAN **sf** binary gives the expected raster dimensions, so something has changed. On Win10 with PROJ 6.3.1 and GDAL 3.0.4:

[sen2r_oddity.txt](https://github.com/ranghetti/sen2r/files/5371957/sen2r_oddity.txt)

On PROJ 7.2.0 (dev) and GDAL 3.2.0 (dev):

```
> dim(rgdal::readGDAL(ex_sel))
/home/rsb/lib/r_libs/sen2r/extdata/out/S2A2A_20190723_022_Barbellino_RGB432B_10.tif has GDAL driver GTiff 
and has 42 rows and 24 columns
[1] 1008    3
> cat(wkt(rgdal::readGDAL(ex_sel)), "\n")
/home/rsb/lib/r_libs/sen2r/extdata/out/S2A2A_20190723_022_Barbellino_RGB432B_10.tif has GDAL driver GTiff 
and has 42 rows and 24 columns
PROJCRS["WGS 84 / UTM zone 32N",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 32N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",9,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    ID["EPSG",32632]] 
> dim(rgdal::readGDAL(test4b))
/tmp/RtmpQYjL8b/fileafd601977b591_test4b.tif has GDAL driver GTiff 
and has 43 rows and 29 columns
[1] 1247    3
> cat(wkt(rgdal::readGDAL(test4b)), "\n")
/tmp/RtmpQYjL8b/fileafd601977b591_test4b.tif has GDAL driver GTiff 
and has 43 rows and 29 columns
PROJCRS["unknown",
    BASEGEOGCRS["unknown",
        DATUM["unknown",
            ELLIPSOID["unknown",6371007.181,0,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
    CONVERSION["unnamed",
        METHOD["Sinusoidal"],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]] 
```
I'm unsure how to proceed.

**Comment by ranghetti** [comment]
Thank you @rsbivand for these warnings. During this week I can not have a look to this problem; I will investigate it next week, as soon as possible.

**Comment by ranghetti** [comment]
I am encountering troubles in building a docker container with GDAL/PROJ develop versions (https://github.com/rocker-org/geospatial/issues/31); with GDAL 3.1.3 and PROJ 7.1.1 I am not seeing any of the problems shown in https://github.com/ranghetti/sen2r/issues/350#issuecomment-706707812 and https://github.com/ranghetti/sen2r/issues/350#issuecomment-707772262. @rsbivand  can you confirm that they are specific of the develop versions (GDAL 3.2.0 and PROJ 7.2.0)?

**Comment by rsbivand** [comment]
I was testing with those versions. Both are now released, and I have not re-tested with the releeased PROJ 7.2.0 and GDAL 3.2.0.

**Comment by ranghetti** [comment]
> I was testing with those versions. Both are now released, and I have not re-tested with the releeased PROJ 7.2.0 and GDAL 3.2.0.

In this case I will try again to build them in a docker; in case of failure, I will wait until those versions will be on ubuntugis-unstable.

**Comment by ranghetti** [comment]
I finally had a look to this issue, thanks to the availability of [rocker/geospatial:dev-osgeo](https://github.com/rocker-org/geospatial/issues/31#issuecomment-740108248) docker image.
The reasons of the errors seems due to a change in GDAL >= 3.2.0 using gdalwarp with -te specified: the output resolution is computed in a different way.

This is what I am getting launching the following bash code:

```bash
gdalinfo --version

gdalwarp -t_srs EPSG:3035 -te -1157556 -1787334 -1145930 -1772742 -r near -overwrite `Rscript -e 'cat(system.file("tif/L7_ETMs.tif", package = "stars"))'` /tmp/L7_ETMs_3035_te.tif
gdalwarp -t_srs EPSG:3035 -r near -overwrite `Rscript -e 'cat(system.file("tif/L7_ETMs.tif", package = "stars"))'` /tmp/L7_ETMs_3035_note.tif

gdalinfo /tmp/L7_ETMs_3035_te.tif | grep "Size"
gdalinfo /tmp/L7_ETMs_3035_note.tif | grep "Size"
```

Case 1:
```
GDAL 3.0.4, released 2020/01/28
Creating output file that is 341P x 429L.
Processing /home/lranghetti/R/x86_64-pc-linux-gnu-library/4.0/stars/tif/L7_ETMs.tif [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 341P x 429L.
Processing /home/lranghetti/R/x86_64-pc-linux-gnu-library/4.0/stars/tif/L7_ETMs.tif [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.
Size is 341, 429
Pixel Size = (34.093841642228739,-34.013986013986013)
Size is 341, 429
Pixel Size = (34.044684504293990,-34.044684504293990)
```

Case 2:
```
GDAL 3.2.0, released 2020/10/26
Creating output file that is 425P x 533L.
Processing /usr/local/lib/R/site-library/stars/tif/L7_ETMs.tif [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.
Processing /usr/local/lib/R/site-library/stars/tif/L7_ETMs.tif [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.
Size is 425, 533
Pixel Size = (27.355294117647059,-27.377110694183866)
Size is 341, 429
Pixel Size = (34.044684504293990,-34.044684504293990)
```

I have to think about how to fix this in sen2r in order to maintain backward compatibility (any suggestion is appreciated)...

**Comment by rsbivand** [comment]
Is this https://github.com/OSGeo/gdal/issues/2754 ? I don't know much about this, maybe reach out to others? Does it only occur from 3.2.0?

**Comment by ranghetti** [comment]
It does not seem the same issue: the output image is clear, and I specified `-r near`. I opened this: https://github.com/OSGeo/gdal/issues/3294.

> Does it only occur from 3.2.0?

Using GDAL 3.1.3 the issue does not occur.

**Comment by ranghetti** [comment]
Given the answer received in OSGeo/gdal#3294 I will modify the `gdal_warp()` source code in order to always pass both `-te` and  `-tr` to `sf::gdal_utils()` (and adding a workaround to grant homogeneity in case users would update an existing archive).

**Comment by rsbivand** [comment]
The problem for **stars** @edzer `L7_ETMs.tif` is that it appears to have been stored with a Proj4 string including a `+towgs84=` key, which leads to a BOUNDCRS. Here are are two versions, the first made by:

```
L7_ETMs <- readGDAL("L7_ETMs.tif")
slot(L7_ETMs, "proj4string") <- CRS(wkt(L7_ETMs))
```
that is by running the existing WKT2:2019 (a BOUNDCRS) through `sp::CRS()` which now by default extracts the source CRS from a BOUNDCRS. The second instantiates assuming SIRGAS 2000:
```
slot(L7_ETMs, "proj4string") <- CRS("EPSG:31985")
```
Does this affect the outcomes?

[L7_ETMs_PROJCRS.zip](https://github.com/ranghetti/sen2r/files/5711791/L7_ETMs_PROJCRS.zip)

**Comment by ranghetti** [comment]
CRAN / GitHub version 1.4.0 should have fixed the problem; feel free to reopen if neither.
