### ISSUE TITLE
About single band colors

### ISSUE THREAD

**Issue by csitaula** [ranghetti/sen2r#351]
Hi, I noticed that all bands have a single color like grayscale. While combining these three colors, we obtain an image of a grayscale type.

Another concern, it provides 11 channel BOA for 10m resolution, although 10m resolution have four bands in total (RGB and NIR). 
 Could anyone please have a look at it once?  Thanks in advance.

out_paths_1 <- sen2r(
  gui = FALSE,
  step_atmcorr = "l2a",
  s2_levels = "l2a",
 # preprocess = TRUE,
  #preprocess
  sel_sensor = "s2a",
  extent = myextent_1,
  extent_name = "Barbellino",
  timewindow = c(as.Date("2019-07-13"), as.Date("2019-07-20")),
  list_prods = c("BOA"),
  #list_prods = c("BOA","SCL"),
  list_indices = c("NDVI", "MSAVI2"),
  list_rgb = c("RGB432B"), #4:2
  # list_rgb = c("RGB432B"),
  mask_type = "cloud_and_shadow",
  max_mask = 10,
  #rgb_ranges = c(0,2500)
  #extent_as_mask = TRUE,
  # clipping the designated regions
  path_l2a = safe_dir,
  path_out = out_dir_1
)

**Comment by ranghetti** [comment]
> Another concern, it provides 11 channel BOA for 10m resolution, although 10m resolution have four bands in total (RGB and NIR).

It is correct (bands at 20-60 metres are rescaled); you can find details about the output file structure at [this page](https://sen2r.ranghetti.info/articles/outstructure.html#surface-reflectances).

> Hi, I noticed that all bands have a single color like grayscale. While combining these three colors, we obtain an image of a grayscale type.

I am sorry, I cannot understand what you mean.

**Comment by csitaula** [comment]
Under R10m, R20m or R60m folder of .SAFE folder, I noticed that all the .jp2 files are of grayscale colour, but BOA contains different colours. 
If I want to stack such grascale images manually under each scale, it is again grayscle. Are such images already pre-processed or calibrated or yet to calibrate if we want to use them? 
Positive point is, I can extract RBG images from BOA image, which can be an option. But, if I want to stack .jp2 files manually according to different resolution, these grayscale images are of no use.  Could you please help me out in this regards? Thanks in advance.

**Comment by ranghetti** [comment]
{sen2r} allows producing output rasters; some products are singleband rasters, others are multiband. Visualisation depends on the software (or on the R packages) used to open rasters and/or to visualise them, not on {sen2r}. If you are using QGIS, you can find some palettes [here](https://github.com/ranghetti/sen2r/tree/master/utils/palettes).
BOA files "appears" coloured because [I assume that] your software uses some of the 11 bands (first 3?) as red, green and blue; to have understandable RGM images from BOA, you should properly set which bands must be used to map red, green and blue, and their range (but again, refer to the reference of the software/package you are using).

**Comment by csitaula** [comment]
Yes, I opened the .jp2 files  using QGIS software. My concern is whether the extracted .jp2 files are already calibrated or not? I can extract RGB imags from BOA images clearly. Thanks for your clarity.

**Comment by ranghetti** [comment]
I do not understand what you mean with "already calibrated": radiometric calibration? Atmospheric/topographic correction? Any processing performed by {sen2r}?
By the way, jp2 files are the data included in raw SAFE archives, which is an input of {sen2r}, not a product; so, {sen2r} does not modify them. You can find details about them in the ESA [Sentinel-2 Products Specification Document](https://sentinel.esa.int/web/sentinel/document-library/content/-/article/sentinel-2-level-1-to-level-1c-product-specifications).

**Comment by csitaula** [comment]
Thank you for the information. I am clear now. {sen2r} modifies them to
achieve radiometric calibration, such as BOA? Thanks a lot for a clear
explanation.
******************************************
Best Regards,
Chiranjibi Sitaula
Postgraduate Research Fellow
School of IT
Burwood Campus
Deakin University,Melbourne, Australia
ORCID:orcid.org/0000-0002-4564-2985
CYA E-RYT 550 Certified Yoga Instructor from Nepal.

**Comment by ranghetti** [comment]
No, operations performed by {sen2r} are only geometric or algebraic: creating multiband rasters, merging adjacent tiles, reshaping/reprojecting/clipping, masking cloudy area, computing spectral indices or RGB images. Sen2Cor generates L2A SAFE archives performing atmospheric and topographic correction, and can be launched from `sen2r::sen2cor()`, but the algorithm is only launched from {sen2r} function, it is not part of it.
