### ISSUE TITLE
ESA-CCI data-package

### ISSUE THREAD

**Issue by lachmoeve** [ranghetti/sen2r#352]
Hello, 
I would like to use the ESA CCI data-package. I read in the command line: 
"To use ESA-CCI data-package, download it at http://maps.elie.ucl.ac.be/CCI/viewer/download.php and install it (further information can be found at http://step.esa.int/main/third-party-plugins-2/sen2cor/)."

I looked up those websites and downloaded the packages, but unfortunately I am not sure where i should save it in order for sen2cor to find and use it. 

I would be very for any kind of advice.
Greetings and thanks in advance

**Comment by ranghetti** [comment]
Hello, see section 3.1.1 at http://step.esa.int/thirdparties/sen2cor/2.5.5/docs/S2-PDGS-MPC-L2A-SUM-V2.5.5_V2.pdf:

> This zip file shall then be extracted at this location of Sen2Cor installation: 
‘$SEN2COR_BIN/aux_data/.’

**Comment by lachmoeve** [comment]
Ok, thanks you for your fast reply.

**Comment by lachmoeve** [comment]
I guess I was confused because I couldn't find the aux_data folder under $SEN2COR_BIN. I created one under the named pathway and stored the data inside. Now ist works. :)
