### ISSUE TITLE
Values and colors for thumbnails

### ISSUE THREAD

**Issue by scf89** [ranghetti/sen2r#356]
I'm downloading ndvi raster with sen2r. I saw that a colored jpeg is created too by default. How can I know the colors and value range for the composition? I would like to know it so I can create a legend in a web map.

**Comment by scf89** [comment]
I was investigating and I found the raster2rgb() function so I tried to create a rgb with my own palette from the downloaded raster but there is an error
The code is the following:
`r1=raster("Y:/Sen2R_Download/prueba_sergio/patatas_melendez/raster/parcela1838/NDVI/S2B2A_20200501_137_sen2r_NDVI_10.tif")
palette <- "Y:/Sen2R_Download/prueba_sergio/NDVI_2020.txt"
names(palette) <- "mypalette"
raster2rgb(
  r1,
  out_file = "Y:/Sen2R_Download/prueba_sergio/patatas_melendez/raster/parcela1838/NDVI/ej.jpeg",
  palette = palette,
  minval = -1,
  maxval = 1,
  bigtiff = FALSE,
  tmpdir = NA
)`
Error in path.expand(path) : invalid 'path' argument

The palette is a color map exported in QGIS and the file's content is the following:
`# QGIS Generated Color Map Export File
INTERPOLATION:DISCRETE
0.3,255,255,255,0,<= 0.3
0.4,194,80,60,255,0.3 - 0.4
0.5,215,148,31,255,0.4 - 0.5
0.6,155,203,19,255,0.5 - 0.6
0.7,78,205,58,255,0.6 - 0.7
inf,24,145,124,255,> 0.7`

Maybe the palette is wrong?

**Comment by ranghetti** [comment]
Thumbnails were thought as a fast way to visualise images which were produced during a processing chain, so they were not intended as a pretty and customisable graphical output: this is the reason why `s2_thumbnails()` does not include options for graphical customisation.
`raster2rgb()` and `stack2rgb()` are internal functions called by `s2_thumbnails()`, so documentation is limited.

In the light of the above, regarding your questions:
- the palettes used by {sen2r} are saved in the [`extdata/palettes`](https://github.com/ranghetti/sen2r/tree/master/inst/extdata/palettes) subdirectory: browing these files you can find ranges and colours used to generate products thumbnails, as well as you can use them as a skeletron to build/customise your owns (your palette is not in the same format: compare them to adapt);
- value ranges which you find in these files are _relative_ ranges (-1 to 1, with the exception of SCL): these are rescaled in absolute ranges basing on the `minval` and `maxval` arguments of functions `raster2rgb()` and `stack2rgb()`. Here below the code determining which ranges are used by default: https://github.com/ranghetti/sen2r/blob/d05824be2ce09480c5b12b3a228e4eeff037db14/R/s2_thumbnails.R#L612-L645

**Comment by scf89** [comment]
Thank you. Adapting my palette to the right format and setting the variable r1 right as follows works well:
`r1="Y:/Sen2R_Download/prueba_sergio/patatas_melendez/raster/parcela1838/NDVI/S2B2A_20200501_137_sen2r_NDVI_10.tif"`
