### ISSUE TITLE
Sen2Cor

### ISSUE THREAD

**Issue by DorHe** [ranghetti/sen2r#361]
Running sen2cor only lists me available *.SAFE files when running this code (has been working 1/2 yr ago):
```r
#### Starting sen2r execution. ####
pos <- st_sfc(st_point(c(12.28, 47.16)), crs=st_crs(4326)) 
time_window2020 <- as.Date(c("2020-05-01","2020-10-01")) 
orb22_2020_s2_list <- s2_list(spatial_extent=pos, 
                              tile="32TQT", level = "L1C", orbit = "022",
                              max_cloud = 20, 
                              time_interval = time_window2020, time_period = "seasonal",
                              availability = "online")
orb22_2020_s2_list
View(orb22_2020_s2_list)

sen2cor(names(orb22_2020_s2_list), 
        l1c_dir = ("e:/01_Sattelkar/01_Sattelkar_satellite/Sentinel-2_Data/L1C/Orbit_022"), 
        tmpdir = ("e:/01_Sattelkar/01_Sattelkar_satellite/Sentinel-2/L1C/TMP"), 
        outdir = ("e:/01_Sattelkar/01_Sattelkar_satellite/Sentinel-2_Data/L2C/Orbit_022"),
        use_dem = TRUE,
        rmtmp = TRUE,
        parallel = TRUE)

#### sen2r session terminated. ####
```

```
[1] "e:\\01_Sattelkar\\01_Sattelkar_satellite\\Sentinel-2_Data\\L2C\\Orbit_022/S2A_MSIL2A_20200518T101031_N0209_R022_T32TQT_20200518T121146.SAFE"
 [2] "e:\\01_Sattelkar\\01_Sattelkar_satellite\\Sentinel-2_Data\\L2C\\Orbit_022/S2B_MSIL2A_20200612T100559_N0209_R022_T32TQT_20200612T124515.SAFE"
 [3] "e:\\01_Sattelkar\\01_Sattelkar_satellite\\Sentinel-2_Data\\L2C\\Orbit_022/S2A_MSIL2A_20200707T101031_N0209_R022_T32TQT_20200707T122319.SAFE"
 [4] `"e:\\01_Sattelkar\\01_Sattelkar_satellite\\Sentinel-2_Data\\L2C\\Orbit_022/S2A_MSIL2A_20200727T101031_N0209_R022_T32TQT_20200727T121713.SAFE"
```

1] with no correction => empty tmpdir & empty outdir
2] rmtmp = TRUE => the folder gets deleted; rmtmp = FALSE => stays empty

#2 
Folder `e:/01_Sattelkar/01_Sattelkar_satellite/Sentinel-2_Data/L1C/Orbit_022` contains already *.SAFE data

#4 
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)
packageVersion("sen2r"): ‘1.3.9.9002’

#5
```
> sen2r::load_binpaths()
$gdalinfo
[1] "C:\\OSGEO4~1\\bin\\gdalinfo.exe"

$ogrinfo
[1] "C:\\OSGEO4~1\\bin\\ogrinfo.exe"

$gdal_translate
[1] "C:\\OSGEO4~1\\bin\\GDAL_T~1.EXE"

$gdalwarp
[1] "C:\\OSGEO4~1\\bin\\gdalwarp.exe"

$gdalbuildvrt
[1] "C:\\OSGEO4~1\\bin\\GDALBU~1.EXE"

$gdaldem
[1] "C:\\OSGEO4~1\\bin\\gdaldem.exe"

$python
[1] "C:\\OSGEO4~1\\bin\\python.exe"

$gdal_calc
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_C~1.PY"

$gdal_polygonize
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_P~2.PY"

$gdal_fillnodata
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_F~1.PY"

$sen2cor
[1] "C:\\Users\\ge73hag\\DOCUME~1\\sen2cor\\SEN2CO~1.05-\\L2A_PR~1.BAT"

$aria2c
[1] "C:\\Users\\ge73hag\\Documents\\sen2cor\\aria2c.exe"

attr(,"path")
[1] "C:\\Users\\ge73hag\\DOCUME~1\\SEN2R~1/paths.json"
```
sen2cor link here => 404 error

**Comment by ranghetti** [comment]
Please describe your problem following the indications in the README (#186).

**Comment by ranghetti** [comment]
I am able to correctly run Sen2Cor, with the addition of the code at point 1 here below.

1. In your code the instructions to download SAFe archives is not present. Had you run the following command (or similar)?
    ```r
    s2_download(
      orb22_2020_s2_list[1:2], 
      outdir = "e:/01_Sattelkar/01_Sattelkar_satellite/Sentinel-2_Data/L1C/Orbit_022"
    )
    ```
2. What is the output of the following command?
    ```r
    safe_isvalid(file.path(
      "e:/01_Sattelkar/01_Sattelkar_satellite/Sentinel-2_Data/L1C/Orbit_022",
      names(orb22_2020_s2_list)
    ))
    ```
2. What does "sen2cor link here => 404 error" mean? 
3. What is the output of this command?
    ```r
    system(paste0(sen2r::load_binpaths()$sen2cor, " -h"))
    ```
4. Please do not update previous posts to answer to my question, but write new posts (otherwise I do not get updated of your answer, or I risk to loose parts of the conversation).

**Comment by DorHe** [comment]
5. Answer here or completly new post?

**Comment by ranghetti** [comment]
Answers

**Comment by DorHe** [comment]
1. In your code the instructions to download SAFe archives is not present. Had you run the following command (or similar)? 
-> Yes: `s2_download(orb22_2020_s2_list, outdir = "e:/01_Sattelkar/01_Sattelkar_satellite/Sentinel-2/L1C/Orbit_022")`

2. Output:
`S2A_MSIL1C_20200518T101031_N0209_R022_T32TQT_20200518T121146.SAFE  FALSE
S2B_MSIL1C_20200612T100559_N0209_R022_T32TQT_20200612T124515.SAFE	FALSE
S2A_MSIL1C_20200707T101031_N0209_R022_T32TQT_20200707T122319.SAFE	FALSE
S2A_MSIL1C_20200727T101031_N0209_R022_T32TQT_20200727T121713.SAFE	FALSE
S2B_MSIL1C_20200801T100559_N0209_R022_T32TQT_20200801T130136.SAFE	FALSE
S2A_MSIL1C_20200806T101031_N0209_R022_T32TQT_20200806T111503.SAFE	FALSE
S2B_MSIL1C_20200811T100559_N0209_R022_T32TQT_20200811T125629.SAFE	FALSE
S2B_MSIL1C_20200821T100559_N0209_R022_T32TQT_20200821T122428.SAFE	FALSE
S2A_MSIL1C_20200826T101031_N0209_R022_T32TQT_20200826T122431.SAFE	FALSE
S2A_MSIL1C_20200905T101031_N0209_R022_T32TQT_20200905T122334.SAFE	FALSE
S2A_MSIL1C_20200915T101031_N0209_R022_T32TQT_20200915T122749.SAFE	FALSE`


3. This link (https://github.com/ranghetti/sen2r/blob/master/reference/sen2cor.html) does not work, it's from here:
https://github.com/ranghetti/sen2r "sen2cor() to correct level-1C products using Sen2Cor"

4.
usage: L2A_Process.py [-h] [--resolution {10,20,60}] [--sc_only] [--cr_only]
                      [--refresh] [--GIP_L2A GIP_L2A]
                      [--GIP_L2A_SC GIP_L2A_SC] [--GIP_L2A_AC GIP_L2A_AC]
                      [--GIP_L2A_PB GIP_L2A_PB]
                      directory

Sentinel-2 Level 2A Processor (Sen2Cor). Version: 2.5.5, created: 2018.03.19,
supporting Level-1C product version <= 14.5.

positional arguments:
  directory             Directory where the Level-1C input files are located

optional arguments:
  -h, --help            show this help message and exit
  --resolution {10,20,60}
                        Target resolution, can be 10, 20 or 60m. If omitted,
                        all resolutions will be processed
  --sc_only             Performs only the scene classification at 60 or 20m
                        resolution
  --cr_only             Performs only the creation of the L2A product tree, no
                        processing
  --refresh             Performs a refresh of the persistent configuration
                        before start
  --GIP_L2A GIP_L2A     Select the user GIPP
  --GIP_L2A_SC GIP_L2A_SC
                        Select the scene classification GIPP
  --GIP_L2A_AC GIP_L2A_AC
                        Select the atmospheric correction GIPP
  --GIP_L2A_PB GIP_L2A_PB
                        Select the processing baseline GIPP
[1] 0

**Comment by ranghetti** [comment]
> 2. Output:
>    `S2A_MSIL1C_20200518T101031_N0209_R022_T32TQT_20200518T121146.SAFE  FALSE S2B_MSIL1C_20200612T100559_N0209_R022_T32TQT_20200612T124515.SAFE	FALSE S2A_MSIL1C_20200707T101031_N0209_R022_T32TQT_20200707T122319.SAFE	FALSE S2A_MSIL1C_20200727T101031_N0209_R022_T32TQT_20200727T121713.SAFE	FALSE S2B_MSIL1C_20200801T100559_N0209_R022_T32TQT_20200801T130136.SAFE	FALSE S2A_MSIL1C_20200806T101031_N0209_R022_T32TQT_20200806T111503.SAFE	FALSE S2B_MSIL1C_20200811T100559_N0209_R022_T32TQT_20200811T125629.SAFE	FALSE S2B_MSIL1C_20200821T100559_N0209_R022_T32TQT_20200821T122428.SAFE	FALSE S2A_MSIL1C_20200826T101031_N0209_R022_T32TQT_20200826T122431.SAFE	FALSE S2A_MSIL1C_20200905T101031_N0209_R022_T32TQT_20200905T122334.SAFE	FALSE S2A_MSIL1C_20200915T101031_N0209_R022_T32TQT_20200915T122749.SAFE	FALSE`

This output indicates that SAFE archives were not downloaded correctly; for this reason Sen2Cor can not recognise them. 

First, remove wrong products with the command below (this step can be skipped if you did not actually run command at point 1):
```r
safe_isvalid(file.path(
  "e:/01_Sattelkar/01_Sattelkar_satellite/Sentinel-2_Data/L1C/Orbit_022",
  names(orb22_2020_s2_list)
))
```

Then, re-run the first two commands in https://github.com/ranghetti/sen2r/issues/361#issuecomment-734757738 to check if products were correctly download. If so, launch Sen2Cor.

**Comment by DorHe** [comment]
I downloaded again (overwrite = T): again a FALSE statement for `safe_isvalid`

**Comment by DorHe** [comment]
Thank you very much, everything is fine now!

1. I ran the download with `overwrite = true`
2. Checked again with your help of `safe_isvalid`
3. Ran `sen2cor`

I encountered the following issue:
1. one file has not been fully unzipped. A *.zip file remained. This caused only a partial atmospheric correction, thus without the not fully unzipped file.

2. the link sen2cor [](https://github.com/ranghetti/sen2r/blob/master/reference/sen2cor.html) is still 404

**Comment by DorHe** [comment]
https://github.com/ranghetti/sen2r/blob/master/reference/sen2cor.html

**Comment by ranghetti** [comment]
> 1. one file has not been fully unzipped. A *.zip file remained. This caused only a partial atmospheric correction, thus without the not fully unzipped file.

Is this a systematic error? I.e., do you encounter it after a manual removal of the existing SAFE - both zip and folder?

> 2. the link sen2cor https://github.com/ranghetti/sen2r/blob/master/reference/sen2cor.html is still 404

This because I did not update the edits yet to the master branch (in the meanwhile, manually visit page https://sen2r.ranghetti.info/reference/sen2cor).

**Comment by DorHe** [comment]
Ad 1.
I re-downloaded some images to test in a test folder - did not encounter again

Ad 2.
Ok
