### ISSUE TITLE
Specificity of s2tiles_selected

### ISSUE THREAD

**Issue by estebangatillo** [ranghetti/sen2r#365]
Hi, I'm having trouble specifying the Sentinel-2 tiles for sen2r using the `s2tiles_selected` argument. I've tried just the tile (T18), without the T (18), with the added characters (T18TYL or T18TYF). I found [this resource](https://gis.stackexchange.com/questions/323928/sentinel-2-tile-ids-by-country) and used items from the 'Vendor Tile ID' column. Everything I've tried so far results in this error: 

`Error: Values are not valid tiles ID and will be removed.`

Any insight would be much appreciated, thank you!

**Comment by ranghetti** [comment]
Hi, you must use "18TYL" or "18TYF" (which is the tile ID: "18" is only the UTM zone).
