### ISSUE TITLE
Enhancement: Sen2r for specific band or AOI

### ISSUE THREAD

**Issue by DorHe** [ranghetti/sen2r#375]
Enhancement to increase performance/processing speed 
sen2r: 

#1: if only rgb bands 10 m needed and/or TCI 10 m needed -> only apply sen2r for specific bands

#2: apply sen2r only for specific AOI

**Comment by DorHe** [comment]
In general, consider that I have no more time to make substantial implementations in sen2r.
 - no problem, I can totally understand!

#2 I mean to not process the tile in its entire size but only to a part, a certain AOI

**Comment by ranghetti** [comment]
This is fully implemented, see the second sheet of the GUI or the argument `extent` of `sen2r()` and the examples [here](https://sen2r.ranghetti.info/reference/sen2r.html#examples).

**Comment by DorHe** [comment]
Thank you, Luigi!
