### ISSUE TITLE
sen2r: DEM smaller than tile

### ISSUE THREAD

**Issue by DorHe** [ranghetti/sen2r#376]
sen2r is only executable if 
size DEM > tile?

I do have a large 5 m ALS but complete tile is not covered.

Is it possible to use sen2r altough the entire tile cannot be covered completely?

**Comment by ranghetti** [comment]
It should be, but see #346 (maybe the problem is retrieving the additional DEM tile).

For specific problems, please open a new issue _**carefully following**_ the template "Help needed / question".

**Comment by DorHe** [comment]
Great, thank you for your very rapid response.

I will try it then with the smaller one and give feedback.

Yes, I have seen and read #346. 
Currently processing with the srtm/default, I will report my results in #346.
