### ISSUE TITLE
Why always display "GUI is initializing, please waiting..." when I execute "sen2r()" command under R?

### ISSUE THREAD

**Issue by yangxhcaf** [ranghetti/sen2r#377]
I installed "sen2r" package following installation description under Ubuntu 18.04, each step shows Done. Howerver, when I execute "sen2r()" command under R, a window is opened, but display  "GUI is initializing, please waiting..."，what's wrong?

**Comment by ranghetti** [comment]
In order to understand why the GUI stopped running I need additional information. When you opened the issues you found a template, whose first sentence clearly stated:

> IMPORTANT NOTE: the following template must not be deleted, but read and filled with the required information. Issues written without following the template will be marked as "malformed" and ignored.

Please reopen the issue _**strictly following**_ the indications.
