### ISSUE TITLE
Error in APIhub URIs: Zip files cannot be opened

### ISSUE THREAD

**Issue by agronomofiorentini** [ranghetti/sen2r#381]
Dear Ranghetti,
I got a strange error output when all the safe.zip files are downloaded, when i use the follow code

`sen2r(gui = FALSE,
      extent = URI_SITE,
      extent_name = "URI",
      extent_as_mask = TRUE,
      timewindow = c(as.Date("2017-06-01"), as.Date("2017-11-30")),
      timeperiod = "full",
      list_prods = "BOA",
      s2_levels = "l2a",
      step_atmcorr = "l2a",
      overwrite_safe = TRUE,
      rm_safe = "yes",
      online = TRUE,
      max_cloud_safe = 20,
      proj = "+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs",
      sel_sensor = c("s2a", 
                     "s2b"),
      outformat = "GTiff",
      parallel = TRUE,
      thumbnails =TRUE,
      path_l2a = "D:/uri/2017_Giugno_Novembre",
      path_out = "D:/uri/2017_Giugno_Novembre")`

I got the follow error:

Error in { : 
  task 1 failed - "task 1 failed - "task 1 failed - "zip file 'D:/uri/2017_Giugno_Novembre/S2A_MSIL2A_20171110T101241_N0206_R022_T32TMK_20171110T135328.SAFE.zip' cannot be opened"""
In addition: Warning message:
Using PROJ.4 strings is deprecated with PROJ >= 6 (see https://www.r-spatial.org/r/2020/03/17/wkt.html). 

How can i solve this?

Thanks in advice.

**Comment by agronomofiorentini** [comment]
I forgot from the previouse issue to upload this image which is related to the folder where the image are stored.


![image](https://user-images.githubusercontent.com/66969646/106907177-41681a80-66fe-11eb-81b8-bfeedeb3d243.png)

**Comment by ranghetti** [comment]
Wow, there is a bug in the ESA APIhub URI: some offline products results online even if they are offline, so invalid zipfiles are downloaded (here sen2r crashes when it tries to unzip them).
Before making any edit to the package I wrote to ESA support (you are in cc): let's see what they will answer.

In the meanwhile you can bypass this using `"dhus"` APIs instead than `"apihub"`, but this cannot be done from `sen2r()`, you must use specific functions: see the example below
```r
safe_list <- s2_list(
  spatial_extent = URI_SITE, 
  time_interval = c("2017-11-10", "2017-11-10"), 
  service = "dhus"
)
s2_download(
  safe_list, 
  outdir = "D:/uri/2017_Giugno_Novembre"
)

sen2r(
  online = FALSE,
  ... # all other parameters
)
```

_Ps. you should have noticed that I changed the way issue can be opened: in future, please use the right template (use "assistance" instead than "bug" if you are not sure the issue is a sen2r code bug) and fill the template with the required information instead than deleting it. Also, please do not assign._

**Comment by agronomofiorentini** [comment]
Dear ranghetti,
I tried this morning your suggested code solution 

> In the meanwhile you can bypass this using "dhus" APIs instead than "apihub", but this cannot be done from sen2r(), you must use specific functions: see the example below

but the output is the follow

[2021-02-05 08:29:06] Check if products are available for download...
[2021-02-05 08:29:13] Ordering 65 Sentinel-2 images stored in the Long Term Archive...
Request failed [403]. Retrying in 1.9 seconds...
Request failed [403]. Retrying in 1.1 seconds...
Request failed [403]. Retrying in 1.8 seconds...
Request failed [403]. Retrying in 1 seconds...
Request failed [429]. Retrying in 1 seconds...
Request failed [429]. Retrying in 1 seconds...
Request failed [429]. Retrying in 1 seconds...
Request failed [429]. Retrying in 2.5 seconds...

I think it is related to ESA APIhub URI problem.

**Comment by ranghetti** [comment]
Check your credentials and verify that you are not using users `"user"`:
```r
creds <- read_scihub_login()
creds == "user" # must be FALSE
check_scihub_login(creds[1], creds[2])
```

**Comment by agronomofiorentini** [comment]
> Check your credentials and verify that you are not using user "user":

I tried and the results was

`creds <- read_scihub_login()`

The console output was username and password

`creds == "user" # must be FALSE`

The console output was FALSE; FALSE

`check_scihub_login(creds[1], creds[2])`

The console output was TRUE

**Comment by ranghetti** [comment]
An you are still not able to make orders?

Eventually try also with both the services:
```r
s2_order(safe_list, service = "dhus")
s2_order(safe_list, service = "apihub")
```
(the first command should provide the same result of `s2_download()`, the second could change, but I expect that products with the wrong URIs will not be ordered)

**Comment by agronomofiorentini** [comment]
> An you are still not able to make orders?

Nope.

I also tried the sen2r way (online) and the same problem of yesterday it is happen.

Right now i tried again the follow code

`safe_list <- s2_list(
   spatial_extent = URI_SITE, 
   time_interval = c("2017-06-01", "2017-11-30")
)`

and 

`s2_order(safe_list, service = "dhus")`

The console output was again 

[2021-02-05 11:56:46] Check if products are already available for download...
[2021-02-05 11:56:58] 2 Sentinel-2 images are already online.
[2021-02-05 11:56:58] Ordering 64 Sentinel-2 images stored in the Long Term Archive...
Request failed [403]. Retrying in 1.4 seconds...
Request failed [403]. Retrying in 1 seconds...
Request failed [403]. Retrying in 1 seconds...
Request failed [403]. Retrying in 3.9 seconds...
Request failed [429]. Retrying in 1 seconds...

While by running the follow code

`s2_order(safe_list, service = "apihub")`

The console output was again 

[2021-02-05 11:57:12] Check if products are already available for download...
[2021-02-05 11:57:31] 25 Sentinel-2 images are already online.
[2021-02-05 11:57:31] Ordering 41 Sentinel-2 images stored in the Long Term Archive...
Request failed [403]. Retrying in 1.7 seconds...
Request failed [403]. Retrying in 3.4 seconds...
Request failed [403]. Retrying in 1 seconds...
Request failed [403]. Retrying in 3.1 seconds...
Request failed [403]. Retrying in 1.8 seconds...

I am not very lucky

But thank you so much for your help, always helpful

**Comment by agronomofiorentini** [comment]
Dear Ranghetti,
Moreover i tried to use the getSpatialData package to download the images, but again didn't work.

Now i think it is only related to ESA APIhub URI problem.

**Comment by agronomofiorentini** [comment]
Dear Ranghetti,
I tried to donwload the images via https://scihub.copernicus.eu and the products that i am trying to download are offline.
I tried to download one of them and the system put the products that i selected to cart.

Have you ever been in a situation like this?
Do you know if these products will ever come back online?

Thanks in advance.

**Comment by ranghetti** [comment]
This is the common ordering process which can be performed from the SciHub GUI (technically the same which can be performed using `s2_order(..., service = "dhus")`).
The Copernicus support answered to my enquiry (you were in cc, see the last lines as an answer to your previous question) without catching the problem. Nevertheless, now the URI problem should [could?] be solved, so you should be able to download products which are already online and ordering the others (taking into accounts the limits of LTA infrastructure, see #314).

**Comment by agronomofiorentini** [comment]
Thanks so much for the support.

I tried in the last days to run the same line of code but using a temporal range corresponding to the year 2019 and everything was executed perfectly.

I hope that one day Copernicus will allow us to access the long term satellite data without going through the usual procedure of request and then download. Also because this leads many users to use then commercial sources.

In addition I re-executed the code (apihub and dhus type) but both give me the following output

Request failed [403]. Retrying in 1 seconds...
Request failed [403]. Retrying in 1.2 seconds...
Request failed [403]. Retrying in 1 seconds...
Request failed [403]. Retrying in 2.6 seconds...
Request failed [429]. Retrying in 1 seconds...

**Comment by ranghetti** [comment]
Reporting here the content of the communication with Copernicus support, as a reference for future similar cases.

**First message**
> Dear Sirs,
> I am facing an issue in the URI used to determine if a product is offline: sometimes it returns TRUE even for offline products. This occurs only with "apihub", while using "dhus" it does not. As an example:
> https://scihub.copernicus.eu/dhus/odata/v1/Products('a81999d6-75da-427b-9355-ae031256cfa9')/Online/$value -> FALSE
> https://scihub.copernicus.eu/apihub/odata/v1/Products('a81999d6-75da-427b-9355-ae031256cfa9')/Online/$value -> TRUE
> Trying to run the download (e.g. https://scihub.copernicus.eu/apihub/odata/v1/Products('a81999d6-75da-427b-9355-ae031256cfa9')/$value), an invalid zip file is downloaded.
> I would like to know if this behaviour is a bug (which is planned to be solved) or a known issue, since it is affecting the behaviour of a tool which I developed (https://github.com/ranghetti/sen2r).
> Thank you for your time, best regards
> Luigi Ranghetti


**Copernicus' answer**
> Dear Luigi,
> 
> With reference to our previous email, we would like to inform you that  the retrieval process has to be initiated from both the platforms (eg: if, for example, the product is available on line on the GUI it is not automatically reflected on the API Hub) these are two separated processes.
> 
> Please note that the Technical support team launched the queries reported and the product is offline on both services.
> 
> The following query correctly activates the retrieval of the product from the LTA from Api Hub 
> https://scihub.copernicus.eu/apihub/odata/v1/Products('a81999d6-75da-427b-9355-ae031256cfa9')/$value
> 
> The product has also been requested also from the GUI and it should be available very soon. We kindly suggest you should check also using the following query:
> 
> https://scihub.copernicus.eu/dhus/odata/v1/Products('a81999d6-75da-427b-9355-ae031256cfa9')/$value
> 
> or directly form the GUI.
> 
> Finally, we would like to remind you that at the moment, an automatic notification informing the user of the online availability of the restored product is not yet available as it depends on the number of requests submitted by all users.
> 
> Therefore, it is not possible to estimate the time of the retrieval, and we suggest you should check the update status on the Copernicus Open Access Hub or directly in your Cart. 
> 
> Once back online, products are available for immediate download only for a limited amount of time, nearly 3 days. At the end of this time-span, will be put offline again from the Data Hub Server. 
> 
> When an offline product is restored and is available for immediate download, it is visible in the “Shopping Cart” with the “Online” label instead of the “Offline” one.   
> 
> Restored products are available online only for a limited amount of time.   
> 
> At the end of this time-span, data will be put offline again from the Data Hub System.   
> 
> I hope the above will be of use.
> 
> Should you need further information or assistance, please do not hesitate to contact us again.
> 
> Kind regards,
> Helene
> 
> SCI Team
> Copernicus Services Coordinated Interface ESA service operated by Serco
> Mail: EOSupport@copernicus.esa.int
> Portal: https://Spacedata.Copernicus.eu/


**My reply**
> Dear Helene,
> thank you for your reply, which unfortunately did not catch the issue. The problem was not the fact that some products are online on a platform and offline on another, but the fact that, on ApiHub, some products offline on ApiHub were declared as online, and that, in this case, trying to run the download an invalid zip file were downloaded instead that an XML page with the proper status code. Now this situation can not yet be verified, since products are correctly online.
> Regards,
> Luigi Ranghetti

**Comment by agronomofiorentini** [comment]
Good morning
I ran the following code 

`sen2r(gui = FALSE,
      extent = zone,
      extent_name = "zone",
      extent_as_mask = TRUE,
      timewindow = c(as.Date("2020-08-01"), as.Date("2020-11-30")),
      timeperiod = "seasonal",
      list_prods = "BOA",
      s2orbits_selected = 65,
      s2_levels = "l2a",
      step_atmcorr = "l2a",
      overwrite_safe = TRUE,
      rm_safe = "yes",
      online = TRUE,
      max_cloud_safe = 30,
      proj = "+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs",
      sel_sensor = c("s2a", 
                     "s2b"),
      outformat = "GTiff",
      parallel = TRUE,
      thumbnails =TRUE,
      path_l2a = "C:/Users/Roberto/Desktop/marco_fiorentini/sentinel_images/sentinel_images",
      path_out = "C:/Users/Roberto/Desktop/marco_fiorentini/sentinel_images/sentinel_images")`

And I reported the same error as previously, that is, it downloads the SAFE.zipper files then tries to open them and then gets to a file and the process hangs (image attached)

However, this time, compared to the previous ones, I have entered a time range much closer to today, which seems very strange. Moreover the files which were downloaded have a size for which I would consider them undamaged files

![image](https://user-images.githubusercontent.com/66969646/108033225-f5896f80-7033-11eb-827b-688cb0624f2f.png)

**Comment by ranghetti** [comment]
> Moreover the files which were downloaded have a size for which I would consider them undamaged files

Yes, so it is likely a different problem: please open a new issue (following the "Help needed" template: in particular, take care to code reproducibility and report the whole console output).

**Comment by ranghetti** [comment]
> Hi, I am having the same issues you list in the 2 bullet points (apihub is returning true and an invalid SAFE can be downloaded -- cannot unzip the downloaded SAFE nor open it in SNAP and dhus is just giving me a 403 Forbidden). I emailed Copernicus support letting them know and cited your ticket number.

_Originally posted by @jburmistrova in https://github.com/ranghetti/sen2r/issues/374#issuecomment-781730254_

Hi @jburmistrova, 
since these kind of errors are becoming frequent, I am planning to manage them by always checking SAFE availability on DHUS (8448f4302ab3c36cf2bb4226c619889e9c144874). To debug that I need a current example (old reported examples are now "fixed" on ShiHub, since products were ordered and the misplacement between DHUS and API Hub was resolved). Can you specify which specific products are showing this behaviour, in your case?

**Comment by jburmistrova** [comment]
Yes. So I kept a log of the issues in an excel table. I sent this excel file to Copernicus also. Just make sure though, this is an issue with Copernicus, correct? I downloaded these Sentinel-2 files a few months ago but needed to redownload and I didn't have these issues before.

[S2records20210216_dhusVSapihub_errors.xlsx](https://github.com/ranghetti/sen2r/files/6011365/S2records20210216_dhusVSapihub_errors.xlsx)

**Comment by ranghetti** [comment]
Thank you, this helped me to debug. Now {sen2r} is able to manage these situations: if `service = "dhus"` is used products are ordered, otherwise the wrong SAFE archive is ont downloaded and products are skipped. I will evaluate in future if adding an automatic ordering command from dhus.

> this is an issue with Copernicus, correct?

Yes, let we know if you will receive a more pertinent answer.

**Comment by Zavud** [comment]
Dear @ranghetti I launched the shiny app running `sen2r()` and I am getting the similar error message:

`Error in { : 
  task 1 failed - "task 1 failed - "task 1 failed - "zip file '...sentinel2_august_2018/S2B_MSIL2A_20180818T103019_N0208_R108_T32ULA_20180818T161004.SAFE.zip' cannot be opened"""
In addition: Warning messages:
1: In CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  :
  GDAL Message 1: Several features with id = 0 have been found. Altering it to be unique. This warning will not be emitted for this layer
2: "max_mask" was set to 4, but no masks were defined: set argument "mask_type" properly in order to use a
cloud mask. 
3: Both native and custom resolution were provided; only custom one ("res") will be used. 
4: 'geojsonlint' not installed, skipping GeoJSON linting `

Is there a way that I could fix this?

**Comment by ranghetti** [comment]
@Zavud install the GitHub version of the package:
```r
install.packages("remotes")
remotes::install_github("ranghetti/sen2r")
```
If you encountered the same error of this topic, the update will fix it; otherwise it would mean that your situation is different to this topic, so in this case open a new issue choosing the "Help needed" template and describe your situation _**carefully following the template instructions**_.

**Comment by Zavud** [comment]
@ranghetti I got this error when I tried to install the GitHub version of the package:

`package ‘Rcpp’ successfully unpacked and MD5 sums checked
Error: Failed to install 'sen2r' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘Rcpp’`
