### ISSUE TITLE
Using Sen2r behind corporate proxy

### ISSUE THREAD

**Issue by riazarbi** [ranghetti/sen2r#382]
**Functionality**
How to use `sen2r` behind a corporate proxy

**Documentation reference**
While the use of R and R packages behind a corporate proxy is documented on the internet, there is no relevant documentation for `sen2r`. This documentation would be useful for users of `sen2r` who work in environments protected by a corporate proxy. 

**Documentation snippet**
I am using `sen2r` v `1.4.0` on R `4.0.3` on Ubuntu 20.04. My Dockerfile can found [here.](https://github.com/riazarbi/datasci-r-sentinel).

There are two places the proxy must be set. This is because some `sen2r` functions use `httr` under the hood, while others call the underlying OS downloader or `aria2`. In particular, `s2_list` uses `httr` while `s2_download` uses the underlying OS downloader.

Here is an example snippet that works in my environment.  Replace the relevant variables for your environment. The `Sys.setenv` calls are to set the OS proxy, the `set_config` calls are to set the `httr` config.

```
proxy_user <- "my_username"
proxy_password <- "my_password"
proxy_url <- "my_proxy_url"
proxy_port <- "my_proxy_port"
proxy_string <- paste0("http://", proxy_user, ":", proxy_password, "@", proxy_url, ":", proxy_port)

Sys.setenv(http_proxy=proxy_string)
Sys.setenv(https_proxy=proxy_string)
Sys.setenv(HTTP_PROXY=proxy_string)
Sys.setenv(HTTPS_PROXY=proxy_string)

httr::set_config(
  httr::use_proxy(proxy_url, 
                  port = proxy_port, 
                  username = proxy_user, 
                  password = proxy_password, 
                  auth = "basic"))
```
Once those are set, you should be able to use `sen2r` as normal.

```
> # Validate login
> sen2r::check_scihub_login(scihub_user, scihub_password)
[1] TRUE
> # Set login creds
> sen2r::write_scihub_login(scihub_user, scihub_password)
> # Load extent
> boundary <- read_sf("cct.geojson")
> # Set target date
> # start <- as.Date("2020-11-09")
> # end   <- start + days(2)
> # date_period <- c(start, end)
> date_period <- as.Date("2020-11-14")
> # get a list of products
> safe_list <- sen2r::s2_list(spatial_extent = boundary, 
+                             tile = NULL, 
+                             orbit = NULL,
+                             time_interval = date_period, 
+                             time_period = "full",
+                             apihub = NA, 
+                             max_cloud = 100,
+                             availability = "check")
although coordinates are longitude/latitude, st_union assumes that they are planar
> length(safe_list)
[1] 1
> # Download missing relevant tiles
> sen2r::s2_download(safe_list, outdir = "/home/jovyan/sentinel/2a-cache")
[2021-02-10 12:15:53] Check if products are available for download...
[2021-02-10 12:15:54] Downloading Sentinel-2 image 1 of 1
         (S2A_MSIL2A_20201114T083221_N0214_R021_T34HBH_20201114T110752.SAFE)...
  |===============================================================================================| 100%
A named vector with 1 SAFE archives.
                                     S2A_MSIL2A_20201114T083221_N0214_R021_T34HBH_20201114T110752.SAFE 
"https://scihub.copernicus.eu/apihub/odata/v1/Products('f60d5cd0-386a-4197-8ec2-140b6e75313e')/$value"

```

**Suggested action**
I don't think any specific action is required other than closing this issue and keeping it up for people to find when they try and use sen2r behind a corporate proxy.

**Comment by riazarbi** [comment]
Actually, on order to prevent your system exhibiting strange proxy behavior after you're done working, it's probably best to set and unset the system proxy variables cleanly, like so :

```
# Download missing relevant tiles
Sys.setenv(http_proxy=proxy_string)
Sys.setenv(https_proxy=proxy_string)
Sys.setenv(HTTP_PROXY=proxy_string)
Sys.setenv(HTTPS_PROXY=proxy_string)
sen2r::s2_download(safe_list, outdir = "/home/jovyan/sentinel/2a-cache")
Sys.unsetenv("http_proxy")
Sys.unsetenv("https_proxy")
Sys.unsetenv("HTTP_PROXY")
Sys.unsetenv("HTTPS_PROXY")
```

**Comment by ranghetti** [comment]
Thank you very much @riazarbi for this useful note!
