### ISSUE TITLE
Clouds inside my extent despite `max_mask = 0`

### ISSUE THREAD

**Issue by Leprechault** [ranghetti/sen2r#386]
I have a problem with clouds inside my extent despite the `max_mask = 0` and `mask_type = "cloud_and_shadow"` condition in `sen2r()` function. In my example:

```
#Packages
library(sen2r)
library(rgdal)

# Read borders of the project lobo.shp just for visualization
https://www.dropbox.com/sh/oobjp98i2jy5ce0/AADCvts4vd38YTeZSFe-yuuSa?dl=0 # Original shapefile in Dropbox
borders <- readOGR (".","lobo") 
proj4string(borders) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")
plot(borders)

# Use sen2r for donwload my image in BOA
if (interactive()) {
  check_scihub_login("xxx", "xxx")
  write_scihub_login("xxx", "xxx")
  read_scihub_login()
}
sen2r(
  gui = FALSE,
  timewindow = as.Date("2020-07-04"),
  extent = "lobo.shp", extent_name = "lobo",
  list_prods = c("BOA"),
  res_s2 = "10m",
  mask_type = "cloud_and_shadow",
  max_mask = 0, 
  extent_as_mask = TRUE,
  overwrite_safe = TRUE,
  rm_safe="yes",
  path_l1c = "~/dataset/sen2data", 
  path_l2a = "~/dataset/sen2data",
  path_out = "~/dataset/sen2data"
)
#
```

But when a make the inspection of my image (`S2A2A_20200704_124_lobo_BOA_10`)  in thumbnails folder I have a lot of clouds and shadows in my image:

![image](https://user-images.githubusercontent.com/17205267/108749326-0fd0bb00-7516-11eb-9a5b-f763ceed2885.png)

Please, how I can solve this? This is normal? Because I re-install the package and the same problem happens several times in other images/locations too, included Ubuntu18.04 and W10 machines.

**Comment by ranghetti** [comment]
First of all, have you checked how these areas are classified inside the input SAFE? Use 'list_prods = c("BOA", "SCL")`, open the produced SCL image and check which SCL classes correspond to those surfaces: if they are not classified as clouds or shadows, {sen2r} can not be used to mask them.

Let me know,

Ps.:
1. for future issues: use the template "bug" only if you are sure you are reporting a code bug. In cases like this one, use "Help needed";
2. 2. do not assign issues (I am not your employee ;) )

**Comment by Leprechault** [comment]
Hi, @ranghetti so sorry about the assignment I did it unintentionally. So sorry about the bug label too, I mistakenly thought that the output was a problem related to the function. Thanks for the explanation!!  Best wishes!!!
