### ISSUE TITLE
Error in s2_dt_centroid[, "X"] : no 'dimnames' attribute for array

### ISSUE THREAD

**Issue by estebangatillo** [ranghetti/sen2r#387]
**Issue description**

Getting an error upon `sen2r()` call: Error in s2_dt_centroid[, "X"] : no 'dimnames' attribute for array

I've tried three different AOI.

**Reproducible example**

```
# Max cloud safe counter
max_cloud <- 10  # (%)
max_cloud_reset <- max_cloud
max_cloud_threshold <- 1 # (%)
max_cloud_incr <- 1
composite_pct_na <- 100
na_threshold <- 5 # (%)
time_window <- 14 # +/- days e.g. 1 month search window
time_window_reset <- time_window
time_window_threshold <- floor((365/4)) # +/- 3 months
time_window_incr <- 7 # one week at a time
time_period_type <- "seasonal"
search_year <- 0 # How far back to search (0 is current year)
search_year_threshold <- 5
search_year_incr <- 1
atmcorr_type <- "l2a" 
res_s2 <- "10m"
extent_as_mask <- T
extent_path <- get_study_extent_path(custom_extent = custom_extent)
print_line()

while(all(composite_pct_na > na_threshold)) {
  
  previous_sen_files <- length(list.files("./data/sentinel-2/sen2r-out/BOA", "\\.tif$", full.names = T))
  start_date <- as.Date(min(trav_date))-time_window-lubridate::years(search_year)
  end_date <- as.Date(max(trav_date))+time_window
  

  sen2r(gui = FALSE,
        timewindow = c(start_date, end_date),
        timeperiod = time_period_type,
        extent = extent_path,
        extent_name = city_name,
        list_prods = c("BOA"),
        max_cloud_safe = max_cloud,      
        mask_type = NA, # no mask
        res_s2 = res_s2,
        extent_as_mask = extent_as_mask,
        parallel = detectCores()-1,
        processing_order = "3", # 3 is fastest but consumes more disk
        step_atmcorr = atmcorr_type,
        overwrite = F,
        overwrite_safe = F,
        rm_safe = "no",
        path_l1c = "./data/sentinel-2/sen2r-in", path_l2a = "./data/sentinel-2/sen2r-in",
        path_out = "./data/sentinel-2/sen2r-out")
  
  # Create list of sentinel-2 processed raster files
  sen_files <- list.files("./data/sentinel-2/sen2r-out/BOA", "\\.tif$", full.names = T)
  
  # Conditionally process composite rasters based on new data
  if(length(sen_files) > 0) {
    if(length(sen_files) > previous_sen_files) {
      # Combine all sentinel observations into single stack 
      sen_stack <- stack(sen_files)
      # Determine percent NA in composite layers for each band 
      composite_pct_na <- composite_bands(sen_stack, custom_extent) %>% unlist
      
      # Plot composite raster if ran interactively within RStudio
      if(any(grepl("rstudio", Sys.getenv()))) {
        s <- stack(list.files("./data/sentinel-2/sentinel-processed", "\\.tif", full.names = T))
        # rgb = 4 3 2
        rgb_scale <- max(c(getValues(s[[6]]), getValues(s[[5]]), getValues(s[[4]])), na.rm = T)
        plotRGB(s, r = 6, g = 5, b = 4, scale = rgb_scale)
      }

    } else {
      print(paste0("No new files were added to sen2r-in, skipping composite!"))
    }
  } else {
    print(paste0("No files within './data/sentinel/sen2r-in' were found..."))
  }
  
  # Update loop status
  print(paste0("Composite percent NA: ", mean(unique(composite_pct_na))))
  print(paste0("Atm Corr: ", atmcorr_type))
  print(paste0("Max Cloud: ", max_cloud))
  print(paste0("Time Window: ", time_window))
  print(paste0("Search Years: ", search_year))
  print(paste0("Start Date: ", start_date))
  print(paste0("Campaign Date: ", trav_date))
  print(paste0("End Date: ", end_date))
  print_line()
  
  # Conditionally increment our counter variables
  if(max_cloud >= max_cloud_threshold) {
    if(time_window >= time_window_threshold) {
      if(search_year >= search_year_threshold) {
        if(atmcorr_type == "l2a") {
          # atmcorr_type <- "auto"
          # max_cloud <- 0 # This will take forever!
          print(paste0("No SAFE data were meeting the quality criteria were found..."))
          na_threshold <- ceiling(unique(composite_pct_na))  
          print(paste0("Using NA threshold of ", na_threshold, "%"))
          print_line()
          stop()
        } else {
          print(paste0("No SAFE data were meeting the quality criteria were found..."))
          na_threshold <- ceiling(unique(composite_pct_na))  
          print(paste0("Using NA threshold of ", na_threshold, "%"))
          print_line()
          stop()
        }
      } else {
        search_year <- search_year + search_year_incr
        time_window <- time_window_reset
        max_cloud <- max_cloud_reset
      }
    } else {
      time_window <- time_window + time_window_incr
      max_cloud <- max_cloud_reset
    }
  } else {
    max_cloud <- max_cloud + max_cloud_incr
  }
}
```

Custom composite_bands function:

```
# Aggregate stack by sentinel bands
composite_bands <- function(sen_stack, custom_extent) {

  cat("Creating composite rasters...\n")
  
  # Determine list of unique band names
  band_names <- unique(str_extract(names(sen_stack), "BOA_[:digit:]{1,2}\\.[:digit:]{1,2}$"))
  
  extent_path <- get_study_extent_path(custom_extent = custom_extent)
  extent <- readOGR(extent_path) %>% 
    spTransform(CRSobj = crs(sen_stack))  

  stack_pct_na <- pblapply(band_names, function(band) {
    
    s <- subset(sen_stack, grep(paste0(band, "$"), names(sen_stack)))
    values(s)[values(s) == 0] <- NA
    
    if(nlayers(s) > 1) {
      r <- calc(s, fun = median, na.rm = T)  
    } else {
      r <- s
    }
    
    names(r) <- paste0(city_name, ".", band)
    
    writeRaster(r, filename = paste0("./data/sentinel-2/sentinel-processed/", names(r), ".tif"),
                format = "GTiff",
                overwrite = T)
    
    if(custom_extent) {
      layer_pct_na <- raster::extract(r, extent, fun=function(x, ...) length(na.omit(x))/length(x))
      layer_pct_na <- 100*(1-layer_pct_na[1,1])
    } else {
      layer_pct_na <- 100*(freq(r, value = NA)/ncell(r))
    }
    return(layer_pct_na)
  }
  ,cl = detectCores()-1
  )
  return(stack_pct_na)
}
```

**Expected and actual behavior**

Expected behavior is successful download of requested sentinel data. I haven't had success yet since this issue began.

Actual behavior is:

```
[2021-02-23 00:50:30] #### Starting sen2r execution. ####
[2021-02-23 00:50:32] Searching for available SAFE products on SciHub...
[2021-02-23 00:50:47] No SAFE products matching the settings were found.
Error in s2_dt_centroid[, "X"] : no 'dimnames' attribute for array

```

**System information**

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3    tinytex_0.25   xfun_0.17
```
```
> packageVersion("sen2r")
[1] ‘1.4.0’
```
```
> sen2r::load_binpaths()
$gdalinfo
[1] "/usr/bin/gdalinfo"

$gdal_calc
[1] "/usr/bin/gdal_calc.py"

$gdal_fillnodata
[1] "/usr/bin/gdal_fillnodata.py"

attr(,"path")
[1] "/home/esteban/.sen2r/paths.json"
```

**Additional context**
This has happened in three AOIs I tested including the extent from [Issue #368](https://github.com/ranghetti/sen2r/issues/368) (`custom_extent <- [ri-study-extent.zip](https://github.com/ranghetti/sen2r/files/5804958/ri-study-extent.zip`). I can include another study area if needed. 

I tried using `extent = st_as_sfc(st_bbox(st_read(extent_path)))` and it did not make a difference. 

I haven't been able to test the fix to Issue #368 because this issue popped up. As always, many thanks and appreciation for your assistance!

**Comment by estebangatillo** [comment]
AH! I [just noticed you commented](https://github.com/ranghetti/sen2r/issues/383#issuecomment-784245240) on this three hours ago. I re-installed the `sen2r` package, but the error still occurred.

**Comment by ranghetti** [comment]
I see:
```
> packageVersion("sen2r")
[1] ‘1.4.0’
```
As required in #368, before re-launching the code you must install the development version of the package:
```r
install.packages("remotes")
remotes::install_github("ranghetti/sen2r", ref = "devel")
```

**Comment by ranghetti** [comment]
> Last night I ran it and produced the same error. This morning I intended to paste the error report here, but everything crashed before I could copy the output. I ran it back and got a new error:
> 
> ```
> ---------------------------------------------------------------------------------------------------------------------------------------
> [2021-02-26 15:09:41] #### Starting sen2r execution. ####
> [2021-02-26 15:09:42] Searching for available SAFE products on SciHub...
> [2021-02-26 15:09:53] Computing output names...
> [2021-02-26 15:09:54] Starting to download the required level-2A SAFE products.
> [2021-02-26 15:09:54] Check if products are available for download...
> [2021-02-26 15:09:54] Downloading Sentinel-2 image 1 of 1
>             (S2B_MSIL2A_20200820T153819_N0214_R011_T19TCF_20200820T195324.SAFE)...
>   |===================================================================================================================================| 100%
> [2021-02-26 15:10:38] Download of level-2A SAFE products terminated.
> [2021-02-26 15:10:38] Starting to download the required level-1C SAFE products.
> No L1C images are needed.
> [2021-02-26 15:10:38] Download of level-1C SAFE products terminated.
> [2021-02-26 15:10:38] Updating output names...
> [2021-02-26 15:10:39] Starting to translate SAFE products in custom format.
> Using UTM zone 19N.
> 1 output files were correctly created.
> [2021-02-26 15:10:39] Starting to merge tiles by orbit.
> Using projection "EPSG:32619".
> [2021-02-26 15:10:40] Starting to edit geometry (clip, reproject, rescale).
> <simpleError in if (is.na(x)) NA_crs_ else if (inherits(x, "crs")) x else if (is.character(x)) {    if (grepl("+init=epsg:", x) && sf_extSoftVersion()[["proj.4"]] >=         "6.0.0" && sf_extSoftVersion()[["proj.4"]] < "6.3.1") {        x = strsplit(x, " ")[[1]]        if (length(x) > 1)             warning(paste("the following proj4string elements are ignored:",                 paste(x[-1], collapse = " "), "; remove the +init=epsg:XXXX to undo this"))        x = paste0("EPSG:", as.integer(substr(x[1], 12, 20)))    }    CPL_crs_from_input(x)} else stop(paste("cannot create a crs from an object of class",     class(x)), call. = FALSE): argument is of length zero>
> Error in { : 
>   task 1 failed - "task 1 failed - "task 1 failed - "argument is of length zero"""
> In addition: Warning messages:
> 1: 'geojsonlint' not installed, skipping GeoJSON linting 
> 2: 'geojsonlint' not installed, skipping GeoJSON linting 
> 3: 'geojsonlint' not installed, skipping GeoJSON linting 
> 4: 'geojsonlint' not installed, skipping GeoJSON linting 
> 5: 'geojsonlint' not installed, skipping GeoJSON linting 
> 6: 'geojsonlint' not installed, skipping GeoJSON linting 
> ```
> 
> PS - made sure to install dev from github this time....

I cannot reproduce this error (your example runs correctly on my system).

It seems an error related to {sf}. What is the output of the following code?
```r
packageVersion("sf")
sf:extSoftVersion()
```
Retry after updating {sf} and {sen2r}:
```r
install.packages(c("sf","sen2r"))
packageVersion("sen2r") # it must be 1.4.1 - I recently updated it on CRAN
packageVersion("sf") # it must be 0.9-7
```
Then, relaunch your code setting `overwrite = TRUE`.

**Comment by estebangatillo** [comment]
Here are outputs from version functions:

```
> packageVersion("sf")
[1] ‘0.9.7’
> packageVersion("sen2r")
[1] ‘1.4.1.9001’
> sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.8.0"        "3.0.4"        "7.0.0"         "true"         "true" 
```

Good to hear it's working on your end! I am still getting this error:

```
[2021-03-02 19:34:23] Starting to translate SAFE products in custom format.
Using UTM zone 19N.
1 output files were correctly created.
[2021-03-02 19:34:23] Starting to merge tiles by orbit.
Using projection "EPSG:32619".
[2021-03-02 19:34:23] Starting to edit geometry (clip, reproject, rescale).
<simpleError in if (is.na(x)) NA_crs_ else if (inherits(x, "crs")) x else if (is.character(x)) {    if (grepl("+init=epsg:", x) && sf_extSoftVersion()[["proj.4"]] >=         "6.0.0" && sf_extSoftVersion()[["proj.4"]] < "6.3.1") {        x = strsplit(x, " ")[[1]]        if (length(x) > 1)             warning(paste("the following proj4string elements are ignored:",                 paste(x[-1], collapse = " "), "; remove the +init=epsg:XXXX to undo this"))        x = paste0("EPSG:", as.integer(substr(x[1], 12, 20)))    }    CPL_crs_from_input(x)} else stop(paste("cannot create a crs from an object of class",     class(x)), call. = FALSE): argument is of length zero>
Error in { : 
  task 1 failed - "task 1 failed - "task 1 failed - "argument is of length zero"""
```

I will continue to troubleshoot on my end, and, as always, thank you very much for your assistance!

**Comment by estebangatillo** [comment]
Update: I've regressed back to the original error. I used the dev version and the newest cran version.

Version 1.4.1:

```
[2021-03-02 21:26:58] #### sen2r session terminated. ####
The processing chain can be re-launched with the command:
  sen2r("/home/esteban/.sen2r/proc_par/s2proc_20210302_211941.json")
Error in compareRaster(rasters) : different extent
In addition: Warning messages:
1: 'geojsonlint' not installed, skipping GeoJSON linting 
2: 'geojsonlint' not installed, skipping GeoJSON linting 
> packageVersion("sen2r") # it must be 1.4.1 - I recently updated it on CRAN
[1] '1.4.1'
> packageVersion("sf") # it must be 0.9-7
[1] '0.9.7'
```

Dev version:

```
[2021-03-02 21:39:54] #### sen2r session terminated. ####
The processing chain can be re-launched with the command:
  sen2r("/home/esteban/.sen2r/proc_par/s2proc_20210302_213232.json")
Error in compareRaster(rasters) : different extent
In addition: Warning messages:
1: 'geojsonlint' not installed, skipping GeoJSON linting 
2: 'geojsonlint' not installed, skipping GeoJSON linting 
> packageVersion("sen2r") # it must be 1.4.1 - I recently updated it on CRAN
[1] '1.4.1.9001'
> packageVersion("sf") # it must be 0.9-7
[1] '0.9.7'
```

**Comment by ranghetti** [comment]
Changes in the output (different errors for different runs) may suggest that the content of the output folder could affect the results.

Let us try being sure to run the same example. The following code includes an extract of your code with a simple, fully reproducible example:

```r
path_safe <- tempfile()
path_out <- tempfile()

download.file(
  "https://github.com/ranghetti/sen2r/files/5804958/ri-study-extent.zip",
  zip_path <- tempfile(fileext = ".zip")
)
unzip(zip_path, exdir = tempdir())
custom_extent <- readRDS(file.path(tempdir(), "ri-study-extent.RDS"))

sen2r(
  gui = FALSE, 
  timewindow = c("2020-07-15", "2020-08-12"),
  extent = custom_extent,
  extent_name = "rhode-island-2",
  list_prods = c("BOA"),
  max_cloud_safe = 3,
  max_mask = 100,
  mask_type = NA,
  res_s2 = "10m",
  online = TRUE,
  extent_as_mask = TRUE,
  parallel = FALSE,
  processing_order = "3",
  step_atmcorr = "l2a",
  overwrite = TRUE,
  overwrite_safe = FALSE,
  rm_safe = "no",
  path_l1c = path_safe, path_l2a = path_safe,
  path_out = path_out
)
```

Try to reproduce it and let me know if you can run it correctly.

**Comment by estebangatillo** [comment]
This seems like some progress! Still problems though. Going back to the beginning - the crux of the issue was the different zones. Here is my original error and output:

```
Error in compareRaster(rasters) : different extent
In addition: Warning message:
'geojsonlint' not installed, skipping GeoJSON linting 
> # Create list of sentinel-2 processed raster files
> sen_files <- list.files("./data/sentinel-2/sen2r-out/BOA", "\\.tif$", full.names = T)
> readandproject <- function(filenames){
+   lapply(filenames, function(filename){
+     r = raster(filename)
+     crs(r) 
+     return(r)
+   }
+   )
+ }
> readandproject(filenames = sen_files)
[[1]]
class      : RasterLayer 
band       : 1  (of  11  bands)
dimensions : 10068, 7719, 77714892  (nrow, ncol, ncell)
resolution : 10, 10  (x, y)
extent     : 753510, 830700, 4561210, 4661890  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=18 +datum=WGS84 +units=m +no_defs 
source     : /home/esteban/uhi/rhode-island-2/data/sentinel-2/sen2r-out/BOA/S2A2A_20200805_011_rhode-island-2_BOA_10.tif 
names      : S2A2A_20200805_011_rhode.island.2_BOA_10 
values     : 0, 65535  (min, max)
[[2]]
class      : RasterLayer 
band       : 1  (of  11  bands)
dimensions : 10068, 7719, 77714892  (nrow, ncol, ncell)
resolution : 10, 10  (x, y)
extent     : 753510, 830700, 4561210, 4661890  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=18 +datum=WGS84 +units=m +no_defs 
source     : /home/esteban/uhi/rhode-island-2/data/sentinel-2/sen2r-out/BOA/S2B2A_20200718_111_rhode-island-2_BOA_10.tif 
names      : S2B2A_20200718_111_rhode.island.2_BOA_10 
values     : 0, 65535  (min, max)
[[3]]
class      : RasterLayer 
band       : 1  (of  11  bands)
dimensions : 10068, 7719, 77714892  (nrow, ncol, ncell)
resolution : 10, 10  (x, y)
extent     : 753510, 830700, 4561210, 4661890  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=18 +datum=WGS84 +units=m +no_defs 
source     : /home/esteban/uhi/rhode-island-2/data/sentinel-2/sen2r-out/BOA/S2B2A_20200721_011_rhode-island-2_BOA_10.tif 
names      : S2B2A_20200721_011_rhode.island.2_BOA_10 
values     : 0, 65535  (min, max)
[[4]]
class      : RasterLayer 
band       : 1  (of  11  bands)
dimensions : 9981, 7603, 75885543  (nrow, ncol, ncell)
resolution : 10, 10  (x, y)
extent     : 253580, 329610, 4558730, 4658540  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=19 +datum=WGS84 +units=m +no_defs 
source     : /home/esteban/uhi/rhode-island-2/data/sentinel-2/sen2r-out/BOA/S2B2A_20200728_111_rhode-island-2_BOA_10.tif 
names      : S2B2A_20200728_111_rhode.island.2_BOA_10 
values     : 0, 65535  (min, max)
[[5]]
class      : RasterLayer 
band       : 1  (of  11  bands)
dimensions : 9981, 7603, 75885543  (nrow, ncol, ncell)
resolution : 10, 10  (x, y)
extent     : 253580, 329610, 4558730, 4658540  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=19 +datum=WGS84 +units=m +no_defs 
source     : /home/esteban/uhi/rhode-island-2/data/sentinel-2/sen2r-out/BOA/S2B2A_20200810_011_rhode-island-2_BOA_10.tif 
names      : S2B2A_20200810_011_rhode.island.2_BOA_10 
values     : 0, 65535  (min, max)
```

We can see the zones are different and there's differences in dimensions and extent. Ultimately, I'm going to stack these all up to  pull mean values by each band from each `path_out` raster. Your fix got these rasters all in the same zone (thank you)! However, there were still minor discrepancies in the dimensions and extent:

```
> readandproject <- function(filenames){
+     lapply(filenames, function(filename){
+         r = raster(filename)
+         crs(r) 
+         return(r)
+       }
+       )
+  }
> readandproject(filenames = sen_files)
[[1]]
class      : RasterLayer 
band       : 1  (of  11  bands)
dimensions : 9684, 7395, 71613180  (nrow, ncol, ncell)
resolution : 9.992921, 9.992921  (x, y)
extent     : 254103, 328000.6, 4560447, 4657218  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=19 +datum=WGS84 +units=m +no_defs 
source     : C:/Users/vs/Desktop/UHI/rhode-island-testing/luigis_method/BOA/S2A2A_20200805_011_rhode-island-2_BOA_10.tif 
names      : S2A2A_20200805_011_rhode.island.2_BOA_10 
values     : 0, 6836  (min, max)


[[2]]
class      : RasterLayer 
band       : 1  (of  11  bands)
dimensions : 9684, 7394, 71603496  (nrow, ncol, ncell)
resolution : 9.99315, 9.99315  (x, y)
extent     : 254104.4, 327993.8, 4560446, 4657220  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=19 +datum=WGS84 +units=m +no_defs 
source     : C:/Users/vs/Desktop/UHI/rhode-island-testing/luigis_method/BOA/S2B2A_20200718_111_rhode-island-2_BOA_10.tif 
names      : S2B2A_20200718_111_rhode.island.2_BOA_10 
values     : 0, 65535  (min, max)


[[3]]
class      : RasterLayer 
band       : 1  (of  11  bands)
dimensions : 9677, 7389, 71503353  (nrow, ncol, ncell)
resolution : 9.999659, 9.999659  (x, y)
extent     : 254105, 327992.5, 4560450, 4657216  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=19 +datum=WGS84 +units=m +no_defs 
source     : C:/Users/vs/Desktop/UHI/rhode-island-testing/luigis_method/BOA/S2B2A_20200721_011_rhode-island-2_BOA_10.tif 
names      : S2B2A_20200721_011_rhode.island.2_BOA_10 
values     : 0, 65535  (min, max)


[[4]]
class      : RasterLayer 
band       : 1  (of  11  bands)
dimensions : 9677, 7389, 71503353  (nrow, ncol, ncell)
resolution : 10, 10  (x, y)
extent     : 254110, 328000, 4560450, 4657220  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=19 +datum=WGS84 +units=m +no_defs 
source     : C:/Users/vs/Desktop/UHI/rhode-island-testing/luigis_method/BOA/S2B2A_20200728_111_rhode-island-2_BOA_10.tif 
names      : S2B2A_20200728_111_rhode.island.2_BOA_10 
values     : 0, 65535  (min, max)


[[5]]
class      : RasterLayer 
band       : 1  (of  11  bands)
dimensions : 9677, 7389, 71503353  (nrow, ncol, ncell)
resolution : 10, 10  (x, y)
extent     : 254110, 328000, 4560450, 4657220  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=19 +datum=WGS84 +units=m +no_defs 
source     : C:/Users/vs/Desktop/UHI/rhode-island-testing/luigis_method/BOA/S2B2A_20200810_011_rhode-island-2_BOA_10.tif 
names      : S2B2A_20200810_011_rhode.island.2_BOA_10 
values     : 0, 65535  (min, max)
```

Thinking this was the main problem, I forced the rasters to all have the same extent and dimensions, and this worked:

```
# Brick all the bands from the first BOA tif.
s1 <- brick(sen_files[1])

# Grab a single raster from the 5th tif (this is the best example it seems)
s5 <- raster(sen_files[5])

# Resample over the brick
s1_brick_resamp <- resample(s1, s5, method = 'bilinear')
```

But when I got an output I realized the original call to `sen2r` missed a large section of the AOI. Here is a clip for quick, easy visualization:

![image](https://user-images.githubusercontent.com/52689748/110220800-f0725000-7e7c-11eb-9ef1-4eab730ea8e2.png)

For more details, using your example, SAFE files are downloaded on 7/18, 7/21, 7/28, 8/5 and 8/10 of 2020:
![image](https://user-images.githubusercontent.com/52689748/110220774-b739e000-7e7c-11eb-958f-808f3f686e26.png)


This results in the output of 5 BOA .tifs: one for each day:
![image](https://user-images.githubusercontent.com/52689748/110220783-c9b41980-7e7c-11eb-858e-91f45e88854c.png)



I'm working on tweaking the simple, fully reproducible example you shared to see if I can get full coverage. As always, thank you very much for your help! It seems like you made a big fix, and I think I might be close to a final product. Your input, suggestions, and assistance has been very helpful. If there is something you think I missed I will make that fix!

**Comment by estebangatillo** [comment]
I think I understand, however, this is causing a substantial issue on my end. Partial coverage of the AOI is causing unequal values across the AOI and these unequal values cause serious issues in my analysis. I've tried to dig through Sentinel documentation, SAFE products, and outputs, but I haven't found any solutions. Here are some visuals of the issue:

Two tiles come together with different values despite having been collected on the same day at the same time:
![image](https://user-images.githubusercontent.com/52689748/112030750-cfa22f80-8af7-11eb-9546-67c7c123f59d.png)

Tile(s) have bands running through them?
![image](https://user-images.githubusercontent.com/52689748/112031270-6111a180-8af8-11eb-9cd7-6ad2c68dd199.png)

Because of these (and other) discrepancies the final product stitches together very poorly:
![image](https://user-images.githubusercontent.com/52689748/112031441-94543080-8af8-11eb-8e11-ed366730ac54.png)

I've run this exact same code in other places including for a larger area around Seattle, Washington, and did not have this issue. Seattle lies squarely within one tile, and all the `path_out` .tifs cover the same exact area. I'm exploring other products acquired to determine if I've had this issue before without noticing. Usually the AOI is much smaller so I don't think this has ever been an issue before.

Do you know why this is occurring? Do I need to write some sort of normalization code to get more equal values across the AOI? Or is the something else I'm doing wrong? As always, thank you for your assistance and patience!

PS - To clarify, these issues were generated using the [simplified code you recommended](https://github.com/ranghetti/sen2r/issues/387#issuecomment-789478689) earlier this month.

**Comment by ranghetti** [comment]
This is quite surely due to discrepances among input data, so not related with {sen2r}: in this case, I cannot help you (I am not responsible on data release).
To be sure of that you can open input jp2 bands included in SAFE archives and compare them.

If you would notice that they are not related to input data, open a **new issue** (this problem is not related with previous one, every problem have to be reported in a separated issue). Follow the "Help needed" template, _**including the _reproducible_ code (code, extent, all I can launch and reproduce) which you used**_ (I cannot deepen problems from screenshots).

**Comment by estebangatillo** [comment]
Yes, I agree with you on the input data discrepancies. I've contacted Copernicus support. Thank you for confirmation! If I find other issues I will open a new issue and follow the template.

**Comment by ranghetti** [comment]
Just an idea: check the corresponding L1C images, maybe the problem is ude to different Sen2Cor parameters used to produce L2A.
