### ISSUE TITLE
Missing units::ud_units

### ISSUE THREAD

**Issue by Enchufa2** [ranghetti/sen2r#390]
We have released a new version of package `units`, which removes some long-deprecated stuff. We did extensive revdep checks, and yet those didn't catch this problem in `sen2r`, so apologies for that. Now we have been notified that `sen2r` checks are failing on CRAN due to the usage of the `units::ud_units`, which has been finally removed.

The recommended fix is to substitute the two instances of `units::ud_units$m^2` in your code with `units::as_units("m^2")` (and the same for similar usages that I may have not identified).

Again, apologies for such a short (late, in fact) notice.

**Comment by ranghetti** [comment]
Thanks for reporting that; I fixed it in 82754724fd3259b12ea1aee57a5242cfcec8438d (I will release a new CRAN version shortly).
