### ISSUE TITLE
Problem with ordering sentinel image from LTA

### ISSUE THREAD

**Issue by tommasojulitta** [ranghetti/sen2r#395]
Dear Ranghetti,
First of all congratulation for the great tools you developed.
I was using it in the last months with no problem and was making the life much more easy.
In the last month I'm facing some issues when I try to get sentinel images from the LTA (for data collected in teh last year no problem).
As reported in issue #381 I was installing the package also from github, and tried also with "service = "dhus" " option. In the last weeks there were some problems with the sentinel hub related to sentinel-2 products in the LTA. Nevertheless, it seems that now is fixed from ESA side and is possible to order them using the Copernicus open access hub again. 
I tested this using different user credentials to avoid the problem of user quota, and trying to download images related to different areas and over different time window. Therefore is not easy to give examples.
When I'm ordering from the LTA using the Copernicus Open Access Hub and realunch sen2r is working, So it seems is something related to the ordering process in sen2r. Can it be?
Thanks

Tommaso

**Comment by ranghetti** [comment]
Dear Tommaso,
I understand that granting reproducibility is not easy dealing with SAFE orders, but without any example I can not even suppose a possible problem in the ordering process in {sen2r}. Please reopen a new issue and follow all the indications provided in the issue template, including the code you used and the console output you received. Provide also the screenshot of the order performed in the Copernicus Open Access Hub with the same credentials.
