### ISSUE TITLE
Problems downloading SAFE files

### ISSUE THREAD

**Issue by scf89** [ranghetti/sen2r#409]
**Issue description**

I developed a script to download sentinel data automatically every two weeks and it was working well without issues during months but latelly there are errors downloading this data. I saw that there are issues with LTA but in this case it shouldn't be that problem because I download data of the last two weeks. My script takes many shapefiles as extension for downloading for the last two weeks and I use a 'for' loop so I take the first extension for downloading, after that the next and so forth. But latelly with some of these extensions it can´t downoad the SAFE file

**Expected and actual behavior**

```
[2021-05-15 14:16:16] #### Starting sen2r execution. ####
[2021-05-15 14:16:16] Searching for available SAFE products on SciHub...
although coordinates are longitude/latitude, st_union assumes that they are planar
[2021-05-15 14:16:19] Computing output names...
[2021-05-15 14:16:20] Starting to download the required level-2A SAFE products.
[2021-05-15 14:16:20] Check if products are available for download...
[2021-05-15 14:16:20] Downloading Sentinel-2 image 1 of 1
         (S2B_MSIL2A_20210506T110619_N0300_R137_T29TQF_20210506T141053.SAFE)...
Request failed [500]. Retrying in 1 seconds...
Request failed [500]. Retrying in 1.3 seconds...
Request failed [500]. Retrying in 6.2 seconds...
Request failed [500]. Retrying in 4.5 seconds...
Error in { : task 1 failed - "task 1 failed - "task 1 failed - "
Download of file S2B_MSIL2A_20210506T110619_N0300_R137_T29TQF_20210506T141053.SAFE was incomplete
(Md5sum check failed). Please retry to launch the download."""
...
```

The normal behavior shouldn't throw a request failed error as I was running this script several times during months without problems until now

**Comment by markolipka** [comment]
Hi, I can confirm this:

`Error in { : task 1 failed - "
Download of file S2A_MSIL2A_20170706T102021_N0205_R065_T32UPE_20170706T102301.SAFE was incomplete
(Md5sum check failed). Please retry to launch the download." `

**Comment by ranghetti** [comment]
I did not encounter any error to download product S2B_MSIL2A_20210506T110619_N0300_R137_T29TQF_20210506T141053.SAFE. If you need assistance, I need information about your use case which you did not provide. In this case, plrease open a new issue **_carefully following_** the indications of the issue template, and providing all the required information (in your case, the reproducible example should be the specific chunk of code returning this error, not the whole script).

**Comment by ranghetti** [comment]
@markolipka this is a different problem, your SAFE is unavailable on the server side, so sen2r cannot dowload it. You must report your problem to the Copernicus assistance.

**Comment by markolipka** [comment]
Thanks for your comment,

in fact it is not the only product I am unable to download (tried the whole weekend). Maybe this 

<img width="967" alt="Screenshot 2021-05-17 at 10 59 42" src="https://user-images.githubusercontent.com/9739839/118462631-2cd4ee80-b6ff-11eb-812d-b69676a4f6ae.png">

is the reason? I'll wait a while and try again. 

Thanks for the great package!
