### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by chenxi-en** [ranghetti/sen2r#410]
images_list <- s2_list(
+     spatial_extent = samplecrops_poly,
+     time_interval = as.Date(c("2017-01-01", "2020-12-30")),
+     max_cloud = 1
+ )
> s2_download (
+     s2_prodlist = images_list,
+     downloader = "builtin",
+     apihub = NA,
+     service = NA,
+     outdir = ".",
+     order_lta = TRUE,
+     abort = TRUE,
+     overwrite = FALSE
+ )
[2021-05-17 18:51:27] Check if products are available for download...
[2021-05-17 18:53:32] Ordering 213 Sentinel-2 images stored in the Long Term Archive...
Request failed [503]. Retrying in 1 seconds...
Request failed [503]. Retrying in 1 seconds...
Request failed [503]. Retrying in 1.6 seconds...
Request failed [503]. Retrying in 1 seconds...
Request failed [503]. Retrying in 1.4 seconds...
Request failed [503]. Retrying in 1 seconds...
Request failed [503]. Retrying in 1.1 seconds...
Request failed [503]. Retrying in 2.7 seconds...
Request failed [503]. Retrying in 1.3 seconds...
Request failed [503]. Retrying in 3.8 seconds...
Request failed [503]. Retrying in 1 seconds...
Request failed [503]. Retrying in 3.6 seconds...
Request failed [503]. Retrying in 1 seconds...

**Comment by ranghetti** [comment]
See https://scihub.copernicus.eu/userguide/LongTermArchive:

> The LTA archives cannot accept new requests since they are busy in handling other requests. In this case the user has to retry to submit the request in a second moment in time.
