### ISSUE TITLE
sentinel resolution correction

### ISSUE THREAD

**Issue by fiastros** [ranghetti/sen2r#414]
The library works really well, the gui is really well done. it's now simple to download and process sentinel images. 
I just have question: using the gui i was able to obtain a raster (.tiff) containing the ndvi indice of a farm field the only, the issue is that the resolution is actually not good: the field is pixelized 

![image](https://user-images.githubusercontent.com/48684791/123982065-0921eb00-d9c3-11eb-9aec-c64c4dc53c64.png)

Is there a way to improve the resolution of my ouput or at least get something get something more visible? ( maybe doing some image treatment, or maybe by changing my setting? )

My the settings are : 
-   BOA (bottom of the atmosphere) , 
-  Sentinel-2a and sentinel-2b (no accessory layers)
-  Esa 
- use Aria2
- Use Sen2Cor only for level-2A products not available locally or online
- No topographic correction
- output format : GeoTiff 
- High (deflate) output compression
- spatial resolution: 10m
- resampling method: Nearest neighbour
- Data type: integer (16 bits)

**Comment by ranghetti** [comment]
Thank you for your appreciation.
You can set an output resolution finer than 10m (e.g. 2m) and a different resampling method (e.g. cubic), so to obtain a blurry effect instead than pixelised. But notice that you cannot obtain a "real" output resolution better than the one of the input data source.
