### ISSUE TITLE
Cropping exactly arround polygon

### ISSUE THREAD

**Issue by fiastros** [ranghetti/sen2r#416]
Hi again, 

i was wondering if it was possible to crop the raster map precisely around a polygon. 
i first tried the option given by sen2r() to crop but the ouput isn't really around my polygon (see the image below): 
![Capture d’écran du 2021-07-07 11-29-19](https://user-images.githubusercontent.com/48684791/124738103-e3dc3200-df18-11eb-83e6-e296ea55c614.png)

So i've tried processing the raster myself using rgdal on rstudio, it's just a littlme bit better but it's still doesn't follow perfectly the shape : 
![Capture d’écran du 2021-07-07 11-30-46](https://user-images.githubusercontent.com/48684791/124738286-0f5f1c80-df19-11eb-91be-477e1f996fbb.png)

And so i was wondering if anyone knows how to crop that raster file to the exact shape of my polygon ?

**Comment by ranghetti** [comment]
First crop is done following boundaries of original Sentinel-2 pixels (10m); second one following the geometry of the output resolution. Pixels are the minimum unit of a raster (as well of any digital image), so thy can not be cropped to follow a polygon boundary.

Ps. this general question is not related with sen2r; please use the {sen2r} issues to receive assistance on topics related to sen2r, _following the indications in the issue template_. For general questions on geospatial theory you should use different instruments (e.g. StackOverflow), where there is a wider community which can provide you better assistance.
