### ISSUE TITLE
Problems accessing SAFE archives (invalid ZIP files) solved by provider?

### ISSUE THREAD

**Issue by estebangatillo** [ranghetti/sen2r#419]
Shortly before [you closed issue 406](https://github.com/ranghetti/sen2r/issues/406#issuecomment-880431449) I received an email from EO Support stating 
```
We would like to inform you that the LTA retrieval issue has been solved on 1st July as per news published on the Copernicus Open Access Hub website at https://scihub.copernicus.eu/news/News00898.  

Therefore, you are now welcome to use again the Copernicus Open Access Hub to retrieve Sentinel data from the LTA, as you should no longer experience any corrupted products following restoration.
```

Has `sen2r` changed to reflect this update? Does `sen2r` still access google cloud if products are not available in LTA? If google cloud is still applied will this be the standard from now on?

Thank you much!

**Comment by ranghetti** [comment]
Thank you for reporting this news, we hope the problem to be actually fixed.

Regarding sen2r, there is not the neeeding to change anything. The default behaviour never changed (Google Cloud is not used by default), so SciHub is always used unless the user explicitly asked to use Google Cloud.
