### ISSUE TITLE
Cloud coverage of an area of interest

### ISSUE THREAD

**Issue by fiastros** [ranghetti/sen2r#420]
Hello sir Ranghetti, 

I was wondering if it was possible top get the cloud coverage of an area of interest ? 
i saw that by using the  function "safe_getMedadata" it was possible to extract the cloud info but for a tile. 
I checked all the issues but i didn't see one that was answering this question (unless i maybe didn't notice it...)
I don't know if this will make sense, but an idea i had was to first get a SCL then maybe from there i could figure out a way to extract the cloud coverage, shadow coverage. 
I'm  trying to include these values for analytics because i think they can be good indicators of the quality of the ndvi map created for example. 

Thank you for your time sir.

**Comment by fiastros** [comment]
ye

**Comment by ranghetti** [comment]
I suppose you solved, since you closed the issue. For future reference, this can be done using the function [`s2_perc_masked()`](https://sen2r.ranghetti.info/reference/s2_mask.html).

**Comment by fiastros** [comment]
@ranghetti , thanks for the reply ! i i hadn't seen that function, so i'm going to try that out. 
What i had done was: produce an scl of a field, and then i count the number of pixels classified as (cloud+ shadow+snow+ thin_cirrus) divided by the total number of pixels * 100. and i used this as my indicator.
