### ISSUE TITLE
Problem when executing successively the commands 'check_sen2r_deps()' and 'sen2r()' in a script that is "sourced"

### ISSUE THREAD

**Issue by lovalery** [ranghetti/sen2r#422]
**Issue description**

Hello,
I am currently experiencing a problem when I source my script: the successive execution of the commands check_sen2r_deps() and sen2r() does not work properly. The problem occurs when closing the window opened by the check_sen2r_deps() command with the "close" button. The close button seems to close the internet connection and when the script executes the sen2r() command, the connection does not open anymore and I get the following message:
[2021-09-03 20:44:42] Launching GUI...

Listening on http://127.0.0.1:7292
[2021-09-03 20:44:42] Program interrupted by the user (GUI closed).

On the other hand, I noticed that if you close the window opened by the check_sen2r_deps() command with the little cross in the top right corner of the window, the connection does not seem to be broken and the sen2r command runs normally and opens the GUI. That's said, it is not a very good solution : whether the window opened by the check_sen2r_depends() command is closed with the "close" button or with the cross in the upper right corner of the window, it would be nice if the internet connection was not broken so that the sen2r command runs correctly in any case when sourcing the script.

I thank you in advance for the advice you could give me to help finding a solution and  remain at your disposal if you need more information.
Cheers

**Reproducible example**

```r
## PLEASE DELETE AND WRITE YOUR OWN
library(sen2r)
example_extent <- "C:/path/of/the/file/example.shp"
# file example.shp _must_ be attached if not available online
output <- sen2r("/path/of/the/parameter_file.json")
# file parameter_file.json _must_ be attached of copied as text
```

**Expected and actual behavior**

```
## PLEASE DELETE AND WRITE YOUR OWN OUTPUT
[2020-12-21 16:17:01] #### Starting sen2r execution. ####
[2020-12-21 16:17:02] Searching for available SAFE products on SciHub...
[2020-12-21 16:17:10] Computing output names...
...
```

**System information**

```
# PASTE HERE YOUR OUTPUT
```

**Additional context**

**Scientific publication**

**Comment by ranghetti** [comment]
Hello,
very strange problem. I can exclude that sen2r functions would directly be able to affect internet connection. Maybe this is a problem related to Shiny interface (for which I can not give assistance) or to RStudio, if you are using it, but I think to be very sistem-dependent.

You did not provide system information:
```
**System information**
<!-- Provide here the output of the following R commands:
sessionInfo()
packageVersion("sen2r")
sen2r::load_binpaths()
```

Are you using RStudio? If so, does this problem occur also launching sen2r from plain R?

**Comment by lovalery** [comment]
Hello,
Thank you very much for your feedback.
Yes, I am using the latest version of RStudio (i.e. Version 1.4.1717).
I just did the test from plain R and I noticed the same behavior as described in my first post.

I think the problem comes from shiny because I found a workaround (not very clean, but it works!): between the commands check_sen2r_depends() and sen2r(), I detach then reattach "shiny" and it's o.k.

**Comment by ranghetti** [comment]
I would suggest to try to reproduce this problem with some Shiny sample GUIs: if you will able to do so it will be easier to report the problem to [rstudio/shiny](https://github.com/rstudio/shiny/issues).

**Comment by lovalery** [comment]
Thanks for the hint. I will try to reproduce the problem with their sample GUIs before submitting my request.

**Comment by ranghetti** [comment]
[keeping open until edits will be checked against tests and pulled on master branch]
