### ISSUE TITLE
Problem with downloading L2A.safe files from Google Cloud 

### ISSUE THREAD

**Issue by naeem32567** [ranghetti/sen2r#425]
**Issue description**

Trying to run the vignette at http://sen2r.ranghetti.info/articles/sen2r_cmd.html to download L2A.safe files from Google Cloud Sentinel 2 bucket. On querying the google cloud bucket  I receive the following error ... InvalidUrlError: Unrecognized scheme "y" 

**Reproducible example**

```r
# Set paths
out_dir_1  <- "Y:\\Satellite\\sentinel2\\n_rhm\\2_Development\\TEST" # output folder
safe_dir <- "Y:\\Satellite\\sentinel2\\n_rhm\\2_Development\\TEST" # output folder

myextent_1 <- system.file("extdata/vector/barbellino.geojson", package = "sen2r") 

library(sen2r)
out_paths_1 <- sen2r(
  gui = FALSE,
  step_atmcorr = "l2a",
  s2_levels = "l2a",
  server = "gcloud",
  extent = myextent_1,
  extent_name = "Barbellino",
  timewindow = c(as.Date("2020-11-13"), as.Date("2020-11-25")),
  list_prods = c("BOA","SCL"),
  list_indices = c("NDVI","MSAVI2"),
  list_rgb = c("RGB432B"),
  mask_type = "cloud_and_shadow",
  max_mask = 10, 
  path_l2a = safe_dir,
  path_out = out_dir_1
)
```

**Expected and actual behavior**

```
[2021-09-14 12:44:30] #### Starting sen2r execution. ####
[2021-09-14 12:44:32] Searching for available SAFE products...
old-style crs object detected; please recreate object with a recent sf::st_crs()
old-style crs object detected; please recreate object with a recent sf::st_crs()
[2021-09-14 12:44:34] Querying Google Cloud (this can take a very long time)...
  |                                                                                                                                      |   0%InvalidUrlError: Unrecognized scheme "y".
  |=================                                                                                                                     |  12%InvalidUrlError: Unrecognized scheme "y".
  |==================================                                                                                                    |  25%InvalidUrlError: Unrecognized scheme "y".
  |==================================================                                                                                    |  38%InvalidUrlError: Unrecognized scheme "y".
  |===================================================================                                                                   |  50%InvalidUrlError: Unrecognized scheme "y".
  |====================================================================================                                                  |  62%InvalidUrlError: Unrecognized scheme "y".
  |====================================================================================================                                  |  75%InvalidUrlError: Unrecognized scheme "y".
  |=====================================================================================================================                 |  88%InvalidUrlError: Unrecognized scheme "y".
  |======================================================================================================================================| 100%Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘saveXML’ for signature ‘"NULL"’
In addition: Warning messages:
1: 'geojsonlint' not installed, skipping GeoJSON linting 
2: XML content does not seem to be XML: 'ile98304eb84720.xml' 
3: XML content does not seem to be XML: 'ile98301d2b6a26.xml' 
4: XML content does not seem to be XML: 'ile98307d4f6064.xml' 
5: XML content does not seem to be XML: 'ile9830354077.xml' 
6: XML content does not seem to be XML: 'ile98306f42608d.xml' 
7: XML content does not seem to be XML: 'ile98302e1a489a.xml' 
8: XML content does not seem to be XML: 'ile9830249d6330.xml' 
9: XML content does not seem to be XML: 'ile983039ec49f9.xml' 
...
```

**System information**

```
> is_gcloud_configured()
[1] TRUE
> system(load_binpaths()$gsutil)
Usage: gsutil [-D] [-DD] [-h header]... [-i service_account] [-m] [-o section:flag=value]... [-q] [-u user_project] [command [opts...] args...]
Available commands:
  acl              Get, set, or change bucket and/or object ACLs
  bucketpolicyonly Configure uniform bucket-level access
  cat              Concatenate object content to stdout
  compose          Concatenate a sequence of objects into a new composite object.
  config           Obtain credentials and create configuration file
  cors             Get or set a CORS JSON document for one or more buckets
  cp               Copy files and objects
  defacl           Get, set, or change default ACL on buckets
  defstorageclass  Get or set the default storage class on buckets
  du               Display object size usage
  hash             Calculate file hashes
  help             Get help about commands and topics
  hmac             CRUD operations on service account HMAC keys.
  iam              Get, set, or change bucket and/or object IAM permissions.
  kms              Configure Cloud KMS encryption
  label            Get, set, or change the label configuration of a bucket.
  lifecycle        Get or set lifecycle configuration for a bucket
  logging          Configure or retrieve logging on buckets
  ls               List providers, buckets, or objects
  mb               Make buckets
  mv               Move/rename objects
  notification     Configure object change notification
  pap              Configure public access prevention
  perfdiag         Run performance diagnostic
  rb               Remove buckets
  requesterpays    Enable or disable requester pays for one or more buckets
  retention        Provides utilities to interact with Retention Policy feature.
  rewrite          Rewrite objects
  rm               Remove objects
  rsync            Synchronize content of two buckets/directories
  setmeta          Set metadata on already uploaded objects
  signurl          Create a signed url
  stat             Display object status
  test             Run gsutil unit/integration tests (for developers)
  ubla             Configure Uniform bucket-level access
  update           Update to the latest gsutil release
  version          Print version info about gsutil
  versioning       Enable or suspend versioning for one or more buckets
  web              Set a main page and/or error page for one or more buckets

Additional help topics:
  acls             Working With Access Control Lists
  crc32c           CRC32C and Installing crcmod
  creds            Credential Types Supporting Various Use Cases
  dev              Contributing Code to gsutil
  encoding         Filename encoding and interoperability problems
  metadata         Working With Object Metadata
  naming           Object and Bucket Naming
  options          Top-Level Command-Line Options
  prod             Scripting Production Transfers
  security         Security and Privacy Considerations
  support          Google Cloud Storage Support
  versions         Object Versioning and Concurrency Control
  wildcards        Wildcard Names

Use gsutil help <command or topic> for detailed help.
[1] 0
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_South Africa.1252  LC_CTYPE=English_South Africa.1252    LC_MONETARY=English_South Africa.1252
[4] LC_NUMERIC=C                          LC_TIME=English_South Africa.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sen2r_1.5.0

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.1   purrr_0.3.4        sf_1.0-2           lattice_0.20-44    V8_3.4.2           vctrs_0.3.8        generics_0.1.0    
 [8] stars_0.5-3        s2_1.0.6           yaml_2.2.1         utf8_1.2.2         XML_3.99-0.7       rlang_0.4.11       e1071_1.7-8       
[15] pillar_1.6.2       foreign_0.8-81     httpcode_0.3.0     glue_1.4.2         DBI_1.1.1          geojsonsf_2.0.1    sp_1.4-5          
[22] wk_0.5.0           foreach_1.5.1      lifecycle_1.0.0    geojsonio_0.9.4    rgeos_0.5-5        raster_3.4-13      RcppTOML_0.1.7    
[29] codetools_0.2-18   doParallel_1.0.16  maptools_1.1-1     parallel_4.1.1     curl_4.3.2         class_7.3-19       fansi_0.5.0       
[36] Rcpp_1.0.7         KernSmooth_2.23-20 classInt_0.4-3     lwgeom_0.2-7       jsonlite_1.7.2     abind_1.4-5        stringi_1.7.4     
[43] dplyr_1.0.7        grid_4.1.1         jqr_1.2.1          rgdal_1.5-23       tools_4.1.1        magrittr_2.0.1     lazyeval_0.2.2    
[50] proxy_0.4-26       geojson_0.3.4      tibble_3.1.4       crul_1.1.0         crayon_1.4.1       pkgconfig_2.0.3    ellipsis_0.3.2    
[57] data.table_1.14.0  httr_1.4.2         iterators_1.0.13   R6_2.5.1           units_0.7-2        compiler_4.1.1    
> packageVersion("sen2r")
[1] ‘1.5.0’
> sen2r::load_binpaths()
$gsutil
[1] "C:\\Users\\User\\AppData\\Local\\Google\\CLOUDS~1\\GOOGLE~1\\bin\\gsutil"

attr(,"path")
[1] "C:\\Users\\User\\DOCUME~1\\SEN2R~1/paths.json"

> check_gcloud()
> check_gcloud_connection()
[1] TRUE
```

**Additional context**

I have setup the google cloud sdk correctly. 

**Scientific publication**

**Comment by ranghetti** [comment]
I can not reproduce the error (all works fine on the Windows machine I used for testing), so I have to ask you some additional information.

First, please run this code chunk and post all the outputs:
```r
binpaths <- load_binpaths()
(x <- "gs://gcp-public-data-sentinel-2/L2/tiles/32/T/NS/S2A_MSIL2A_20201114T101301_N0214_R022_T32TNS_20201114T120346.SAFE/")
system(paste0(binpaths$gsutil," ls ",paste0(x, "GRANULE")), intern = TRUE)
(x1 <- system(paste0(binpaths$gsutil," ls ",paste0(x, "MTD_MSI*.xml")), intern = TRUE))
system(paste0(binpaths$gsutil," -m -q cp -r ",x1[1]," ",x2 <- tempfile(fileext=".xml")))
x2; file.info(x2)

(x_gdal <- strsplit(gdal_utils("info", x2, quiet = TRUE), "\\n")[[1]])
(x_xml <- xmlRoot(htmlTreeParse(x2, useInternalNodes = TRUE))[["body"]][[1]])
(x_foot <- gsub("^ *FOOTPRINT=", "", x_gdal[which(grepl("^ *FOOTPRINT=", x_gdal))][1]))
x_xml[["quality_indicators_info"]][["cloud_coverage_assessment"]][["text"]]
```

**Comment by naeem32567** [comment]
Thanks for looking into the issue. I have posted the all the outputs below. 

> binpaths <- load_binpaths()
> (x <- "gs://gcp-public-data-sentinel-2/L2/tiles/32/T/NS/S2A_MSIL2A_20201114T101301_N0214_R022_T32TNS_20201114T120346.SAFE/")
[1] "gs://gcp-public-data-sentinel-2/L2/tiles/32/T/NS/S2A_MSIL2A_20201114T101301_N0214_R022_T32TNS_20201114T120346.SAFE/"
> system(paste0(binpaths$gsutil," ls ",paste0(x, "GRANULE")), intern = TRUE)
[1] "gs://gcp-public-data-sentinel-2/L2/tiles/32/T/NS/S2A_MSIL2A_20201114T101301_N0214_R022_T32TNS_20201114T120346.SAFE/GRANULE/L2A_T32TNS_A028190_20201114T101418_$folder$"
[2] "gs://gcp-public-data-sentinel-2/L2/tiles/32/T/NS/S2A_MSIL2A_20201114T101301_N0214_R022_T32TNS_20201114T120346.SAFE/GRANULE/L2A_T32TNS_A028190_20201114T101418/"        
> (x1 <- system(paste0(binpaths$gsutil," ls ",paste0(x, "MTD_MSI*.xml")), intern = TRUE))
[1] "gs://gcp-public-data-sentinel-2/L2/tiles/32/T/NS/S2A_MSIL2A_20201114T101301_N0214_R022_T32TNS_20201114T120346.SAFE/MTD_MSIL2A.xml"
> system(paste0(binpaths$gsutil," -m -q cp -r ",x1[1]," ",x2 <- tempfile(fileext=".xml")))
InvalidUrlError: Unrecognized scheme "y".
[1] 1
> x2; file.info(x2)
[1] "Y://Satellite//sentinel2//n_rhm//2_Development//Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file9830728c461c.xml"
                                                                                                                         size isdir mode mtime ctime atime
Y://Satellite//sentinel2//n_rhm//2_Development//Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file9830728c461c.xml   NA    NA <NA>  <NA>  <NA>  <NA>
                                                                                                                          exe
Y://Satellite//sentinel2//n_rhm//2_Development//Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file9830728c461c.xml <NA>
> 
> (x_gdal <- strsplit(gdal_utils("info", x2, quiet = TRUE), "\\n")[[1]])
Error in gdal_utils("info", x2, quiet = TRUE) : 
  could not find function "gdal_utils"
> (x_xml <- xmlRoot(htmlTreeParse(x2, useInternalNodes = TRUE))[["body"]][[1]])
Error in xmlRoot(htmlTreeParse(x2, useInternalNodes = TRUE)) : 
  could not find function "xmlRoot"
> (x_foot <- gsub("^ *FOOTPRINT=", "", x_gdal[which(grepl("^ *FOOTPRINT=", x_gdal))][1]))
Error in is.factor(x) : object 'x_gdal' not found
> x_xml[["quality_indicators_info"]][["cloud_coverage_assessment"]][["text"]]
Error: object 'x_xml' not found

**Comment by ranghetti** [comment]
Your temporary directory is strange (it contains spaces and dashes). What is the output of this?
```r
system(paste0(binpaths$gsutil," -m -q cp -r ",x1[1]," ",x2 <- shortPathName(tempfile(fileext=".xml"))))
x2; file.info(x2)
```

**Comment by naeem32567** [comment]
Yes you are correct. Perhaps the temp dir needs to restored to default. Or reinstall  R and R studio.

> system(paste0(binpaths$gsutil," -m -q cp -r ",x1[1]," ",x2 <- shortPathName(tempfile(fileext=".xml"))))
Error in paste0(binpaths$gsutil, " -m -q cp -r ", x1[1], " ", x2 <- shortPathName(tempfile(fileext = ".xml"))) : 
  object 'binpaths' not found
> x2; file.info(x2)
Error: object 'x2' not found

**Comment by ranghetti** [comment]
Run `binpaths <- load_binpaths()` before the previous chunk (sorry, I supposed you were in the same workspace of the first chunk).

**Comment by naeem32567** [comment]
No worries. Hope this is correct ... 

> binpaths <- load_binpaths()
> system(paste0(binpaths$gsutil," -m -q cp -r ",x1[1]," ",x2 <- shortPathName(tempfile(fileext=".xml"))))
CommandException: No URLs matched: Y:\\Satellite\\sentinel2\\n_rhm\\2_Development\\Raw
CommandException: No URLs matched: sentinel
CommandException: No URLs matched: data
CommandException: Multiple URL strings are not supported with streaming ("-") URLs or named pipes.
CommandException: Destination URL must name a directory, bucket, or bucket
subdirectory for the multiple source form of the cp command.
CommandException: 5 files/objects could not be transferred.
[1] 1
> 
> x2; file.info(x2)
[1] "Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file983059194ef9.xml"
                                                                                                                                   size
Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file983059194ef9.xml   NA
                                                                                                                                   isdir
Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file983059194ef9.xml    NA
                                                                                                                                   mode
Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file983059194ef9.xml <NA>
                                                                                                                                   mtime
Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file983059194ef9.xml  <NA>
                                                                                                                                   ctime
Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file983059194ef9.xml  <NA>
                                                                                                                                   atime
Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file983059194ef9.xml  <NA>
                                                                                                                                    exe
Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file983059194ef9.xml <NA>
>

**Comment by ranghetti** [comment]
Now? 
```r
system(paste0(binpaths$gsutil," -m -q cp -r ",x1[1]," ",x2 <- tempfile(tmpdir = shortPathName(tempdir()), fileext=".xml")))
x2; file.info(x2)
```

**Comment by naeem32567** [comment]
I installed sen2r on another windows machine ... it works fine. I think i probably need to do a fresh install on the machine i am working on.. the tmp folders are not right. Will let you know if I am successful. However, the output for code above ...  

> system(paste0(binpaths$gsutil," -m -q cp -r ",x1[1]," ",x2 <- tempfile(tmpdir = shortPathName(tempdir()), fileext=".xml")))
CommandException: No URLs matched: Y:\\Satellite\\sentinel2\\n_rhm\\2_Development\\Raw
CommandException: No URLs matched: sentinel
CommandException: No URLs matched: data
CommandException: Multiple URL strings are not supported with streaming ("-") URLs or named pipes.
CommandException: Destination URL must name a directory, bucket, or bucket
subdirectory for the multiple source form of the cp command.
CommandException: 5 files/objects could not be transferred.
[1] 1
> x2; file.info(x2)
[1] "Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file98304bf53c7e.xml"
                                                                                                                                   size
Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file98304bf53c7e.xml   NA
                                                                                                                                   isdir
Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file98304bf53c7e.xml    NA
                                                                                                                                   mode
Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file98304bf53c7e.xml <NA>
                                                                                                                                   mtime
Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file98304bf53c7e.xml  <NA>
                                                                                                                                   ctime
Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file98304bf53c7e.xml  <NA>
                                                                                                                                   atime
Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file98304bf53c7e.xml  <NA>
                                                                                                                                    exe
Y:\\\\Satellite\\\\sentinel2\\\\n_rhm\\\\2_Development\\\\Raw sentinel data - Jan - June - empty\\RtmpqE5Rd5\\file98304bf53c7e.xml <NA>
>

**Comment by ranghetti** [comment]
@naeem32567 have you tried if the error was solved on the first machine, after ensuring `tempdir()` is pointing to an existing directory?
