### ISSUE TITLE
How to download available single file ordered?

### ISSUE THREAD

**Issue by Gianfilippo7797** [ranghetti/sen2r#426]
Is it possibile to choose a single ordered file to download? Which is the command that I have to use?
I ordered files few days ago, but now there are 5 of them available. How can I choose which one to download?

<img width="375" alt="Schermata 2021-09-16 alle 12 24 38" src="https://user-images.githubusercontent.com/90836927/133596066-e488963c-5ac0-4b9e-adb3-d9e7efedf983.png">

**Comment by ranghetti** [comment]
Simply download the whole list using `s2_download()`: available archives will be downloaded, ordered ones will not.

PS. if you will need further assistence, please provide all the information required in the issue template (in your case, with a reproducible example I would have provided a more detailed answer).
