### ISSUE TITLE
SystemRequirements of sen2r

### ISSUE THREAD

**Issue by edzer** [ranghetti/sen2r#463]
sen2R DESCRIPTION lists
```
SystemRequirements: | GDAL (>= 2.1.2), PROJ (>= 4.9.1), GEOS (>= 3.4.2), Cairo, Curl, NetCDF, jq, Protocol Buffers, V8, OpenSSL, Libxml2.
```
this package however does not have any system requirements. I think that [WRE](https://cran.r-project.org/doc/manuals/R-exts.html) only requires packages that need system requirements to list those.

**Comment by ranghetti** [comment]
Thanks @edzer for pointing out that. Actually these are system requirements of packages listed in Imports, which should not be listed here. I will remove them in the next CRAN release.
