### ISSUE TITLE
Plotting and styling S2

### ISSUE THREAD

**Issue by ranghetti** [ranghetti/sen2r#7]
Output products come without any style information, but each product has its own (e.g. SCL has a specific colour palette, TOA/BOA can have almost three RGB visualisation).

It could be useful:
1) to implement methods to assign default styles for leaflet, spplot, sprawl, ... when plotting products in R;
2) to create styling files together with output products (a common `.aux.xml` if possible, otherwise a `.qml` for QGIS and others for other applications.

**Comment by rcabas** [comment]
This improvement means that we can assign an speciffic pallette after we use raster2rgb()?
I am trying to use this function to put colors int the final JPG product... but it was not possible? any alternative?
Thanks!

**Comment by ranghetti** [comment]
`raster2rgb()` is an internal function used to produce thumbnails, which are products thought in order to have an idea about what a processing chain produced; for this reason, customisation is not possible. [Here](https://github.com/ranghetti/sen2r/tree/master/inst/extdata/palettes) there are some palettes for QGIS.
Regarding RGB images, you can use function `s2_rgb()` or define your custom RGB palette in the GUI.

**Comment by ranghetti** [comment]
I am closing very old issues; if you have further questions, please open a new issue.
