### ISSUE TITLE
s2_thumbnails() sometimes fails on BOA

### ISSUE THREAD

**Issue by ranghetti** [ranghetti/sen2r#82]
Thumbnails of some BOA images (i.e. Arborea, but not Cortona and Jolanda) are computed wrongly (only first band - red - is present, while other two ones are NA).

**Comment by ranghetti** [comment]
Now BOA and TOA uses GTiff intermediate files instead of VRT (`gdal_calc()` failed using vrt as input, computing only the first band).

**Comment by WalterCh** [comment]
Hi, it seems like I'm getting this error,
 I've done the whole processing with this bounding box
![image](https://user-images.githubusercontent.com/38228086/72617062-316c7580-3906-11ea-9d82-c321cabecf4e.png)
And then with another 'small' place within the boundin box
![image](https://user-images.githubusercontent.com/38228086/72617267-97f19380-3906-11ea-9c12-3644ccec8780.png)
But I get these red images in thumbnails of every product and these grey tiffs
![image](https://user-images.githubusercontent.com/38228086/72617433-ebfc7800-3906-11ea-9df6-cc1371d80760.png)

Except for BOA, the thumbnails are black.
This is the code I used for the smaller bounding box


```
# Libraries
library(sen2r)

# sen2r
out_path <- sen2r(
  gui = FALSE,
  step_atmcorr = "auto",
  extent = "D:/Geocomputation/udep/udep.geojson",
  extent_name = "UDEP",
  online = TRUE,
  overwrite = TRUE,
  timewindow = as.Date("2016-02-05"),
  list_prods = "BOA",
  list_indices = c("NDVI","ARVI"),
  path_l1c = "D:/Geocomputation/bosque-seco-norperu/Sen2-levels/L1C",
  path_l2a = "D:/Geocomputation/bosque-seco-norperu/Sen2-levels/L2A",
  path_out = "D:/Geocomputation/udep/Products"
)

# Thumbnail visualisation
thumb <- file.path(dirname(out_path), "thumbnails", gsub("tif$", "jpg", basename(out_path)))
thumb[grep("BOA", thumb)] <- gsub("jpg$", "png", thumb[grep("BOA", thumb)])

image(stars::read_stars(thumb[grep("NDVI", thumb)]), rgb = 1:3)
```

![image](https://user-images.githubusercontent.com/38228086/72617770-b5732d00-3907-11ea-9790-6632fc98197c.png)

**Comment by ranghetti** [comment]
Hi, please do not necro-post. Report this error in a new issue, including also some other useful information as specified in #186 (in your case, in the new issue include also the content of `"D:/Geocomputation/udep/udep.geojson"`). Thanks
