### ISSUE TITLE
Python Version Issues

### ISSUE THREAD

**Issue by RAJohansen** [ranghetti/sen2r#89]
I have not been able to get pasted the python version issues. Do you have any advice?

Thank you,
Richard

```
[2018-06-15 14:06:56] Starting sen2r execution.
Error in python_config(python_version, required_module, python_version,  : 
  Error 1 occurred running C:\OSGEO4~1\bin\python.exe 
In addition: Warning message:
In system2(command = python, args = paste0("\"", config_script,  :
  running command '"C:\OSGEO4~1\bin\python.exe" "C:/user/Documents/R/R-3.5.0/library/reticulate/config/config.py"' had status 1
```

**Comment by ranghetti** [comment]
Dear Richard,
it seems to be a problem related to the Python environment which the package reticulate is trying to use. Is C:\OSGEO41\ the directory in which your OSGeo4W environment is installed? If so, can you try to [update it](http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe) (or delete it and then launch `check_sen2r_deps()` to install it again)?
If this does not solve, consider that I am curerntly working on a dockerised version of the package, which should solve problems related to local issues with dependencies.

**Comment by poniitty** [comment]
Thank you for very useful R package.

However, I have exactly the same issue as RAJohansen above. 

I tried to update, delete and reinstall the OSGeo4W and/or python, but nothing helped.

Have you any further suggestions?

Best Regards,
Pekka

**Comment by RAJohansen** [comment]
@ranghetti @poniitty , 

I have tried multiple times to reinstall, delete, update OSgeo4W. However, I was never able to call the function check_sen2r_deps(), nor could I find it in the package by ?check_sen2r_deps(). Also, I was not always able to run the installation GUI. 

Hopefully this helps, and I really looking forward to using this package once all the kinks are worked out. 

Thank you,
Richard

**Comment by ranghetti** [comment]
Dear @RAJohansen and @poniitty ,
thank you for your feedbacks. I am going to make some tests on a Windows machine in order to understand the reason. I will update you during next days.

@RAJohansen , sorry, I had forgotten about exporting that function; now you should be able to run it.

**Comment by lbusett** [comment]
Hi Luigi and all, 

     seems like a windows path problem to me. I seem to remember that on windows, OSGEO is often installed in a folder which gets the "windows abbreviation" to "C:\OSGEO4~1"

@RAJohansen: 

- Cold you confirm that a folder named "C:\OSGEO41\" (with no tilde) exists on your machine ? 
- Do you happen to have multiple OSGEO installation on you machine ? 
- What happens if you open a windows terminal via "cmd" (or from within RStudio) and run the command
"C:\OSGEO41\bin\python.exe" ? 

Lorenzo

**Comment by ranghetti** [comment]
I made a first try, with which I would not be able to reproduce the error: sen2r installed correclty, using a Python installation in your same path (`"C:\OSGEO4~1\bin\python.exe"`).

Can you post the output of these two commands?
1. `jsonlite::fromJSON(system.file("extdata","paths.json",package="sen2r"))`
2. `sen2r:::init_python()`

**Comment by RAJohansen** [comment]
@lbusett 
1. Yes, my OSGEO4 is located at "C:\OSGEO4W64" 
2. No, I do not have multiple OSGEO installed. 
3. Not exactly how to interpret your last comment, but this is what I get when I run that command in R studio.
> "C:/OSGEO4~1/bin/python.exe"
[1] "C:/OSGEO4~1/bin/python.exe"

**Comment by ranghetti** [comment]
I'm closing this isssue due to inactivity.
@RAJohansen  and @poniitty, feel free to reopen it if you will spot new problems related to this issue.
